### PR TITLE
fix(core): properly report missing providers and viewProviders

### LINKED ISSUE #8237: Uncaught Token must be defined!
Hello, after updating to angular beta 16 I started getting this error. Does anyone have an idea what can cause this?

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
Bore this change a missing provider / viewProvider would result in a cryptic "can't read .properties of null" for cases when a given provider is not defined. This happens quite often in plunkers where an import might be misspelled and fail silently. 

Fixes #8237

### CODE REVIEW

File: modules/@angular/compiler/src/metadata_resolver.ts [hunk 1]
```diff
@@ -423,6 +425,23 @@ function flattenArray(tree: any[], out: Array<Type|any[]>): void {
...
 
+function verifyNonBlankProviders(
+    directiveType: Type, providersTree: any[], providersType: string): any[] {
+  var flat: any[] = [];
+  var errMsg: string;
+
+  flattenArray(providersTree, flat);
+  for (var i = 0; i < flat.length; i++) {
+    if (isBlank(flat[i])) {
+      errMsg = flat.map(_ => isBlank(_) ? '?' : stringify(_)).join(', ');
```
Comment (vicb) [inline modules/@angular/compiler/src/metadata_resolver.ts]: use a name parameters rather than `_` - use `_` only when the param is not used

File: modules/@angular/compiler/src/metadata_resolver.ts [hunk 2]
```diff
@@ -423,6 +425,23 @@ function flattenArray(tree: any[], out: Array<Type|any[]>): void {
...
+      throw new BaseException(
+          `One or more of ${providersType} for "${stringify(directiveType)}" were not defined: (${errMsg}).`);
```
Comment (vicb) [inline modules/@angular/compiler/src/metadata_resolver.ts]: `(...)` => `[...]` ?

**Comment by vicb** [comment]
a few minor comments

**Comment by pkozlowski-opensource** [comment]
Thnx @vicb ! Just pushed an update.

**Comment by vicb** [comment]
Thanks, will be merged after the rc3
