### PR TITLE
fix(datePipe): allow float for date pipe input

### LINKED ISSUE #10125: DatePipe Exception on Decimal
```[x] bug report```

**Current behavior**
```{{ '1123.11' | date:'mm:ss' }}```
results in
````Invalid integer literal when parsing 1123.11 in base 10```

**Expected/desired behavior**
If no intention to use fractions of milliseconds then we should just discard the decimal places.

**What is the motivation / use case for changing the behavior?**
Sometimes date/time values contain a fraction of milliseconds, resulting in decimal values.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
* **Browser:** Firefox 47.0.1

### PR DESCRIPTION
**Pull request by laskoviymishka**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
Date pipe accept decimal, but fails with Invalid integer literal when parsing  in base 10

**What is the new behavior?**
Date pipe accept decimal and work nice with it

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

Closes #10125

### CODE REVIEW

File: modules/@angular/common/src/pipes/date_pipe.ts [hunk 1]
```diff
@@ -104,7 +104,7 @@ export class DatePipe implements PipeTransform {
     }
 
     if (NumberWrapper.isNumeric(value)) {
-      value = DateWrapper.fromMillis(NumberWrapper.parseInt(value, 10));
+      value = DateWrapper.fromMillis(NumberWrapper.parseFloat(value));
```
Comment (vicb) [inline modules/@angular/common/src/pipes/date_pipe.ts]: pls remove the use of NumberWrapper
needs test

Comment (laskoviymishka) [inline modules/@angular/common/src/pipes/date_pipe.ts]: Sure.

**Comment by laskoviymishka** [comment]
@vicb done. Test was added. Now I use just `parseFloat` instead of pointing `NumberWrapper`. I assume that this class should be marked as obsolete, is it so?
By some reason one of build job failed on test `WebWorker Router should route on click`. I believe that this some internal travis-ci issue, which is not related to my change.

**Comment by vicb** [comment]
`NumberWrapper ` is internal only so no `@deprecated` but will be removed soon

**Comment by vicb** [comment]
Thanks for the update. I'll restart Travis

**Comment by laskoviymishka** [comment]
Travis is green. Hooray!
I think number wrapper should be replaced by some helper functions. Whole facade itself is pretty obsolete, since dart was removed.
