### PR TITLE
[4.x only] fix(compiler): improve error msg for unexpected closing tags

### LINKED ISSUE #6652: Better error messages when encountering invalid HTML
Opening this issue as a result of #6648 
It would improve the developer experience to give more detail error messages when the template parser encounters invalid HTML.
#### Example

Say you have some HTML like this:

``` html
<p><div></div></p>
```

This is invalid because `<p>` may only contain ["phrasing content"](https://www.w3.org/TR/html-markup/common-models.html#common.elem.phrasing). This is one of the more obscure rules in the specification. 

When Angular encounters this, the error message is:

```
EXCEPTION: Template parse errors:
Unexpected closing tag "p" ("<p><div></div>[ERROR ->]</p>"): HelloWorld@0:14
```

The developer here doesn't really know what the problem is, especially since actual browsers will accept this and still render something.

cc @vicb

### PR DESCRIPTION
**Pull request by DzmitryShylovich**
Closes #6652

### CODE REVIEW

File: modules/@angular/compiler/src/ml_parser/parser.ts [hunk 1]
```diff
@@ -306,8 +306,9 @@ class _TreeBuilder {
           fullName, endTagToken.sourceSpan,
           `Void elements do not have end tags "${endTagToken.parts[1]}"`));
     } else if (!this._popElement(fullName)) {
-      this._errors.push(TreeError.create(
-          fullName, endTagToken.sourceSpan, `Unexpected closing tag "${endTagToken.parts[1]}"`));
+      const errMsg =
+          `Unexpected closing tag "${fullName}". It may happen when the tag has already been closed by another tag. For more info see "Tag omission" on https://developer.mozilla.org/en/docs/Web/HTML/Element/${fullName}`;
```
Comment (vicb) [inline modules/@angular/compiler/src/ml_parser/parser.ts]: what about linking to the html5 spec or a wiki page instead ?
The link might not exist when the error is due to a typo.

Comment (DzmitryShylovich) [inline modules/@angular/compiler/src/ml_parser/parser.ts]: do you have a good link? anyway I think it will be too generic and I don't think anybody will read html spec tbh :)

Plus 404 page will give a hint to a user that something wrong with element name

Comment (vicb) [inline modules/@angular/compiler/src/ml_parser/parser.ts]: https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags

No way we have error msgs linking 404 !

Comment (DzmitryShylovich) [inline modules/@angular/compiler/src/ml_parser/parser.ts]: as you wish :)

But as for me mdn has a much better explanation. I wouldn't understand anything from the spec.

Comment (DzmitryShylovich) [inline modules/@angular/compiler/src/ml_parser/parser.ts]: @vicb done

**Comment by vicb** [comment]
Thanks for the update !
LGTM

**Review by vicb — APPROVED** [review]

**Review by chuckjaz — APPROVED** [review]
