### PR TITLE
fix(common): do not reference deprecated classes in providers

### LINKED ISSUE #14521: Compiler generates references to a deprecated class.
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**

When using `*ngFor`, the compiler will generate a reference to `NgFor` in the provider for the component. `NgFor` is deprecated in favor of `NgForOf<T>` and will issue warning if the code is checked for references to deprecated symbols.

**Expected behavior**

The compiler should only generated references to deprecated classes only if a depreciated class is declared or imported into the module it is declared in and part of the template matches the selector for the component or directive.

**Minimal reproduction of the problem with instructions**

Any template with a `*ngFor`.

**What is the motivation / use case for changing the behavior?**

Avoiding deprecated references.

### PR DESCRIPTION
**Pull request by chuckjaz**
References to `NgFor` are now an alias for `NgForOf` instead of a derived class.

Fixes #14521

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
```

**What is the current behavior?** (You can also link to an open issue here)

The compiler will generate references to the deprecated class `NgFor` because the `NgFor` is reference in the provider for `NgForOf<T>`.

**What is the new behavior?**

The compiler no longer generates references to the deprecated `NgFor` class.

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by vicb** [comment]
Do we need to keep `NgFor` then ?
Would `export const NgFor = NgForOf` work ? If not may be add a 'before/after` code snippet to the commit message.

File: modules/@angular/common/test/directives/ng_for_spec.ts [hunk 1]
```diff
@@ -350,6 +350,14 @@ export function main() {
            getComponent().items = ['e', 'f', 'h'];
            detectChangesAndExpectText('efh');
          }));
+
+      it('should support injecting `NgFor` and get an instance of `NgForOf`', async(() => {
+           const template = `<template ngFor [ngForOf]='items' let-item test></template>`;
+           fixture = createTestComponent(template);
+           const testDirective = fixture.debugElement.childNodes[0].injector.get(TestDirective);
```
Comment (vicb) [inline modules/@angular/common/test/directives/ng_for_spec.ts]: `const testDirective = fixture.debugElement.query(By.directive(TestDirective));`

Why not inject both in the td ?

Comment (chuckjaz) [inline modules/@angular/common/test/directives/ng_for_spec.ts]: Both?

Comment (chuckjaz) [inline modules/@angular/common/test/directives/ng_for_spec.ts]: Also `query` seems to return the `DebugElement` and not `TestDirective`

**Review by IgorMinar — APPROVED** [review]
