### PR TITLE
fix(core): prevent child animation elements from being orphaned

### LINKED ISSUE #67400: In some cases, the `animate.leave` animations leave a component in the DOM.
### Which @angular/* package(s) are the source of the bug?

animations

### Is this a regression?

Yes

### Description

With Angular 21.2.0 it seems that something broke with the CSS animations. To make thinks simple I created a directive to add animations to html elements. This directive uses `animate.leave`. 

Starting from version 21.2.0, it seems that components are not removed after they animate on "leave" when routing away from an component. See the stackblitz below. It mini project has 2 routes with components. And 2 links that switch between the two routes.

I think it is related to https://github.com/angular/angular/pull/67032

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-htmhdsyu

If you click on `first`, then `second`, you will notice that the new component showing "TEST" appears, but the old component (green square) stays and is not removed from the DOM. 

Clicking on `first` again, will show another (duplicate) component (green square).

### Please provide the exception or error you saw
```true
Components not being removed.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI       : 21.2.0
Angular           : 21.2.0
Node.js           : 24.13.0
Package Manager   : npm 11.6.2
Operating System  : win32 x64

┌───────────────────────────────────┬───────────────────┬───────────────────┐
│ Package                           │ Installed Version │ Requested Version │
├───────────────────────────────────┼───────────────────┼───────────────────┤
│ @angular/build                    │ 21.2.0            │ ^21.2.0           │
│ @angular/cli                      │ 21.2.0            │ ^21.2.0           │
│ @angular/common                   │ 21.2.0            │ ^21.2.0           │
│ @angular/compiler                 │ 21.2.0            │ ^21.2.0           │
│ @angular/compiler-cli             │ 21.2.0            │ ^21.2.0           │
│ @angular/core                     │ 21.2.0            │ ^21.2.0           │
│ @angular/forms                    │ 21.2.0            │ ^21.2.0           │
│ @angular/localize                 │ 21.2.0            │ ^21.2.0           │
│ @angular/platform-browser         │ 21.2.0            │ ^21.2.0           │
│ @angular/platform-browser-dynamic │ 21.2.0            │ ^21.2.0           │
│ @angular/router                   │ 21.2.0            │ ^21.2.0           │
│ @angular/service-worker           │ 21.2.0            │ ^21.2.0           │
│ rxjs                              │ 7.8.2             │ ^7.8.2            │
│ typescript                        │ 5.9.3             │ ~5.9.3            │
│ zone.js                           │ 0.15.1            │ ~0.15.1           │
└───────────────────────────────────┴───────────────────┴───────────────────┘
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by thePunderWoman**
When routing between two different routes, child animations were not finishing, causing elements to be left behind in the dom. The fix ensures the proper fallback is handled to avoid automatically cancelled custom events. This ensures the animation-fallback cancelling the animation actually completes, and ensures the element is removed.

fixes: #67400

### CODE REVIEW

File: packages/core/src/render3/instructions/animation.ts [hunk 1]
```diff
@@ -317,17 +322,25 @@ function animateLeaveClassRunner(
 ) {
   cancelAnimationsIfRunning(el, renderer);
   const cleanupFns: VoidFunction[] = [];
-  const resolvers = getLViewLeaveAnimations(lView).get(tNode.index)?.resolvers;
+  const componentResolvers = getLViewLeaveAnimations(lView).get(tNode.index)?.resolvers;
+  let fallbackTimeoutId: any;
```
[the remark this answers is not in the document]
Comment (thePunderWoman) [reply packages/core/src/render3/instructions/animation.ts]: We've been avoiding typing on timeouts like this as they can cause issues. We can probably just go with `as unknown as number`.

File: packages/core/src/render3/instructions/animation.ts [hunk 2]
```diff
@@ -317,17 +322,25 @@ function animateLeaveClassRunner(
...
+  const componentResolvers = getLViewLeaveAnimations(lView).get(tNode.index)?.resolvers;
+  let fallbackTimeoutId: number | undefined;
+  let hasCompleted = false;
 
   const handleOutAnimationEnd = (event: AnimationEvent | TransitionEvent | CustomEvent) => {
-    // this early exit case is to prevent issues with bubbling events that are from child element animations
-    if (event.target !== el) return;
-    if (event instanceof CustomEvent || isLongestAnimation(event, el)) {
+    // Custom fallback events don't have a target, so we bypass this check for them.
+    if (event.target !== el && event.type !== 'animation-fallback') return;
```
Comment (crisbeto) [inline packages/core/src/render3/instructions/animation.ts:331]: It's worth noting that `event.target` is a bit weird if the event comes from the shadow DOM. We use this utility in Components: https://github.com/angular/components/blob/main/src/cdk/platform/features/shadow-dom.ts#L59

**Review by crisbeto — APPROVED** [review]

File: packages/core/src/render3/instructions/animation.ts (hunk 2 above)
Comment (thePunderWoman) [reply packages/core/src/render3/instructions/animation.ts:331]: Good to know. I'll do a quick follow up after this to use a similar function.

**Comment by thePunderWoman** [comment]
This PR was merged into the repository. The changes were merged into the following branches:

- main: 9e64147b731a1d9d0a36074b77c1e21e3fb49ea7
- 21.2.x: b4ec3cc4e41f2948ad0830eb14aa05d14fa3a9ed
