### PR TITLE
Multiple zone callbacks (phase 1)

### LINKED ISSUE #4535: Allow multiple callback overrides in NgZone
Angular seems to only allow one override for onTurnStart and onEventDone in NgZone [1]. The Testability API is overriding these callbacks [2] and we have some internal stuff (see b/24673935) that also overrides it. However, due to the mentioned limitation, only the last registration is actually successful. All earlier registrations are silently ignored. 

This is a problem for our webdriver and latency tests because if the testability API looses this race, it will never be able to tell our tests that the angular app is stable. Our test will then time out waiting for the testability api to tell us that the app is stable, which will never happen due to the broken callback registration.

This bug is internally tracked at b/24673935.

[1] https://github.com/angular/angular/blob/master/modules/angular2/src/core/zone/ng_zone.dart#L114
[2] https://github.com/angular/angular/blob/master/modules/angular2/src/core/testability/testability.ts#L25

### PR DESCRIPTION
**Pull request by yjbanov**
- introduce `NgZone` event Streams/Observables to allow multiple subscribers
- deprecate old `override` methods

fixes #4535

Phase 2 is to clean up usages of deprecated API and delete it.

### CODE REVIEW

File: modules/angular2/src/core/zone/ng_zone.dart [hunk 1]
```diff
@@ -103,19 +120,44 @@ class NgZone {
...
    * Sets the zone hook that is called immediately after Angular processes
    * all pending microtasks.
    */
+  @Deprecated('Use onTurnDone Stream instead')
   void overrideOnTurnDone(ZeroArgFunction onTurnDoneFn) {
     _onTurnDone = onTurnDoneFn;
   }
 
   /**
+   * Notifies subscribers immediately after Angular zone is done processing
```
Comment (TedSander) [inline modules/angular2/src/core/zone/ng_zone.dart]: Is this better?
after Angular zone -> after the Angular zone

File: modules/angular2/src/core/zone/ng_zone.dart [hunk 2]
```diff
@@ -137,15 +180,55 @@ class NgZone {
...
+   */
+  bool get hasPendingMicrotasks => _pendingMicrotasks > 0;
+
+  /**
+   * Whether there are any outstanding timers.
+   */
+  bool get hasPendingTimers => _pendingTimers.isNotEmpty;
+
+  /**
+   * Whether there are any outstanding asychnronous tasks of any kind that are
```
Comment (TedSander) [inline modules/angular2/src/core/zone/ng_zone.dart]: asychnronous -> asynchronous

File: modules/angular2/src/core/zone/ng_zone.dart [hunk 3]
```diff
@@ -103,19 +120,44 @@ class NgZone {
...
+   *
+   * Emits an event once per browser task that is handled by Angular.
+   */
+  Stream get onTurnStart => _onTurnStartCtrl.stream;
+
   /**
    * Sets the zone hook that is called immediately after Angular processes
    * all pending microtasks.
    */
+  @Deprecated('Use onTurnDone Stream instead')
```
Comment (TedSander) [inline modules/angular2/src/core/zone/ng_zone.dart]: Maybe file an issue to cleanup these deprecations... or perhaps just a calendar entry for yourself. Would be nice to clean them up, makes the code a bit more complicated.

File: modules/angular2/test/core/zone/ng_zone_spec.ts [hunk 4]
```diff
@@ -201,42 +249,73 @@ function commonTests() {
...
+         }, resultTimer);
+       }), testTimeout);
+
+    it('should run subscriber listeners the subscription zone (inside)',
+       inject([AsyncTestCompleter], (async) => {
+         // the only practical use-case to run a callback inside the zone is
+         // change detection after "onTurnDone". That's the only case tested.
+         var turnDone = false;
+         ObservableWrapper.subscribe(_zone.onTurnDone, (_) => {
+           _log.add('onTurnDone');
```
Comment (TedSander) [inline modules/angular2/test/core/zone/ng_zone_spec.ts]: This looks weird to me. Is it an error if this is called twice? Why log both times?

File: modules/angular2/test/core/zone/ng_zone_spec.ts [hunk 5]
```diff
@@ -201,42 +249,73 @@ function commonTests() {
...
+           if (turnDone) return;
+           _zone.run(() => { microTask(() => {}); });
+           turnDone = true;
+         });
 
          macroTask(() => { _zone.run(_log.fn('run')); });
 
          macroTask(() => {
-           expect(_log.result()).toEqual('run; onTurnDone; onEventDone');
+           expect(_log.result()).toEqual('run; onTurnDone; onTurnDone');
```
Comment (TedSander) [inline modules/angular2/test/core/zone/ng_zone_spec.ts]: Why did this change from onEventDone?

**Comment by TedSander** [comment]
Mostly looks good. Just a couple of questions, and doc cleanup stuff.

File: modules/angular2/test/core/zone/ng_zone_spec.ts (hunk 4 above)
Comment (yjbanov) [inline modules/angular2/test/core/zone/ng_zone_spec.ts]: Because when you run inside the zone a new microtask cases a new turn. The test sets up an expectation that we come back here a second time by logging `onTurnDone` twice then verifying it. This distinguishes this test from the `(outside)` test above.

File: modules/angular2/test/core/zone/ng_zone_spec.ts (hunk 5 above)
Comment (yjbanov) [inline modules/angular2/test/core/zone/ng_zone_spec.ts]: Previously, `NgZone` called your callback directly and it had the semantics that your callback would be called outside of Angular zone. This test used to verify those semantics. With streams, however, the _developer_ decides which zone to run their callbacks in (it's the zone where you call `stream.listen`).

Comment (TedSander) [inline modules/angular2/test/core/zone/ng_zone_spec.ts]: Thanks for the clarification. Makes sense.

File: modules/angular2/src/core/zone/ng_zone.dart (hunk 1 above)
Comment (yjbanov) [inline modules/angular2/src/core/zone/ng_zone.dart]: done

File: modules/angular2/src/core/zone/ng_zone.dart (hunk 2 above)
Comment (yjbanov) [inline modules/angular2/src/core/zone/ng_zone.dart]: done

File: modules/angular2/src/core/zone/ng_zone.dart (hunk 3 above)
Comment (yjbanov) [inline modules/angular2/src/core/zone/ng_zone.dart]: done: https://github.com/angular/angular/issues/4846
