### PR TITLE
fix(dart/transform): Handle mixed lifecycle specs

### LINKED ISSUE #3276: Specifying both 'lifecycle' and interfaces causes invalid generated code
Repro:

```dart
@Component(
  lifecycle: const [LifecycleEvent.onInit]
)
class Foo implements OnInit {
  ...
}
```

This would cause the transformer to generate the following in `ng_deps`:

```dart
const Component(
  lifecycle: const[LifecycleEvent.onInit],
  lifecycle: const[LifecycleEvent.onInit]
)
```

### PR DESCRIPTION
**Pull request by kegluneq**
Update the transformer to handle classes which both have a `lifecycle`
value and `implement` lifecycle interfaces.

Closes #3276

### CODE REVIEW

File: modules/angular2/test/transform/directive_processor/multiple_interface_lifecycle_files/soup.dart [hunk 1]
```diff
@@ -4,3 +4,6 @@ import 'package:angular2/annotations.dart';
 
 @Component(selector: '[soup]')
 class MultiSoupComponent implements OnChange, OnDestroy, OnInit {}
+
+@Component(selector: '[soup]', lifecycle: const [LifecycleEvent.onCheck])
+class MixedSoupComponent implements OnChange {}
```
Comment (yjbanov) [inline modules/angular2/test/transform/directive_processor/multiple_interface_lifecycle_files/soup.dart]: Also add a test in which `lifecycle` _and_ the interface are the same, e.g. `LifecycleEvent.onChange`&`implements OnChange`
