### PR TITLE
fix(forms): Resolves debounce promise on abort in debounceForDuration

### LINKED ISSUE #66646: [signal forms]: debounceForDuration does not resolve its Promise on abort, causing pending awaits
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

The current implementation of debounceForDuration does not resolve or reject the returned Promise when the associated AbortSignal is aborted ([source](https://github.com/angular/angular/blob/5d46554e3fe8b64c5fefc7a8ce891c179741977e/packages/forms/signals/src/api/rules/debounce.ts#L44)).

As a result, callers awaiting this Promise may remain suspended indefinitely. In particular, debounceSync awaits debounceForDuration ([source](https://github.com/angular/angular/blob/5d46554e3fe8b64c5fefc7a8ce891c179741977e/packages/forms/signals/src/field/node.ts#L324)), and if the debounce is aborted, the await never resolves.

This can lead to:
- async execution paths that never complete
- retention of async stack frames and captured variables
- potentially increased memory usage in long-running or frequently triggered scenarios

Resolving the Promise on abort would avoid this issue. This should be safe, as debounceSync already checks `controller.signal.aborted` before performing the sync operation, so resolving early would not change observable behavior—only ensure proper completion of the async flow.

### Please provide a link to a minimal reproduction of the bug

_No response_

### Please provide the exception or error you saw

```true

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI       : 21.0.5
Node.js           : 24.13.0
Package Manager   : npm 11.6.2
Operating System  : darwin arm64
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by SkyZeroZx**
Ensures the promise returned by the debouncer resolves when aborted, preventing potential hangs for awaiting consumers. Fixes #66646

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/contributing-docs/commit-message-guidelines.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

 

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.dev application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

 
Issue Number: #66646

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: packages/forms/signals/src/api/rules/debounce.ts [hunk 1]
```diff
@@ -46,6 +46,7 @@ function debounceForDuration(durationInMilliseconds: number): Debouncer<unknown>
 
       const onAbort = () => {
         clearTimeout(timeoutId);
+        resolve();
```
Comment (SkyZeroZx) [inline packages/forms/signals/src/api/rules/debounce.ts:49]: I haven't found a way to replicate the problem mentioned with a test; however, I think it's right that we solve the problem to avoid any unexpected behavior or memory leak

**Comment by kirjs** [comment]
Thank you, I know @leonsenft is working in that area right now, so adding him as a reviewer

File: packages/forms/signals/src/api/rules/debounce.ts (hunk 1 above)
Comment (leonsenft) [reply packages/forms/signals/src/api/rules/debounce.ts:49]: Yeah, I agree this is correct. I don't believe we can properly unit test this without exporting the private `debounceForDuration` API.

**Review by leonsenft — APPROVED** [review]

**Comment by leonsenft** [comment]
This PR was merged into the repository. The changes were merged into the following branches:

- main: b1bf535f8e5cbeaec23e9dbb98c1a1bb99deb62a
- 21.1.x: 6f75b6e3f60dc2a4f33e13562649931dc95eb52b
