### PR TITLE
fix(compiler): clone templates before compiling them

### LINKED ISSUE #1058: Shadow DOM Emulation: two components in a template, the second does not get content projection
I have two components: `MdButton` and `MdAnchor`. Their selectors are `[md-button]:not([href])` and `[md-button][href]`, respectively. They both use the same template:
```html
<link href="../button.css" rel="stylesheet">
<span class="md-button-wrapper"><content></content></span>
```

I have a demo where I render out some buttons and some anchors. It looks something like this:
```html
<button md-button>BUTTON</button>
<a md-button href="http://google.com">ANCHOR</a>
```

Whichever component is second on the page does not receive content projection. Instead, the placeholder `<script>` tags are still there.

You can see this issue locally:
```
git fetch https://github.com/jelbourn/angular.git material-2
get checkout tags/projection-bug
npm install gulp-sass
npm install gulp-autoprefixer
gulp build.material
gulp serve.js.dev
```
Then visit `http://localhost:8000/angular2/src/material/components/button/demo/?`
You can see that the anchors do not have their content projected, while the buttons do. If you remove all of the buttons and leave only the anchors, they work fine. Re-add another button after the anchors, and then that button will have the problem.

### PR DESCRIPTION
**Pull request by tbosch**
This is needed as the compiler changes templates during compilation
and we are caching templates in the `TemplateLoader`.

Closes #1058

### CODE REVIEW

File: modules/angular2/src/render/dom/compiler/compiler.js [hunk 1]
```diff
@@ -47,7 +47,10 @@ export class Compiler {
   _compileTemplate(viewDef: ViewDefinition, tplElement):Promise<ProtoViewDto> {
     var subTaskPromises = [];
     var pipeline = new CompilePipeline(this._stepFactory.createSteps(viewDef, subTaskPromises));
-    var compileElements = pipeline.process(tplElement, viewDef.componentId);
+    // we need to clone the template element as we modify it
+    // and it might be given to use again as the TemplateLoader
+    // uses an internal cache.
+    var compileElements = pipeline.process(DOM.clone(tplElement), viewDef.componentId);
```
Comment (yjbanov) [inline modules/angular2/src/render/dom/compiler/compiler.js]: This seems wrong. `TemplateLoader` should return a new node and we should cache the result of compilation.

File: modules/angular2/src/render/dom/compiler/template_loader.js [hunk 2]
```diff
@@ -39,7 +39,7 @@ export class TemplateLoader {
         StringMapWrapper.set(this._htmlCache, url, promise);
       }
 
-      return promise;
+      return promise.then( (tplElement) => DOM.clone(tplElement) );
```
Comment (yjbanov) [inline modules/angular2/src/render/dom/compiler/template_loader.js]: explain why cloning is necessary
