### PR TITLE
fix(language-service): avoid interpolation highlighting inside `@let`

### LINKED ISSUE #61643: @let doesn't support string interpolation using @let var =  '{{ variable }}' syntax
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

@let template syntax doesn't support standard angular interpolation syntax like @let var =  '{{ variable }}'. meanwhile language services highlight these variables inside strings as interpolated. 

Image

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-6wvun8yy?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 19.2.3
Node: 18.20.4
Package Manager: npm 10.7.0
OS: win32 x64

Angular: 19.2.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1902.3
@angular-devkit/build-angular   19.2.3
@angular-devkit/core            19.2.3
@angular-devkit/schematics      19.2.3
@angular/cdk                    19.2.3
@angular/cli                    19.2.3
@angular/material               19.2.3
@schematics/angular             19.2.3
rxjs                            7.8.1
typescript                      5.8.2
zone.js                         0.15.0
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by SkyZeroZx**
This change omits treating `{{ }}` interpolation syntax as valid inside `@let` binding strings, preventing the interpolation curly braces from superseding the match of the surrounding binding expression and ensuring the highlighter reflects the correct semantics of `@let` bindings.

fixes https://github.com/angular/angular/issues/61643

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/contributing-docs/commit-message-guidelines.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.dev application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
image
 
 

## What is the new behavior?
image

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: vscode-ng-language-service/syntaxes/src/template.ts [hunk 1]
```diff
@@ -10,7 +10,8 @@ import {GrammarDefinition} from './types';
 
 export const Template: GrammarDefinition = {
   scopeName: 'template.ng',
-  injectionSelector: 'L:text.html -comment -control.block.ng',
+  injectionSelector:
+    'L:text.html -comment -control.block.ng -string.quoted.single.ts -string.quoted.double.ts -string.template.ts',
```
Comment (atscott) [inline vscode-ng-language-service/syntaxes/src/template.ts]: I think this is the wrong exclusion and should instead be `-meta.definition.variable.ng`

Comment (SkyZeroZx) [reply vscode-ng-language-service/syntaxes/src/template.ts]: Updated

**Review by atscott — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository. The changes were merged into the following branches:

- main: 9f5744a92dda4219e93bf7e6236d32a93bc167e6
- 21.0.x: e0694df3eccae3d31a4ea537dffe1db1368ef34a
