### PR TITLE
fix(compiler-cli): don't unnecessarily throw on StaticSymbols

### LINKED ISSUE #11276: Importing RouterTestingModule in spec files causes AOT/ngc compiler to fail
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Current behavior**
If I have RouterTestingModule imported in any of my spec files, I will get the following error:
>Error: parameters received {"filePath":"/Users/qdouble/Sites/MAIN_PROJECT/node_modules/@angular/common/src/location/location.d.ts","name":"Location"} which is not a StaticSymbol

**Expected/desired behavior**
First of all, there should be an option to make the ngc compiler ignore spec files (other than having to go back and forward in changing your tsconfig setting to ignore spec files). I'll also assume that if it's evaluating spec files, it would make the compilation slower.

Beyond fixing the RouterTestingModule bug, I think ngc should be a setting to make ngc/aot ignore spec/e2e files.

* **Angular version:** 2.0.0-builds --- latest

### PR DESCRIPTION
**Pull request by steve8708**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
#11276 #12097

ngc throws an error when StaticSymbol interface compatible objects are passed to `StaticReflector.parameters` or `StaticReflector.hasLifecycleHook`

**What is the new behavior?**

If the object properly matches the `StaticSymbol` interface, do not throw an error and allow the object to be processed

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

Closes #11276 #12097

### CODE REVIEW

**Comment by steve8708** [comment]
(fyi this is a blocker for [AOT support in angular/universal](https://github.com/angular/universal/pull/578))

File: modules/@angular/compiler-cli/src/static_reflector.ts [hunk 1]
```diff
@@ -120,7 +121,7 @@ export class StaticReflector implements ReflectorReader {
   }
 
   public parameters(type: StaticSymbol): any[] {
-    if (!(type instanceof StaticSymbol)) {
+    if (!isStaticSymbol(type)) {
```
Comment (tbosch) [inline modules/@angular/compiler-cli/src/static_reflector.ts]: Could you add a test for this new behavior? In https://github.com/angular/angular/blob/master/modules/@angular/compiler-cli/test/static_reflector_spec.ts...

File: modules/@angular/compiler/src/private_export.ts [hunk 2]
```diff
@@ -6,6 +6,7 @@
  * found in the LICENSE file at https://angular.io/license
  */
 
+import * as compile_metdata from './compile_metadata';
```
Comment (tbosch) [inline modules/@angular/compiler/src/private_export.ts]: Could you then also export the `StaticSymbol` here as well and drop the declaration in `static_reflector`? You will probably need to add `members` to the one in `@angular/compiler`...

File: modules/@angular/compiler-cli/src/static_reflector.ts (hunk 1 above)
Comment (chuckjaz) [inline modules/@angular/compiler-cli/src/static_reflector.ts]: This change is wrong. The reason that this code checks using `instanceof` is because the static reflector assumes that all the static symbols it receives in its API are where produced by the static reflector. This is because it uses object identity to cache information and determine type identity. The bug is not that we are checking for `instanceof` instead of using `isStaticSymbol`, rather, it is that someone is passing static symbol that wasn't produced by the static reflector.

Comment (steve8708) [inline modules/@angular/compiler-cli/src/static_reflector.ts]: got it, thanks for the explanation @chuckjaz 

I'll dig deeper and find the source of static symbols not created by the static reflector and update this PR accordingly

Comment (steve8708) [inline modules/@angular/compiler-cli/src/static_reflector.ts]: So from digging around deeper I see what is going on. 

The objects were originally static symbols created by the StaticSymbol constructor, but then were cloned in the [mapStringMap function](https://github.com/angular/angular/blob/master/modules/@angular/compiler-cli/src/static_reflector.ts#L609) (which is called by [simplify](https://github.com/angular/angular/blob/master/modules/@angular/compiler-cli/src/static_reflector.ts#L346) in [parameters](https://github.com/angular/angular/blob/master/modules/@angular/compiler-cli/src/static_reflector.ts#L122) in the static reflector) which is where the `instanceof` check breaks, as well as proper ability to cache by reference.

Looking deeper into why this happens to only some providers in some situations and to why the simplify functions that are being used exist in the first place and if the cloning can be circumvented or if it is a deeper issue that StaticSymbols are passed to the simplify function in the first place

Comment (chuckjaz) [inline modules/@angular/compiler-cli/src/static_reflector.ts]: Thanks for looking into this! `StaticSymbol` should be a special case in the evaluator. Try adding the lines:
```ts
        if (expression instanceof StaticSymbol) {
          return expression;
        }
```
just after the test for `Array` in `simplify()`. This will prevent the static reflector from trying to clone a `StaticSymbol`, treating it like a primitive instead of a hash map.

Comment (chuckjaz) [inline modules/@angular/compiler-cli/src/static_reflector.ts]: If you find how a `StaticSymbol` got in a value passed to `simplify()` I would be curious. That shouldn't happen but if it does we shouldn't damage it.

File: modules/@angular/compiler-cli/src/static_reflector.ts [hunk 3]
```diff
@@ -347,6 +347,9 @@ export class StaticReflector implements ReflectorReader {
         if (isPrimitive(expression)) {
           return expression;
         }
+        if (expression instanceof StaticSymbol) {
+          return expression;
+        }
```
Comment (steve8708) [inline modules/@angular/compiler-cli/src/static_reflector.ts]: Found the issue. 

When recursively processing/simplifying annotation metadata StaticSymbols need to be kept in tact rather than treated as plain string maps and cloned

This was happening to us in universal for any private import we made from `platform-browser` using the format we see from the this repo must be used to properly import private exports (i.e. using the explicit `typeof x` type annotations) which we do in universal [here](https://github.com/angular/universal/blob/3d7c56ddad9ac003543133dac60ce5eab373fdb8/modules/platform-node/__private_imports__.ts#L10). 

I'm guessing this is just a byproduct of the parsing being a bit different when using that special import/export format required for private exports.

I've updated this PR accordingly to check for StaticSymbol before further processing in the `simplifyInContext` method which I've verified with this fix universal now builds and runs as expected with AOT

Happy to make any further updates or refactors desired as well, just let me know, and thanks for taking a look at this @tbosch and @chuckjaz!

File: modules/@angular/compiler-cli/src/static_reflector.ts (hunk 1 above)
Comment (steve8708) [inline modules/@angular/compiler-cli/src/static_reflector.ts]: @chuckjaz agreed, and thanks!

My solution was identical to yours but I added the check below the check for primitives, if it's important that it be below the check for `Array` just let me know and I'll happily move it

So far I am stumped as well how only in rare cases static symbols are passed to simplify anyway (it's within some deep recursion in some edge case situations it seems) but I'll definitely let you know if I figure it out!

Also, just added a test for this new check as well 👍

File: modules/@angular/compiler-cli/src/static_reflector.ts (hunk 3 above)
Comment (chuckjaz) [inline modules/@angular/compiler-cli/src/static_reflector.ts]: Can you add a test to `static_reflector_spec.ts` that verifies that `simplify()` will not clone a `StaticSymbol`? Something like: ```ts
```
  it('should not clone a static symbol', () => {
    const symbol = new StaticSymbol('/tmp/src/some_file.ts', 'SomeSymbol');
    expect(simplify(symbol, symbol)).toBe(symbol);
  });
```

Comment (steve8708) [inline modules/@angular/compiler-cli/src/static_reflector.ts]: @chuckjaz just did in a separate commit 👍

Comment (steve8708) [inline modules/@angular/compiler-cli/src/static_reflector.ts]: if you want me to squash it with the first, just let me know

File: modules/@angular/compiler-cli/src/static_reflector.ts (hunk 1 above)
Comment (chuckjaz) [inline modules/@angular/compiler-cli/src/static_reflector.ts]: We are cross talking! No need for it being after `Array` really. It is slightly faster there (in that `StaticSymbol`s are less common than `Array`s but not really noticeably so. Only move it if you feel so inclined.

File: modules/@angular/compiler-cli/src/static_reflector.ts (hunk 3 above)
Comment (chuckjaz) [inline modules/@angular/compiler-cli/src/static_reflector.ts]: Up to you. Tobias will probably squash and merge anyway.

File: modules/@angular/compiler-cli/src/static_reflector.ts (hunk 1 above)
Comment (steve8708) [inline modules/@angular/compiler-cli/src/static_reflector.ts]: @chuckjaz makes perfect sense, I went a head and pushed one small update with that extra optimization 👍

File: modules/@angular/compiler-cli/src/static_reflector.ts [hunk 4]
```diff
@@ -371,6 +368,9 @@ export class StaticReflector implements ReflectorReader {
           }
           return result;
         }
+        if (expression instanceof StaticSymbol) {
+          return expression;
+        }
         if (expression) {
```
Comment (chuckjaz) [inline modules/@angular/compiler-cli/src/static_reflector.ts]: No need for this to be a separate commit. Just squash them.

Comment (steve8708) [inline modules/@angular/compiler-cli/src/static_reflector.ts]: @chuckjaz squashed 👍

**Comment by alexeagle** [comment]
Awesome, thanks for digging so deep, @steve8708 !

**Comment by steve8708** [comment]
no problem, thank you for the tips @alexeagle!

**Comment by snstarosciak** [comment]
Hey everyone, I'm a bit confused here :/ I stumbled upon this thread from [this one](https://github.com/angular/angular/issues/12097) as I was looking for a solution to fix my Ionic 2 compiler when I run `ionic build ios`. I don't see the file `modules/@angular/compiler-cli/src/static_reflector.ts` The closest thing would be modules/@angular/compiler-cli/src/static_reflector.d.ts and it's only 80 lines long. Would anyone be able to shed some light on this for me? :)

**Comment by chuckjaz** [comment]
I am not sure what your question is but the lines https://github.com/angular/angular/blob/master/modules/%40angular/compiler-cli/src/static_reflector.ts#L369-L371 were added to resolve this issue.

**Comment by snstarosciak** [comment]
@chuckjaz Thanks for quick response. Sorry for the confusion. I don't have that file in my respective node_modules directory. I was able to solve the problem by not using the DomSanitizer as a provider and just imported it directly into my component. Problem solved :)
