### PR TITLE
fix(core): fix property decorators

### LINKED ISSUE #12224: Firefox issue with property decorators
**I'm submitting a ...**  
```
[ x ] bug report
```

**Current behavior**
When name of property is `watch` and this property marked with property decorator (Input or Output) in Firefox I see issue like `unshift is not a function`. I found that this line of code `meta[name] = meta[name] || [];` returns watch() function instead of property metadata. 

**Expected behavior**
From my point of view `watch` is not a reserved name for variables or properties, so we should be able to create properties with name `watch`.

**Minimal reproduction of the problem with instructions**
This is only Firefox issue, in Chrome it works fine.
Plunker to reproduce: https://plnkr.co/edit/pL19LMYTJ27Th2zWUPLH

**Please tell us about your environment:** Windows 10, Firefox 49.0.1

* **Angular version:** 2.0.2

* **Browser:** Firefox 49.0.1
 
* **Language:** TypeScript 2.0.2

### PR DESCRIPTION
**Pull request by vicb**
fixes #12224 

"funny" bug where firefox has `Object.prototype.watch` hence `meta['watch] = function() {...}`

### CODE REVIEW

File: modules/@angular/core/test/util/decorators_spec.ts [hunk 1]
```diff
@@ -133,3 +155,10 @@ export function main() {
     });
   });
 }
+
+const Prop = makePropDecorator('Prop', [['value', undefined]]);
+
+class TestClass {
+  @Prop('firefox!')
+  watch: any;
+}
```
Comment (chuckjaz) [inline modules/@angular/core/test/util/decorators_spec.ts]: Consider moving this into the `define` as we discussed.

**Comment by chuckjaz** [comment]
LGTM with the minor change requested.
