### PR TITLE
docs(docs-infra): fix missing syntax highlighting in router api

### LINKED ISSUE #65565: Missing Syntax Highlighting in Router API Documentation
### Describe the problem that you experienced

Currently, the following Angular Router APIs:

- https://angular.dev/api/router/NavigationBehaviorOptions  
- https://angular.dev/api/router/NavigationExtras  
- https://angular.dev/api/router/Router  
- https://angular.dev/api/router/UrlCreationOptions  

include examples that are not formatted with proper TypeScript syntax highlighting.

To improve readability and ensure consistency across the documentation, the JSDoc for each of these APIs should be updated so that all code samples use correct TypeScript syntaxis.

Image

Proposed Solution

Add the `ts` language identifier (```ts) to all code fences that are missing TypeScript syntax highlighting , following the same approach used in examples such as [`routerConfig`](https://github.com/angular/angular/blob/main/packages/router/src/router.ts#L374).

### PR DESCRIPTION
**Pull request by alessiopelliccione**
closes #65565

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/contributing-docs/commit-message-guidelines.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.dev application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Syntax Highlighting is missing in Router API Documentation

Issue Number: #65565

## What is the new behavior?
Fixed the issue

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: packages/router/src/models.ts [hunk 1]
```diff
@@ -1480,7 +1480,7 @@ export interface NavigationBehaviorOptions {
   /**
    * When true, navigates without pushing a new state into history.
    *
-   * ```
+   * ```angular-ts
```
Comment (SkyZeroZx) [inline packages/router/src/models.ts]: I think using the `ts` tag is enough, since `angular-ts` is more for template-based examples, like those inside a `@Component` template.

File: packages/router/src/navigation_transition.ts [hunk 2]
```diff
@@ -119,7 +119,7 @@ export interface UrlCreationOptions {
    * The following `go()` function navigates to the `list` route by
    * interpreting the destination URI as relative to the activated `child`  route
    *
-   * ```ts
+   * ```angular-ts
```
Comment (SkyZeroZx) [inline packages/router/src/navigation_transition.ts]: Something similar here; since we don't have an inline template, it's fine as it is initially.

File: packages/router/src/router.ts
Comment (JeanMeche) [inline packages/router/src/router.ts:455]: We need to extract that note from the code block, else it's highlighted.

File: packages/router/src/models.ts (hunk 1 above)
Comment (alessiopelliccione) [reply packages/router/src/models.ts]: True, thanks for that!

**Review by JeanMeche — APPROVED** [review]

**Comment by JeanMeche** [comment]
caretaker note: No need to presubmit, this is a doc only change

**Comment by kirjs** [comment]
This PR was merged into the repository. The changes were merged into the following branches:

- main: 7d20f2071caa5b2d74fde678459f200bb1a47233
- 21.0.x: 9d6b86958a27f1c61b1846d3fdb7385ef9987228
