### PR TITLE
fix(language-service): detect when there isn't a tsconfig.json

### LINKED ISSUE #15874: language service: 100% CPU consumption when no tsconfig.json found
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**

When requesting a information about a file with no `tsconfig.json` file will cause 100% CPU usage.

**Expected behavior**

It correctly detect no `tsconfig.json` file.

**Minimal reproduction of the problem with instructions**

Open an `.html` file in a directory that has no `tsconfig.json` file in the directory or a parent directory.

### PR DESCRIPTION
**Pull request by chuckjaz**
Fixes #15874

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
```

**What is the current behavior?** (You can also link to an open issue here)

The language service is created in a directory that has no `tsconfig.json` file in itself or one of its parents it would infinite loop searching for it.

#15874
https://github.com/angular/vscode-ng-language-service/issues/69

**What is the new behavior?**

It now terminates the loop looking for a tsconfig.json file when it is not found in a parent directory.

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

### CODE REVIEW

File: packages/language-service/test/typescript_host_spec.ts [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+
+  it('should be able to create a typescript host',
+     () => { expect(() => new TypeScriptServiceHost(host, service)).not.toThrow(); });
+
+  beforeEach(() => { ngHost = new TypeScriptServiceHost(host, service); });
+
+  it('should be able to analyze modules',
+     () => { expect(ngHost.getAnalyzedModules()).toBeDefined(); });
+
+  fit('should be able to analyze modules in without a tsconfig.json file', () => {
```
Comment (vicb) [inline packages/language-service/test/typescript_host_spec.ts]: it

File: packages/language-service/src/typescript_host.ts [hunk 2]
```diff
@@ -1097,7 +1097,9 @@ function findTsConfig(fileName: string): string {
   while (fs.existsSync(dir)) {
     const candidate = path.join(dir, 'tsconfig.json');
     if (fs.existsSync(candidate)) return candidate;
-    dir = path.dirname(dir);
+    const newdir = path.dirname(dir);
```
Comment (vicb) [inline packages/language-service/src/typescript_host.ts]: parentDir ?

**Review by vicb — APPROVED** [review]
need to change to fit
