### PR TITLE
fix(compiler): ignore @import in multi-line css

### LINKED ISSUE #18038: @import in multi-line css comment is wrongly interpreted
## I'm submitting a ...
[x] Bug report

## Current behavior
`@import` statements in multi-line comments in CSS are incorrectly interpreted, generating a network request.

## Expected behavior
Comment, and the `@import` statement inside it, should be ignored.

## Minimal reproduction of the problem with instructions
<pre><code>
/* 
This import statement should be ignored: @import "foo.scss"; 
*/
</code></pre>

## What is the motivation / use case for changing the behavior?
Obviously, the import statement inside a comment should be ignored.

## Please tell us about your environment

<pre><code>
Angular version: 4.2.5

Browser:
- [x] Chrome (desktop) version 59

### PR DESCRIPTION
**Pull request by marclaval**
Fixes #18038

### CODE REVIEW

File: packages/compiler/src/style_url_resolver.ts [hunk 1]
```diff
@@ -43,5 +43,5 @@ export function extractStyleUrls(
 }
 
 const CSS_IMPORT_REGEXP = /@import\s+(?:url\()?\s*(?:(?:['"]([^'"]*))|([^;\)\s]*))[^;]*;?/g;
-const CSS_COMMENT_REGEXP = /\/\*.+?\*\//g;
+const CSS_COMMENT_REGEXP = /\/\*[^]+?\*\//g;
```
Comment (vicb) [inline packages/compiler/src/style_url_resolver.ts]: is `[^]` the same as `[\s\S]` (we use the later as several places IIRC)

Comment (mlaval) [inline packages/compiler/src/style_url_resolver.ts]: Regexp updated

**Review by vicb — APPROVED** [review]

**Comment by vicb** [comment]
@mlaval Thanks - restarted Travis because AIO was failing (most probably a flake)
