### PR TITLE
fix(aio): restore visible sidenav keyboard focus

### LINKED ISSUE #17665: aio: highlight when tabbing on the navbar doesn't work
If you tab through the navbar it only highlights those nodes with children but not the ones without it.

### PR DESCRIPTION
**Pull request by wardbell**
closes #17665
Restores keyboard focus that was removed by commit b8b91d3.

To prevent keyboard focus on hidden child nodes,
also collapses inner expanded nodes when parent node is collapsed.
The implicit parent node of top nodes is always expanded.

Also, raise the right-TOC by 20px (96px->76px) because was too far down.

## PR Checklist
Does please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

### CODE REVIEW

File: aio/src/app/layout/nav-item/nav-item.component.ts [hunk 1]
```diff
@@ -22,9 +23,10 @@ export class NavItemComponent implements OnChanges {
     if (this.selectedNodes) {
       const ix = this.selectedNodes.indexOf(this.node);
       this.isSelected = ix !== -1; // this node is the selected node or its ancestor
-      this.isExpanded = this.isSelected || // expand if selected or ...
+      this.isExpanded = this.isParentExpanded &&
```
Comment (gkalpak) [inline aio/src/app/layout/nav-item/nav-item.component.ts]: I am not sure how I feel about this, but I think I lean towards liking it :grin:

**Review by gkalpak — APPROVED** [review]
A couple of minor suggestions/questions.
LGTM otherwise.

**Comment by petebacondarwin** [comment]
Why are we averse to just using an `ngIf` or perhaps changing the exposed `nodeChildren` array when the item is not expanded? Doing so would avoid the hack of tracking whether the parent item is expanded or not.

File: aio/src/app/layout/nav-item/nav-item.component.ts (hunk 1 above)
Comment (petebacondarwin) [inline aio/src/app/layout/nav-item/nav-item.component.ts]: I am not sure I like it

**Review by petebacondarwin — CHANGES_REQUESTED** [review]
I agree with @gkalpak's comments and suggest that they are acted upon.

File: aio/src/styles/2-modules/_toc.scss [hunk 2]
```diff
@@ -1,7 +1,7 @@
 .toc-container {
   width: 18%;
   position: fixed;
-  top: 96px;
+  top: 76px;
   right: 0;
   bottom: 32px;
```
Comment (wardbell) [inline aio/src/styles/2-modules/_toc.scss]: I agree. Not sure where all the pieces are. My starting question ... do you agree that TOC needs to start higher on the page?

File: aio/src/styles/1-layouts/_sidenav.scss [hunk 3]
```diff
@@ -22,7 +22,7 @@ aio-nav-menu {
   }
 
   aio-nav-item div a {
-    padding-left: 16px;
+    padding-left: 2px;
```
Comment (wardbell) [inline aio/src/styles/1-layouts/_sidenav.scss]: How much more?

Btw ... have you seen how tight the outline is for the right TOC items? I think it's zero px. Do you feel the same way about that?

**Comment by Foxandxss** [comment]
I like that it is more obvious now, but what is with that black to blue animation? :P

**Comment by wardbell** [comment]
@petebacondarwin I considered `*ngIf`. It doesn't make the code easier and the expand animation goes away! We aren't using Angular Animations (because of size?). So I stuck with this approach.

File: aio/src/styles/1-layouts/_sidenav.scss [hunk 4]
```diff
@@ -67,27 +67,34 @@ md-sidenav-container div.mat-sidenav-content {
...
   &:hover {
-    text-shadow: 0 0 5px #ffffff;
+    background-color: $lightgray;
     color: $blue;
+    text-shadow: 0 0 5px #ffffff;
+  }
+
+  &:focus {
+    outline: $accentblue auto 2px;
+    outline-color: $accentblue;
```
Comment (wardbell) [inline aio/src/styles/1-layouts/_sidenav.scss]: I stole that CSS from elsewhere. Damned if I know.  Will fix.

File: aio/src/styles/2-modules/_toc.scss (hunk 2 above)
Comment (gkalpak) [inline aio/src/styles/2-modules/_toc.scss]: I have also thought that it started lower than necessary, but I assumed it was a concious design decision :grin: I don't mind either way.

File: aio/src/styles/1-layouts/_sidenav.scss (hunk 3 above)
Comment (gkalpak) [inline aio/src/styles/1-layouts/_sidenav.scss]: Yeah. ToC could use some space too, but at least it is symmetric on the two sides. It is also less obvious in ToC, because it is not obvious on hover, only when focused. With the left SideNav, hovering over the items makes their background gray which makes it obvious that the left and right padding are quite different:

test

**Comment by IgorMinar** [comment]
@wardbell TOC alignment adjustment lgtm

File: aio/src/styles/2-modules/_toc.scss (hunk 2 above)
Comment (wardbell) [inline aio/src/styles/2-modules/_toc.scss]: I changed to `bottom: 12px;` and reduced the "fudge margin" in the [`maxTocHeight` calculation][1] as you suggested.


[1]: https://github.com/IdeaBlade/angular/blob/ea581b8f31b26ef622dbc9993afe9226d3930273/aio/src/app/app.component.ts#L280

**Comment by wardbell** [comment]
@Foxandxss @sjtrimble removed the gray->blue transition as you requested.

**Comment by petebacondarwin** [comment]
Cherry picked via 7080fccb38ba41b11b0deb25e1b8d15fbc9c856c
