### PR TITLE
fix(forms): Untrack `setValue` in reactive forms

### LINKED ISSUE #67073: `formControl.setValue` inside a reactive context causes tracking of all signals read by value/validity change subscribers
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

After upgrading from Angular 19 to Angular 21
---
A component that uses `AfterRenderEffect` started behaving unexpectedly. When the user clicks a button in a toggle group, the selected value should be reflected correctly, but instead the view is reset to the main title after a render cycle. This appears to be triggered when a form control’s`setValue('main')` is called, which causes the render to run in a way that overrides the user’s selection.
If I comment out the `setValue('main')` call, the component behaves as expected and the selection is preserved, with no unexpected re-renders. 
well i susbect that **(iam not sure)** `setValue()` is now interacting differently with change detection and `AfterRenderEffect` between Angular 19 and Angular 21. I am trying to understand whether this is an intentional change in how `setValue` emits events or triggers rendering, or a regression in how it collaborates with render effects.

Link v19, where it was working [link](https://stackblitz.com/edit/stackblitz-starters-tptspfzl?file=src%2Fcustom-component.ts,src%2Fmain.ts)

link v21, where it was broke [link](https://stackblitz.com/edit/stackblitz-starters-tkg2lk9c?file=package-lock.json,src%2Fmain.ts)

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-tkg2lk9c?file=package-lock.json,src%2Fmain.ts

### Please provide the exception or error you saw

```true

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI       : 21.0.2
Angular           : 21.0.3
Node.js           : 20.19.1
Package Manager   : npm 10.8.2
Operating System  : linux x64

┌───────────────────────────┬───────────────────┬───────────────────┐
│ Package                   │ Installed Version │ Requested Version │
├───────────────────────────┼───────────────────┼───────────────────┤
│ @angular/animations       │ 21.0.3            │ ^21.0.3           │
│ @angular/build            │ 21.0.2            │ ^21.0.2           │
│ @angular/cdk              │ 21.1.4            │ ^21.1.4           │
│ @angular/cli              │ 21.0.2            │ ^21.0.2           │
│ @angular/common           │ 21.0.3            │ ^21.0.3           │
│ @angular/compiler         │ 21.0.3            │ ^21.0.3           │
│ @angular/compiler-cli     │ 21.0.3            │ ^21.0.3           │
│ @angular/core             │ 21.0.3            │ ^21.0.3           │
│ @angular/forms            │ 21.0.3            │ ^21.0.3           │
│ @angular/material         │ 21.1.4            │ ^21.1.4           │
│ @angular/platform-browser │ 21.0.3            │ ^21.0.3           │
│ @angular/router           │ 21.0.3            │ ^21.0.3           │
│ rxjs                      │ 7.8.2             │ ^7.8.1            │
│ typescript                │ 5.9.3             │ ^5.9.3            │
└───────────────────────────┴───────────────────┴───────────────────┘
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by JeanMeche**
Reasonably, writing to an `AbstractControl` shouldn't register signal reads.

fixes #67073

### CODE REVIEW

File: packages/forms/src/model/form_array.ts [hunk 1]
```diff
@@ -321,12 +321,14 @@ export class FormArray<TControl extends AbstractControl<any> = any> extends Abst
       emitEvent?: boolean;
     } = {},
   ): void {
```
Comment (SkyZeroZx) [inline packages/forms/src/model/form_array.ts:323]: It seems it would also be reasonable to do it with `patchValue` and maybe `reset` ? 
 I just tested it and it behaves the same way.

Comment (JeanMeche) [reply packages/forms/src/model/form_array.ts:323]: Both rely on calling `setValue` added tests to show it.

**Review by alxhub — APPROVED** [review]
Let's see how breaking this is on TGP, but my instinct is that this can land as a fix in patch - it's genuinely a bug.

**Comment by JeanMeche** [comment]
TGP returned a single breakage.

**Comment by alxhub** [comment]
Yep, then let's land this in patch :)

**Review by alxhub — APPROVED** [review]

**Comment by JeanMeche** [comment]
(doesn't merge cleanly in patch, will create a patch PR seperately when this is merged)

**Comment by JeanMeche** [comment]
[TGP is green](https://fusion2.corp.google.com/presubmit/870435534/OCL:870435534:BASE:872388860:1771514688215:592300e6)

**Comment by thePunderWoman** [comment]
This PR was merged into the repository. The changes were merged into the following branches:

- main: 2061fd8253882a46336aae8d73a79a1b176449e0
