### PR TITLE
fix(zone.js): allow draining microtasks in `Promise.then` (through flag)

### LINKED ISSUE #44446: zone.js drains microtasks too early in synchronous event call
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Please see the reproduction. It seems zone.js assumes EventTarget's event call is always a standalone task, which may not be true.

```js
const invoke = (fn) => {
  document.body.addEventListener('click', fn);
  document.body.click();
  document.body.removeEventListener('click', fn);
};

invoke(() => {
  Promise.resolve().then(() => console.log(2));
});
console.log(1);
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/typescript-88btqj?file=index.ts

### Please provide the exception or error you saw

```true
Native Chrome/Safari/Firefox outputs `1 2`, while with zone.js outputs `2 1`.
```

### Please provide the environment you discovered this bug in (run `ng version`)

_No response_

### Anything else?

I noticed this during debugging https://github.com/angular/angular/issues/41506#issuecomment-991765487 , maybe related.

### LINKED ISSUE #51328: zone.js promises returning Unhandled Promise Rejection error even with catch blocks
### Which @angular/* package(s) are the source of the bug?

zone.js

### Is this a regression?

No

### Description

I've hit the same issue as described in #31680 and both this and that ticket have same root cause detailed bellow. Since I cannot reopened old issue I've created a new one.

### Repro
Following simplified code will emit unhandled promise rejection even tho there is a catch handler. This happens only when zone.js is loaded. Without zone.js, all majors browsers (Chrome, Safari, Firefox) don't report anything in this case.

```typescript
onunhandledrejection = (e) => { console.log("Unhandled promise rejection", e) }

(async function() {
    return Promise.reject(1);
})().catch(e => {});
// OR
(async function() {
    await Promise.reject(2);
})().catch(e => {});
```
Using native Promise.reject will not emit unhandled rejection.

### Root cause:
zone.js schedules the reporting of unhandled rejections on the microtask queue as soon as the promise is rejected. In the case of `Promise.reject` it schedules as part of the reject call.
JS async function calls `.then` on the returned inner promise (Promise.reject) on the next microtask tick. This is defined in the Ecmascript spec.
zone.js will end up running the code to report unhandled rejections before JS async function has a chance to call `then` and as such zone.js ends emiting unhandled rejection.

All major browsers check if unhandled rejections exists at the end of the microtask checkpoint (i.e. after draining the queue) and if needed will schedule on normal queue a task (or what you call a macro task) to process&report unhandled rejections. This allows sufficient time for the async infrastructure to hook to the returned promise. In Chrome and Safari it even allows sufficient time to add catch handler in a callback run by setTimeout of delay 0.

Chrome:
https://github.com/chromium/chromium/blob/89e00b6b959f5efb4bd7eec468973badb3093a3b/third_party/blink/renderer/platform/scheduler/common/event_loop.cc#L108
https://github.com/chromium/chromium/blob/89e00b6b959f5efb4bd7eec468973badb3093a3b/third_party/blink/renderer/bindings/core/v8/rejected_promises.cc#L248-L252
Firefox:
https://github.com/mozilla/gecko-dev/blob/77dd6aa3810610949a5ff925e24de2f8c11377fd/xpcom/base/CycleCollectedJSContext.cpp#L473-L480
Safari:
https://github.com/WebKit/WebKit/blob/75a3eb3a5fe3dce1867d880faf785137963b234a/Source/WebCore/dom/Microtasks.cpp#L107
https://github.com/WebKit/WebKit/blob/75a3eb3a5fe3dce1867d880faf785137963b234a/Source/WebCore/dom/RejectedPromiseTracker.cpp#L142-L144

### Please provide a link to a minimal reproduction of the bug

_No response_

### Please provide the exception or error you saw

```true
Unhandled Promise rejection: 1 ; Zone: <root> ; Task: null ; Value: 1 undefined
Unhandled Promise rejection: 2 ; Zone: <root> ; Task: null ; Value: 2 undefined
Unhandled promise rejection PromiseRejectionEvent {isTrusted: true,  reason: 1, type: 'unhandledrejection' ...}
Uncaught (in promise) 1
Unhandled promise rejection PromiseRejectionEvent {isTrusted: true,  reason: 2, type: 'unhandledrejection' ...}
Uncaught (in promise) 2
```

### Please provide the environment you discovered this bug in (run `ng version`)

_No response_

### Anything else?

_No response_

### LINKED ISSUE #55590: PromiseRejectionEvent not fired
### Which @angular/* package(s) are the source of the bug?

zone.js

### Is this a regression?

No

### Description

The PromiseRejectionEvent is not triggered when zone.js is included on the webpage. The issue stems from zone.js's inability to construct a PromiseRejectionEvent because options parameter is undefined - `{ promise: undefined, reason: undefined }`

Event is not fired and silently ignored here: https://github.com/angular/angular/blob/main/packages/zone.js/lib/common/promise.ts#L82
Fails to construct PromiseRejection error here: https://github.com/angular/angular/blob/main/packages/zone.js/lib/browser/browser.ts#L316

image

Here is a minimal example to reproduce the issue. Note that if you remove the zone.js script, the event fires as expected.
```html
<!doctype html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<title>Title</title>
		<script src="https://cdn.jsdelivr.net/npm/zone.js@0.14.4/bundles/zone.umd.min.js"></script>
	</head>
	<body>
		<script>
			window.addEventListener('unhandledrejection', (event) =>
				console.log('unhandledrejection', event, event.promise, event.reason),
			)

			const scriptEl = document.createElement('script')
			scriptEl.innerHTML = "Promise.reject('Error happened :(')"
			document.body.append(scriptEl)
		</script>
	</body>
</html>

```

### Please provide a link to a minimal reproduction of the bug

_No response_

### Please provide the exception or error you saw

_No response_

### Please provide the environment you discovered this bug in (run `ng version`)

```true
zone.js: latest
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by arturovt**
These changes are essentially the same as those introduced in angular#45273, but they include backward compatibility for applications that explicitly rely on the order in which microtasks are drained.

This is critically important for our code and other third-party code, which is beyond our control, to work properly. If a microtask is scheduled within an event listener to be executed "later", it should indeed be executed later and not synchronously, as this would break the expected flow of code execution.

The simple code that reproduces the behavior that exists now:

```ts
Zone.current.fork({name: 'child'}).run(() => {
  const div = document.createElement('div');
  div.style.height = '200px';
  div.style.width = '200px';
  div.style.backgroundColor = 'red';
  document.body.appendChild(div);

  function listener() {
    Promise.resolve().then(() => {
      div.style.height = '400px';
    });
  }

  div.addEventListener('fakeEvent', listener);
  div.dispatchEvent(new Event('fakeEvent'));
  console.log(div.getBoundingClientRect().height); // 400
});
```

The code above logs 400 as the height, but it should actually log 200 because the height is updated in a microtask within the event listener.

When using Angular with microfrontend applications, especially when other apps might be using React, zone.js can disrupt the classical order of operations. For example, when using a `react-component/trigger`, it schedules a microtask within an event listener using `Promise.resolve().then(...)` to determine whether the event needs to be re-dispatched. The event is re-dispatched when the layout has changed, which is why a microtask is used.

With this change, we introduce a global configuration flag, `__zone_symbol__enable_native_microtask_draining`, to allow consumers to enable microtask draining within a browser microtask.

This flag is necessary to prevent any breaking changes resulting from this modification. The previous attempt to address this issue caused a significant number of failures in g3. Therefore, we are hiding that fix behind the configuration flag.

Closes https://github.com/angular/angular/issues/44446
Closes https://github.com/angular/angular/issues/55590
Closes https://github.com/angular/angular/issues/51328

### CODE REVIEW

**Comment by arturovt** [comment]
Note for reviewers: do not close this request, as discussed with @atscott these changes have the green light.

File: packages/zone.js/lib/zone-impl.ts [hunk 1]
```diff
@@ -1503,54 +1500,75 @@ export function initZone(): ZoneType {
   const symbolSetTimeout = __symbol__('setTimeout');
   const symbolPromise = __symbol__('Promise');
   const symbolThen = __symbol__('then');
+  // To prevent any breaking changes resulting from this change, given that
+  // it was already causing a significant number of failures in g3, we have hidden
+  // that behavior behind a global configuration flag. Consumers can enable this
+  // flag explicitly if they want the microtask queue to be drained as defined
+  // in the specification.
```
Comment (atscott) [inline packages/zone.js/lib/zone-impl.ts:1507]: nit: it wasn't a _significant_ number (IIRC, like 10) but more that there were a few and it's really hard to tell if something just isn't covered by tests and is going to cause a production outage.

File: packages/zone.js/lib/zone-impl.ts [hunk 2]
```diff
@@ -1503,54 +1500,75 @@ export function initZone(): ZoneType {
...
+        } catch (error) {
+          _api.onUnhandledError(error as Error);
         }
       }
+    }
+
+    // The order matters!
+    if (global[enableNativeMicrotaskDraining]) {
+      _isDrainingMicrotaskQueue = false;
+      _api.microtaskDrainDone();
```
Comment (atscott) [inline packages/zone.js/lib/zone-impl.ts:1570]: I don't specifically recall why order matters and it does look odd that it's different from the other case. do you remember why and can you add more details?

Comment (arturovt) [reply packages/zone.js/lib/zone-impl.ts:1570]: I don't recall too, it didn't have any issues tbh. I think it should always be the following:
```ts
_isDrainingMicrotaskQueue = false;
_api.microtaskDrainDone();
```

Regardless whether `microtaskDrainDone` would throw.

**Comment by arturovt** [comment]
@atscott should `__zone_symbol__enable_native_microtask_draining` be documented as the recommended configuration for existing apps using zone.js?

The flag eliminates a whole class of subtle bugs — flaky ordering in router navigation, unexpected Promise.then sequencing in event handlers, etc.

**Comment by arturovt** [comment]
@atscott I also added more regression tests for other issues being closed with this fix.

**Comment by thePunderWoman** [comment]
Woah, looks like you've opened a lot of issues/PRs recently. While we appreciate contributions from the community, triaging and reviewing a large influx of content in a short time period takes time away from other ongoing projects. As a result, we're closing these issues/PRs to maintain the team's focus.

Note that this is not necessarily a rejection of the goals or direction of any of these contributions in particular, so much as a reflection of the team's current capacity and priorities.

You are welcome to open a smaller subset of issues/PRs in accordance with [our policy](/contributing-docs/spam.md) focused on the most important and impactful contributions and we will do our best to prioritize a response as soon as possible.

**Comment by atscott** [comment]
> should __zone_symbol__enable_native_microtask_draining be documented as the recommended configuration for existing apps using zone.js?

I wouldn't make a hard push for it. While I agree that it should be the default, it's still likely not worth doing anything about for existing apps, especially given that very few apps are actually at risk of hitting this issue.

**Review by atscott — APPROVED** [review]

**Comment by atscott** [comment]
TGP=https://fusion2.corp.google.com/presubmit/899035739/OCL:899035739:BASE:899004210:1776134351755:e8c2d3dd/targets

**Comment by kirjs** [comment]
This PR was merged into the repository. The changes were merged into the following branches:

- main: fc6a7eea682a76f03e85c4786aed3b02bdb06968
- 21.2.x: eddca4280b3026cbdff3153442df30b5c5870e3f
