### PR TITLE
fix(compiler-cli): do not type check native controls with ControlValueAccessor

### LINKED ISSUE #65468: docs-bug(datepicker): Usage with signal forms
### Documentation Feedback

Can you please add an example of using [`mat-datepicker`](https://material.angular.dev/components/datepicker/examples) with [signal forms](https://angular.dev/guide/forms/signals/overview)?

I tried to use it with a `Date` field, but I'm getting a typescript error:
```dart
Type 'Date' is not assignable to type 'string'.ngtsc(2322)
```

Image

---

**Typescript is saying that:**
- `field` is of type `Field<Date>.field: InputSignal<FieldTree<Date, string | number>>`
- `reportForm.reportDate` is of type `FieldTree<Date, string>` (not sure where the `string` came from)

**Simple form setup:**
```typescript
  formModel = signal({
    reportDate: new Date(),
  });
  reportForm = form(this.formModel);
```

### Affected documentation page

https://material.angular.dev/components/datepicker/examples

### PR DESCRIPTION
**Pull request by crisbeto**
Currently when we detect a `field` binding on a native element, we treat it as a built-in native control. This might not be the case if it's a pre-existing `ControlValueAccessor` relying on the CVA interop.

These changes try to detect any CVA-like directive on the element and disable the additional type checking if there are any.

Fixes #65468.

### CODE REVIEW

File: packages/compiler-cli/src/ngtsc/typecheck/src/ops/scope.ts [hunk 1]
```diff
@@ -776,7 +777,9 @@ export class Scope {
       isFieldDirective(dir) &&
       node instanceof TmplAstElement &&
       (node.name === 'input' || node.name === 'select' || node.name === 'textarea') &&
-      !allDirectiveMatches.some(getCustomFieldDirectiveType)
+      allDirectiveMatches.every((meta) => {
```
Comment (crisbeto) [inline packages/compiler-cli/src/ngtsc/typecheck/src/ops/scope.ts]: I was debating between this and disabling the native control type checking if there are _any_ directives (aside from `Field`) on the same element. I went with this approach, because the alternative seemed a bit aggressive.

Comment (mmalerba) [inline packages/compiler-cli/src/ngtsc/typecheck/src/ops/scope.ts]: nit: This `if` logic is getting pretty long, would it make sense to extract the new condition into a function called `hasCVA` or something

**Review by mmalerba — APPROVED** [review]

**Review by leonsenft — APPROVED** [review]
Are CVAs always directives? I know they're generally provided via the `NG_VALUE_ACCESSOR` token, so is there an edge case where the provided accessor isn't actually a directive, and could we catch that in type checking or no?

**Comment by crisbeto** [comment]
They're generally always directives so this should cover it. There _are_ cases where it's provided by assigning to `NgControl.valueAccessor` instead of providing the CVA token, but that shouldn't be an issue here.

**Comment by kirjs** [comment]
This PR was merged into the repository. The changes were merged into the following branches:

- main: 6b8720de913fb67e5131428e594b896ac2cc879a
- 21.0.x: 39c577bc362b263896b38c9486131d4342b8f1a8
