### PR TITLE
fix(core): adds transfer cache to httpResource to fix hydration

### LINKED ISSUE #62897: Resource `hasValue()` is false for a moment when using TransferState cached data, causing hydration to fail
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

A minimal reproduction demonstrating hydration issues when using @else and @empty blocks with the control flow syntax. The app fetches Pokemon data (httpClient + rxResource + transfer state enabled) and displays three scenarios:

1) Works: Uses separate @if blocks - hydration works correctly

Image

2) Broken: Uses @if/@else blocks - hydration fails

Image

3) Broken: Uses @for/@empty blocks - hydration fails

Image

Expected: All components should hydrate properly
Actual: When using @else or @empty, components are not hydrating

### Please provide a link to a minimal reproduction of the bug

https://github.com/zip-fa/ng20-new-hydration-issue

### Please provide the exception or error you saw

```true

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 20.1.3
Node: 24.2.0
Package Manager: npm 11.3.0
OS: darwin arm64

Angular: 20.1.3
... build, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-server, router, ssr

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.2001.3
@angular-devkit/core         20.1.3
@angular-devkit/schematics   20.1.3
@schematics/angular          20.1.3
rxjs                         7.8.2
typescript                   5.8.3
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by thePunderWoman**
This should prevent the microtask problem with hydration and httpResource.

fixes: #62897

### CODE REVIEW

File: packages/common/http/src/resource.ts [hunk 1]
```diff
@@ -234,10 +237,31 @@ function makeHttpResourceFn<TRaw>(responseType: ResponseType) {
...
+    if (cacheOptions && transferState) {
+      const req = untracked(() => normalizeRequest(request, responseType));
+      if (req) {
+        const cachedResponse = StateFromCache(req, cacheOptions, transferState, originMap);
+        if (cachedResponse) {
+          try {
+            const body = cachedResponse.body as TRaw;
+            defaultValue = options?.parse ? options.parse(body) : (body as unknown as TResult);
+          } catch (e) {
+            // Ignore parse errors from cache
```
Comment (SkyZeroZx) [inline packages/common/http/src/resource.ts]: Q: Would this be a silent failure for the user, or am I missing something?

Comment (thePunderWoman) [reply packages/common/http/src/resource.ts]: Yes, but it's safe here. Essentially the data wouldn't be successfully parsed, which would result in a network request rather than pulling from the cache. We wouldn't want an error to be thrown breaking someone's initial page load.

Comment (SkyZeroZx) [reply packages/common/http/src/resource.ts]: I was wondering if a warning would be a good thing, at least indicating that something happened, so they can trace it.

Comment (thePunderWoman) [reply packages/common/http/src/resource.ts]: Good suggestion. I've added that.

File: packages/core/src/resource/resource.ts [hunk 2]
```diff
@@ -196,6 +196,7 @@ export class ResourceImpl<T, R> extends BaseWritableResource<T> implements Resou
     private readonly equal: ValueEqualityFn<T> | undefined,
     private readonly debugName: string | undefined,
     injector: Injector,
+    private readonly initialStream?: Signal<ResourceStreamItem<T>>,
```
Comment (alxhub) [inline packages/core/src/resource/resource.ts]: Minor nit: we should clear this after we evaluate for the first time, to not leak the memory of the cached item.

File: packages/common/http/src/resource.ts [hunk 3]
```diff
@@ -234,13 +237,44 @@ function makeHttpResourceFn<TRaw>(responseType: ResponseType) {
...
+
+    let defaultValue: TResult | undefined = options?.defaultValue;
+    const cacheOptions = injector.get(CACHE_OPTIONS, null, {optional: true});
+    const transferState = injector.get(TransferState, null, {optional: true});
+    const originMap = injector.get(HTTP_TRANSFER_CACHE_ORIGIN_MAP, null, {optional: true});
+
+    let initialStream: Signal<ResourceStreamItem<TResult>> | undefined;
+
+    if (cacheOptions && transferState) {
+      const req = untracked(() => normalizeRequest(request, responseType));
```
Comment (alxhub) [inline packages/common/http/src/resource.ts]: This evaluates the `request` at creation time of the `httpResource`. If the request depends on things like `input()` signals, it will attempt to read them before change detection sets their value, causing a crash.

The whole calculation of the initial value for transfer state needs to be deferred / pushed into the resource's internal state `linkedSignal`.

We should also have a test for this :)

File: packages/common/http/src/transfer_cache.ts [hunk 4]
```diff
@@ -206,15 +202,59 @@ export function transferCacheInterceptorFn(
...
+  }
+
+  const requestUrl =
+    typeof ngServerMode !== 'undefined' && ngServerMode && originMap
+      ? mapRequestOriginUrl(req.url, originMap)
+      : req.url;
+  const storeKey = makeCacheKey(req, requestUrl);
+
+  // In the following situations we do not want to cache the request
+  if (
```
Comment (AndrewKushnir) [inline packages/common/http/src/transfer_cache.ts]: We have a similar check in the `StateFromCache` function. It'd be great to extract it out to a separate function and reuse in both places.

File: packages/common/http/src/transfer_cache.ts [hunk 5]
```diff
@@ -206,15 +202,59 @@ export function transferCacheInterceptorFn(
...
+  if (cachedResponse) {
+    return of(cachedResponse);
+  }
+
+  const {isCacheActive, ...globalOptions} = options;
+  const {transferCache: requestOptions, method: requestMethod} = req;
+  let headersToInclude = globalOptions.includeHeaders;
+  if (typeof requestOptions === 'object' && requestOptions.includeHeaders) {
+    headersToInclude = requestOptions.includeHeaders;
+  }
```
Comment (AndrewKushnir) [inline packages/common/http/src/transfer_cache.ts]: This logic also seems to be duplicated with the `StateFromCache` function.

File: packages/common/http/src/transfer_cache.ts [hunk 6]
```diff
@@ -123,11 +123,13 @@ const CACHE_OPTIONS = new InjectionToken<CacheOptions>(
  */
 const ALLOWED_METHODS = ['GET', 'HEAD'];
 
-export function transferCacheInterceptorFn(
+export function StateFromCache(
```
Comment (AndrewKushnir) [inline packages/common/http/src/transfer_cache.ts]: nit: naming suggestion
```suggestion
export function retrieveStateFromCache(
```

File: packages/common/http/src/transfer_cache.ts [hunk 7]
```diff
@@ -206,15 +202,59 @@ export function transferCacheInterceptorFn(
...
+export function transferCacheInterceptorFn(
+  req: HttpRequest<unknown>,
+  next: HttpHandlerFn,
+): Observable<HttpEvent<unknown>> {
+  const options = inject(CACHE_OPTIONS);
+  const transferState = inject(TransferState);
+
+  const originMap: Record<string, string> | null = inject(HTTP_TRANSFER_CACHE_ORIGIN_MAP, {
+    optional: true,
+  });
```
Comment (AndrewKushnir) [inline packages/common/http/src/transfer_cache.ts]: nit: we've moved this code without changes, but an explicit type annotation is not required here, we can simplify the code a bit:
```suggestion
  const originMap = inject(HTTP_TRANSFER_CACHE_ORIGIN_MAP, { optional: true });
```

File: packages/core/src/resource/resource.ts (hunk 2 above)
Comment (thePunderWoman) [reply packages/core/src/resource/resource.ts]: done!

File: packages/common/http/src/resource.ts (hunk 3 above)
Comment (thePunderWoman) [reply packages/common/http/src/resource.ts]: This now should be addressed.

**Review by alxhub — APPROVED** [review]
👍 LGTM

**Comment by thePunderWoman** [comment]
Caretaker note: broken test is unrelated. This is safe to merge.

**Comment by thePunderWoman** [comment]
This PR was merged into the repository. The changes were merged into the following branches:

- main: 88685cb3b6d6fc09239ca9f7c1201fe89e79d2a8
- 21.2.x: e2e9a9a531c9e9a69701e549f28354cc5d5edd77
