### PR TITLE
fix(compiler): support arbitrary nesting in :host-context()

### LINKED ISSUE #59176: Incorrect parsing of complex selectors inside `:host-context`
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

Basically the expectation is:
```
    expect(shim(':host-context(:where(.foo:not(.bar))) {}', 'contenta', 'hosta')).toEqualCss(
      ':where(.foo:not(.bar))[hosta], :where(.foo:not(.bar)) [hosta] {}',
    );
```

But it returns `([hosta]:where(.foo:not(.bar))) {}`. It looks like the regular expression which is used here doesn't parse nested selectors with parenthesis (i.e. `:not()` within ':where()`) correctly.

### Please provide a link to a minimal reproduction of the bug

Run the tests with `yarn test packages/compiler/test:test`, adding the test case above to the list.

### Please provide the exception or error you saw

```true

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Reproducible among different versions.
```

### Anything else?

I tried it with and without recent changes to the compiler, that changed the way `:where` and `:host-context` are being parsed, the result is identical between the versions.

### PR DESCRIPTION
**Pull request by mattrbeck**
Previously we supported one level of nested pseudo-element selectors inside `:host-context()`, e.g. `:host-context(:is(.foo, .bar))`. This was based on a regex-based approach. We could support deeper levels of nesting by updating the regex, but using a regex approach prohibits us from supporting arbitrary nesting.

Rather than just adding one more level to the existing expression, I've added a new generator function which splits selectors on commas in a parenthesis-aware way. This allows us to support arbitrary nesting.

It's likely we'll want to reuse this in other places where we're not as careful today. We'll probably do this on a request-based basis, though.

Fixes #59176

### CODE REVIEW

**Comment by JeanMeche** [comment]
(Adding the TGP label, those changes were often risky in the past).

**Comment by mattrbeck** [comment]
Thanks @JeanMeche! Does that tag trigger a TGP or just mark that we'd like the caretaker to run one? Any idea why the pullapprove bot is removing it?

**Comment by JeanMeche** [comment]
It mean that someone will need to run one. 
Ah yeah the bot only wants it on some specifics scopes...

File: packages/compiler/src/shadow_css.ts [hunk 1]
```diff
@@ -525,6 +525,40 @@ export class ShadowCss {
...
+   *
+   * @param text The string to split
+   */
+  private *_splitOnTopLevelCommas(text: string): Generator<string> {
+    const length = text.length;
+    let parens = 0;
+    let prev = 0;
+
+    for (let i = 0; i < length; i++) {
+      const char = text[i];
```
Comment (crisbeto) [inline packages/compiler/src/shadow_css.ts]: nit: since we only check if the `char` is a specific symbol, we could also use `.charCodeAt(i) === someCode` instead. We have constants for common char codes in `chars.ts`. I don't feel strongly about changing it.

File: packages/compiler/src/shadow_css.ts [hunk 2]
```diff
@@ -525,6 +525,40 @@ export class ShadowCss {
...
+          yield text.slice(prev, i);
+          return;
+        }
+      } else if (char === ',' && parens === 0) {
+        // Found a top-level comma, yield the current chunk
+        yield text.slice(prev, i);
+        prev = i + 1;
+      }
+    }
+
```
Comment (crisbeto) [inline packages/compiler/src/shadow_css.ts:558]: Do we need some validation in case the `parens > 0` by the end of the loop?

File: packages/compiler/src/shadow_css.ts [hunk 3]
```diff
@@ -525,6 +525,40 @@ export class ShadowCss {
...
+   */
+  private *_splitOnTopLevelCommas(text: string): Generator<string> {
+    const length = text.length;
+    let parens = 0;
+    let prev = 0;
+
+    for (let i = 0; i < length; i++) {
+      const char = text[i];
+
+      if (char === '(') {
```
Comment (crisbeto) [inline packages/compiler/src/shadow_css.ts]: A bit of an edge case, but is it possible to hit a selector here that has an escaped or quoted paren? E.g. `:host-context([someAttr=")"])`? I'm guessing the old approach didn't handle this either though...

File: packages/compiler/src/shadow_css.ts [hunk 4]
```diff
@@ -587,18 +597,27 @@ export class ShadowCss {
...
-        // `match` = [':host-context(<selectors>)<rest>', <selectors>, <rest>]
-
-        // The `<selectors>` could actually be a comma separated list: `:host-context(.one, .two)`.
-        const newContextSelectors = (match[1] ?? '')
-          .trim()
-          .split(',')
-          .map((m) => m.trim())
-          .filter((m) => m !== '');
+      // Loop until every :host-context in the compound selector has been processed.
+      while (selectorText.includes(_polyfillHostContext)) {
```
Comment (crisbeto) [inline packages/compiler/src/shadow_css.ts]: nit: I guess here we're making the linear search for `_polyfillHostContext` twice: once in the `while` expression and once for `startIndex`. Maybe we can do one `indexOf` and reuse it?

**Review by crisbeto — APPROVED** [review]

File: packages/compiler/src/shadow_css.ts (hunk 1 above)
Comment (mattrbeck) [reply packages/compiler/src/shadow_css.ts]: Is this a performance thing, like https://github.com/angular/angular/pull/32997?

File: packages/compiler/src/shadow_css.ts (hunk 3 above)
Comment (mattrbeck) [reply packages/compiler/src/shadow_css.ts]: It's possible, but the old approach didn't handle this either. I'm still open to the idea of moving to a proper parser, but that'd be significantly more work. I'm in favor of leaving this individual change more simple since it doesn't regress anything, and we can consider making it more robust separately.

File: packages/compiler/src/shadow_css.ts (hunk 1 above)
Comment (crisbeto) [reply packages/compiler/src/shadow_css.ts]: Yeah I think it's supposed to be slightly faster for these single character cases. Anyways, I don't think it's a blocker.

Comment (mattrbeck) [reply packages/compiler/src/shadow_css.ts]: Made the change anyway 👍

**Comment by mattrbeck** [comment]
Tested: http://test/OCL:823161254:BASE:823582831:1761327167500:577d4b25

**Comment by crisbeto** [comment]
This PR was merged into the repository. The changes were merged into the following branches:

- main: b478e910680d01b076b49e348ef9fd2e0abbe0b2
- 21.0.x: 04dd75ba948889601bf611254021577aba458d4c
