### PR TITLE
fix(router): runs guards every time when unsuccessfully navigating to…

### LINKED ISSUE #12851: Router 3.2.0 - canDeactivate runs only once
let's say you have a confirmation dialog on canDeactivate. if user refuses to leave a form (clicks No), the dialog closes (promise is resolved to false). now, user does the same thing again but canDeactivate doesn't fire anymore.

This doesn't happen on 3.1.0.

### PR DESCRIPTION
**Pull request by vsavkin**
Closes https://github.com/angular/angular/issues/12851

### CODE REVIEW

File: modules/@angular/router/src/router.ts [hunk 1]
```diff
@@ -387,8 +387,17 @@ export class Router {
     // which does not work properly with zone.js in IE and Safari
     this.locationSubscription = <any>this.location.subscribe(Zone.current.wrap((change: any) => {
       const rawUrlTree = this.urlSerializer.parse(change['url']);
+      const lastNavigation = this.navigations.value;
+
+      // TODO add a comment describing why it has to be like that
```
Comment (vicb) [inline modules/@angular/router/src/router.ts]: TODO ?

File: modules/@angular/router/src/router.ts [hunk 2]
```diff
@@ -281,11 +281,11 @@ function defaultErrorHandler(error: any): any {
 type NavigationParams = {
   id: number,
   rawUrl: UrlTree,
-  prevRawUrl: UrlTree,
   extras: NavigationExtras,
   resolve: any,
   reject: any,
   promise: Promise<boolean>
+  imperative: boolean;
```
Comment (vicb) [inline modules/@angular/router/src/router.ts]: I also never remember if it should be ,/; in types but here you have ""/,/;, must be wrong
