### PR TITLE
fix(testing): add an explicit doAsyncPrecompilation step

### LINKED ISSUE #9593: Rename TestInjector to TestBed

### LINKED ISSUE #9975: Review API for `inject` now that we have app modules
In https://github.com/angular/angular/pull/9846, we switched to using `AppModule`s for tests. This is great because it allows for more flexibility, but one consequence is that each test case _may_ require asynchronous setup, in order to precompile components with external templates (because they need to make an XHR).

The solution in #9846 was to make the `inject` helper method inspect whether it is being called inside an `async` block or not. This will work for most current user cases, but destroys encapsulation and ties users to our ways of dealing with async. It's also a lot of 'just trust us magic'.

We could, instead, require the user to let us know if they need to do something asynchronous. This could look like:

```js
beforeEach(async(() => {
  configureModule({
    precompile: MyComponentWithExternalTemplate;
  });

  doAsyncPrecompilation(); // Proposed new method
}));

it('does something with that module', inject([TestComponentBuilder], (builder) => {
  // This will always be called synchronously now.
  var fixture = builder.createSync(MyComponentWithExternalTemplate);
});
```

Currently, (in master at the moment) this would look like:

```js
beforeEach(() => {
  configureModule({
    precompile: MyComponentWithExternalTemplate;
  });
});

it('does something with that module', async(inject([TestComponentBuilder], (builder) => {
  // This will throw an error if it's not inside an async block.
  var fixture = builder.createSync(MyComponentWithExternalTemplate);
}));
```

### PR DESCRIPTION
**Pull request by juliemr**
This removes the magic from the `inject` test helper that would inspect
the current zone and would only work with our `async` test helper.
Now, `inject` is always synchronous, and if you are using a module
that requires async precompilation, you're required to call
`doAsyncPrecompilation` in your tests.

This is part of the breaking changes introduced with the swap
to each test having an AppModule.

Also, cleans up some APIs and renames `TestInjector` to `TestBed`.

Closes #9975
Closes #9593

### CODE REVIEW

File: modules/@angular/platform-browser/test/testing_public_spec.ts [hunk 1]
```diff
@@ -300,27 +303,21 @@ export function main() {
...
-      });
-
-      it('should allow to precompile components with templateUrl using the async helper',
-         async(withModule(() => {
-                 return {precompile: [CompWithUrlTemplate]};
-               }).inject([ComponentFactoryResolver], (resolver: ComponentFactoryResolver) => {
-           expect(resolver.resolveComponentFactory(CompWithUrlTemplate).componentType)
-               .toBe(CompWithUrlTemplate);
-         })));
+      // beforeEach(() => {
```
Comment (juliemr) [inline modules/@angular/platform-browser/test/testing_public_spec.ts]: Cleanup: remove this comment.

File: modules/@angular/core/testing/test_injector.ts [hunk 2]
```diff
@@ -231,10 +264,23 @@ export function resetBaseTestProviders() {
...
+  testBed.platform = null;
+  testBed.appModule = null;
+  testBed.reset();
+}
+
+/**
+ * Run asynchronous precompilation for the test's AppModule. It is necessary to call this function
+ * if your test is using an AppModule which has precompiled components that require an asynchronous
+ * call,
+ * such as an XHR. Should be called once before the test case.
```
Comment (vikerman) [inline modules/@angular/core/testing/test_injector.ts]: nit: Move one line up?

Comment (juliemr) [inline modules/@angular/core/testing/test_injector.ts]: thanks clang :/

Done!

File: modules/@angular/platform-browser/test/testing_public_spec.ts [hunk 3]
```diff
@@ -454,26 +446,27 @@ export function main() {
...
-        restoreJasmineIt();
-      });
+      it('should report an error for precompile components with templateUrl which never call doAsyncPrecompile',
+         () => {
+           var itPromise = patchJasmineIt();
+
+           expect(
+               () =>
+                   it('should fail',
+                      withModule(() => { return {precompile: [CompWithUrlTemplate]}; })
```
Comment (IgorMinar) [inline modules/@angular/platform-browser/test/testing_public_spec.ts]: "{ return" is not needed

File: tools/public_api_guard/core/testing.d.ts [hunk 4]
```diff
@@ -82,6 +88,29 @@ export declare function resetTestEnvironment(): void;
...
+    }): void;
+    configureModule(moduleDef: {
+        providers?: any[];
+        directives?: any[];
+        pipes?: any[];
+        precompile?: any[];
+        modules?: any[];
+    }): void;
+    createAppModuleFactory(): Promise<AppModuleFactory<any>>;
+    deprecatedCreateInjectorAsync(): Promise<Injector>;
```
Comment (IgorMinar) [inline tools/public_api_guard/core/testing.d.ts]: do we need to do this? this method was created only after rc.4, so we should be able to just remove it.

File: tools/public_api_guard/core/testing.d.ts [hunk 5]
```diff
@@ -82,6 +88,29 @@ export declare function resetTestEnvironment(): void;
 /** @deprecated */
 export declare function setBaseTestProviders(platformProviders: Array<Type | Provider | any[]>, applicationProviders: Array<Type | Provider | any[]>): void;
 
+/** @experimental */
+export declare class TestBed implements Injector {
+    appModule: Type;
+    platform: PlatformRef;
+    configureCompiler(config: {
```
Comment (IgorMinar) [inline tools/public_api_guard/core/testing.d.ts]: is this method useful for anything else than testing the internals of the framework? should it be public api?

File: tools/public_api_guard/core/testing.d.ts (hunk 4 above)
Comment (IgorMinar) [inline tools/public_api_guard/core/testing.d.ts]: I see that it's being used by `inject` but only for the AsyncCompleter flow. maybe instead of deprecating we should just prefix it with `_`?

File: modules/@angular/core/testing/test_injector.ts [hunk 6]
```diff
@@ -148,23 +174,30 @@ export class TestInjector implements Injector {
...
+  if (_testBed == null) {
+    _testBed = new TestBed();
   }
-  return _testInjector;
+  return _testBed;
+}
+
+/**
+ * @deprecated use getTestInjector instead.
+ */
```
Comment (IgorMinar) [inline modules/@angular/core/testing/test_injector.ts]: you didn't document the TestInjector -> TestBed rename and deprecation of the TestInjector in the commit message. can you please add it there?

File: modules/@angular/core/testing/test_injector.ts [hunk 7]
```diff
@@ -148,23 +174,30 @@ export class TestInjector implements Injector {
   execute(tokens: any[], fn: Function): any {
     if (!this._instantiated) {
       throw new BaseException(
-          'Illegal state: The TestInjector has not yet been created. Call createInjectorSync/Async first!');
+          'Illegal state: The TestBed has not yet been created. Call createInjectorSync/Async first!');
```
Comment (IgorMinar) [inline modules/@angular/core/testing/test_injector.ts]: "createInjectorSync/Async" is outdated

File: modules/@angular/core/testing/test_injector.ts [hunk 8]
```diff
@@ -134,9 +160,9 @@ export class TestInjector implements Injector {
   get(token: any, notFoundValue: any = Injector.THROW_IF_NOT_FOUND) {
     if (!this._instantiated) {
       throw new BaseException(
-          'Illegal state: The TestInjector has not yet been created. Call createInjectorSync/Async first!');
+          'Illegal state: The TestBed has not yet been created. Call createInjectorSync/Async first!');
```
Comment (IgorMinar) [inline modules/@angular/core/testing/test_injector.ts]: "createInjectorSync/Async" is outdated

File: tools/public_api_guard/core/testing.d.ts (hunk 4 above)
Comment (juliemr) [inline tools/public_api_guard/core/testing.d.ts]: Done.

File: tools/public_api_guard/core/testing.d.ts (hunk 5 above)
Comment (juliemr) [inline tools/public_api_guard/core/testing.d.ts]: It's only used for testing internals now, but I can imagine advanced users wanting to change the JIT settings. I'd lean on keeping it public.

File: modules/@angular/core/testing/test_injector.ts (hunk 7 above)
Comment (juliemr) [inline modules/@angular/core/testing/test_injector.ts]: done.

File: modules/@angular/core/testing/test_injector.ts (hunk 8 above)
Comment (juliemr) [inline modules/@angular/core/testing/test_injector.ts]: done.

File: modules/@angular/core/testing/test_injector.ts (hunk 6 above)
Comment (juliemr) [inline modules/@angular/core/testing/test_injector.ts]: done.

File: modules/@angular/platform-browser/test/testing_public_spec.ts (hunk 3 above)
Comment (juliemr) [inline modules/@angular/platform-browser/test/testing_public_spec.ts]: tsc complains without it, I think because of the object synta.

**Comment by juliemr** [comment]
Done, and Travis is happy again. Please take a look!

File: modules/@angular/core/testing/test_injector.ts [hunk 9]
```diff
@@ -18,11 +18,12 @@ const UNDEFINED = new Object();
 /**
  * @experimental
  */
-export class TestInjector implements Injector {
+export class TestBed implements Injector {
```
Comment (IgorMinar) [inline modules/@angular/core/testing/test_injector.ts]: do you also want to rename the file to test_bed.ts?

**Comment by IgorMinar** [comment]
otherwise lgtm

File: modules/@angular/core/testing/test_injector.ts (hunk 9 above)
Comment (juliemr) [inline modules/@angular/core/testing/test_injector.ts]: done!

**Comment by juliemr** [comment]
Thanks! Waiting on Travis and then I'll merge.
