### PR TITLE
fix(animations): ensure parent animations are triggered before children

### LINKED ISSUE #10737: RC5 still does not animate nested elements correctly (persistent problem)
**I'm submitting a persistent problem with animations of nested elements in RC5.
```
[x] bug report
```

**Current behavior**
This problem was reported in RC2 (https://github.com/angular/angular/issues/9402 and https://github.com/angular/angular/pull/9887) and it had to be resolved by commit https://github.com/angular/angular/commit/c3bdd504d0ea1166d26df359c7bbd9d28df70c99. But it is not true. The problem still exists.

Plunker demo: There is an outermost DIV that contains another inner DIV. Buttons allow to expand and collapse them individually. Steps to show:
- Expand the outer and then inner.
- Continue with collapsing the outer.
- Finally expand the outer again.

**Expected/desired behavior**
Expanding animation of the outermost DIV should respect its full content (including inner div) which is available at the actual moment.

**Reproduction of the problem**
Plunker: http://plnkr.co/edit/58pVfEs0cJAxvQfwlIpr?p=preview

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all]
 
* **Language:** [all]

### PR DESCRIPTION
**Pull request by matsko**
Closes #10737

### CODE REVIEW

File: modules/@angular/core/src/linker/view.ts [hunk 1]
```diff
@@ -28,6 +29,8 @@ import {ViewUtils, ensureSlotCount, flattenNestedViewRenderNodes} from './view_u
 
 var _scope_check: WtfScopeFn = wtfCreateScope(`AppView#check(ascii id)`);
 
+var _animationQueue: AnimationPlayer[] = [];
```
Comment (tbosch) [inline modules/@angular/core/src/linker/view.ts]: Remove either this array or the one in animation_queue

Comment (tbosch) [inline modules/@angular/core/src/linker/view.ts]: Probably remove this one

File: modules/@angular/core/src/linker/view.ts [hunk 2]
```diff
@@ -51,6 +54,7 @@ export abstract class AppView<T> {
   private _hasExternalHostElement: boolean;
 
   public animationPlayers = new ViewAnimationMap();
+  public queuedAnimations: AnimationPlayer[] = [];
```
Comment (tbosch) [inline modules/@angular/core/src/linker/view.ts]: Why do we need this array as well?

File: modules/@angular/core/src/linker/view_ref.ts [hunk 3]
```diff
@@ -103,8 +106,14 @@ export class ViewRef_<C> implements EmbeddedViewRef<C>, ChangeDetectorRef {
   get destroyed(): boolean { return this._view.destroyed; }
 
   markForCheck(): void { this._view.markPathToRootAsCheckOnce(); }
-  detach(): void { this._view.cdMode = ChangeDetectorStatus.Detached; }
-  detectChanges(): void { this._view.detectChanges(false); }
+  detach(): void {
+    this._view.cdMode = ChangeDetectorStatus.Detached;
+    triggerQueuedAnimations();
```
Comment (tbosch) [inline modules/@angular/core/src/linker/view_ref.ts]: Why do we need this here?

File: modules/@angular/core/test/animation/animation_integration_spec.ts [hunk 4]
```diff
@@ -961,6 +963,85 @@ function declareTests({useJit}: {useJit: boolean}) {
...
+           var innerPlayer: any = <InnerContentTrackingAnimationPlayer>inner['player'];
+           var outer: any = driver.log.pop();
+           var outerPlayer: any = <InnerContentTrackingAnimationPlayer>outer['player'];
+
+           expect(InnerContentTrackingAnimationPlayer.initLog).toEqual([
+             outerPlayer.element, innerPlayer.element
+           ]);
+         }));
+
+      it('should trigger animations that exist in nested views without a chain of animations in between',
```
Comment (tbosch) [inline modules/@angular/core/test/animation/animation_integration_spec.ts]: What is a "chain of animations"?
