### PR TITLE
fix(language-service): do not crash when hovering over a label definition

### LINKED ISSUE #17972: Language Service: Hovering over template reference throws Error
## I'm submitting a ...

<pre><code>
[x] Bug report 
</code></pre>

## Current behavior

Hovering over a template reference will throw.

https://github.com/angular/vscode-ng-language-service/issues/121

## Expected behavior

No throw.

## Minimal reproduction of the problem with instructions

Add: `<div #chart><div>` to a template (such as a `ng new` project's `app.component.html`) and hover over `#chart`.

### PR DESCRIPTION
**Pull request by chuckjaz**
Fixes: #17972

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
```

## What is the current behavior?

Issue Number:  #17972

## What is the new behavior?

No longer crashes.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

File: packages/language-service/test/hover_spec.ts [hunk 1]
```diff
@@ -68,6 +68,16 @@ describe('hover', () => {
         'property name of TestComponent');
   });
 
+  it('should be able to ignore a reference declaration', () => {
+    addCode(
+        ` @Component({template: '<div #«chart»></div>'}) export class MyComponent {  }`,
```
Comment (vicb) [inline packages/language-service/test/hover_spec.ts]: are the special quotes expected here ?

**Review by vicb — APPROVED** [review]

File: packages/language-service/test/hover_spec.ts (hunk 1 above)
Comment (chuckjaz) [inline packages/language-service/test/hover_spec.ts]: This is a marker so the test knows where to ask for the hover. it is removed before parsing. The surrounding tests also use this mechanism.
