### PR TITLE
fix(compiler): support complex selectors in :nth-child()

### LINKED ISSUE #64913: nth-child with of adds unexpected [_ngcontent] attr to selector
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

Consider these styles:
```css
:host:nth-child(1 of *:not(.lol):not(.whatever)) {
  color: blue;
}

:host:nth-child(1 of *:not(.whatever)) {
  color: red !important;
}
```

First one works correctly but the second one, **without dual `:not`**, adds an unexpected content attribute to selector.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-tnsye4fb

### Please provide the exception or error you saw

```true
[_nghost-ng-c1419874505]:nth-child(1 of *:not(.lol):not(.whatever)) {
  color: blue;
}

[_nghost-ng-c1419874505][_ngcontent-ng-c1419874505]:nth-child(1 of *:not(.whatever)) {
  color: red !important;
}
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Latest
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mattrbeck**
:nth-child() (and its siblings) support complex expressions, e.g. `:nth-child(2n of :is(.foo, .bar))`. Previously we'd choke because of the `:is()`. Now, we reuse the `_parenSuffix` subexpression to match nested parentheses the same way we do for :host() and :host-context(). Note that we only support 3 levels of nesting, so a selector like `:nth-child(n of :is(:has(:not(.foo))))` will still break.

I'll say yet again that we really should add a proper parser so we stop getting bug reports like this :)

Fixes #64913

### CODE REVIEW

File: packages/compiler/src/shadow_css.ts [hunk 1]
```diff
@@ -1076,6 +1076,7 @@ const _level1Parens = String.raw`(?:\(${_noParens}\)|${_noParens})+?`;
 // Matches content with at most TWO levels of nesting, e.g., "a(b(c)d)e"
 const _level2Parens = String.raw`(?:\(${_level1Parens}\)|${_noParens})+?`;
 const _parenSuffix = String.raw`(?:\((${_level2Parens})\))`;
+const nthRegex = new RegExp(String.raw`(:nth-[-\w]+)` + _parenSuffix, 'g');
```
Comment (crisbeto) [inline packages/compiler/src/shadow_css.ts:1079]: Regexes with the `g` flag have a state. Is that a concern for this case?

**Review by crisbeto — APPROVED** [review]

File: packages/compiler/src/shadow_css.ts (hunk 1 above)
Comment (mattrbeck) [reply packages/compiler/src/shadow_css.ts:1079]: I don't think it's a concern. You may know more or be more familiar, though. The existing expression also uses the global flag, so I believe this produces the same results. (I know regexp literals are compiled on script load, but IIRC otherwise they behave identically to instantiating a `RegExp`?)

From my read of the spec and docs on MDN, it looks like while using the `g` flag makes the RegExp track its `lastIndex` for the match. This is relevant for the `RegExp.prototype.exec()` method, which it appears `String.prototype.replace()` calls repeatedly. Since this should replace all occurrences in the string, `lastIndex` should be reset to 0 by the end ([MDN description](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/lastIndex#description)).

The statefulness seems like more of a concern if you `exec` against one string then `exec` against another string without resetting `lastIndex`.

**Comment by mattrbeck** [comment]
Tested http://test/OCL:830517039:BASE:830474775:1762836426271:ebf1b6fa

Both failures are flakes.

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository. The changes were merged into the following branches:

- main: 24cfd5a0ed5090f6e60971e4c2b676dca6d262fc
- 20.3.x: 9419ea348a296b50f13ac2e23ea9a00b336989b8
- 21.0.x: 814b2713f56f94372db7e15e0a86f089a88f888d
