### PR TITLE
Aio break on bad links etc

### LINKED ISSUE #16936: aio: fail docs if examples are missing
Stuff like this

```
info:    running processor: renderExamples
error:   Missing example file... relativePath: "forms/src/app/app.component.ts". - doc "guide/forms" (content)  - from file "guide/forms.md" - starting at line 1
error:   Example files can be found in: examples, examples
```

should fail the build

### LINKED ISSUE #17942: aio: configure dgeni to break build if there are dangling links

### PR DESCRIPTION
**Pull request by petebacondarwin**
Closes #16936
Closes #17942
Closes #18034

### CODE REVIEW

**Comment by petebacondarwin** [comment]
And of course the build on Travis is failing because we do actually have dangling links right now.

File: aio/tools/transforms/angular-base-package/post-processors/add-image-dimensions.js [hunk 1]
```diff
@@ -20,14 +20,16 @@ module.exports = function addImageDimensions(getImageDimensions) {
...
-              props.width = '' + dimensions.width;
-              props.height = '' + dimensions.height;
+              if (props.width === undefined && props.height === undefined) {
+                props.width = '' + dimensions.width;
+                props.height = '' + dimensions.height;
+              }
             } catch(e) {
               if (e.code === 'ENOENT') {
-                file.message('Unable to load src in image tag `' + source(node, file) + '`');
+                file.fail('Unable to load src in image tag `' + source(node, file) + '`');
```
Comment (gkalpak) [inline aio/tools/transforms/angular-base-package/post-processors/add-image-dimensions.js]: Having this as a side effect of `getImageDimensions()` is not ideal, but happy to go with it for now 😛

**Review by gkalpak — APPROVED** [review]

**Comment by petebacondarwin** [comment]
Cherry picked to 4.3.x as

fda607cc2fafe49f7f52c6afbc701a3dec0172c8 build(aio): fail doc-gen if referenced images are missing
cc3aa681237d68d7f77b91b1f8a85567d7034ca7 docs(aio): fix broken image sources
306621d2d671b0905c809282f720fb01c87647db docs(aio): fix up broken links
d204f7aa2ae0bb0a20e6b8fe53e339147c2fff6e build(aio): abort doc-gen on dangling links
a94f5e8cbb3e7f94fc9550a38d29b21c273050b5 build(aio): abort doc-gen if an example is missing
