### PR TITLE
fix(compiler): StaticReflector ignores unregistered decorators.

### LINKED ISSUE #9182: StaticReflector tests should use the MetadataCollector
The `StaticReflector` currently has a mock collector with stub data.

The test should be changed to use the `MetadataCollector` to make the tests easier to read as well as validate that the collector and the static reflector agree on the results.

### LINKED ISSUE #9265: StaticReflector reports 'call not supported' if a class uses a custom decorator.
* **I'm submitting a ...**
```
[x] bug report
```

**Current behavior**

When getting metadata statically for a type such as:

```typescript
export class Foo {
  @CustomDecorator() get foo(): string { return ''; }
}
```

the static reflector reports `Unsupported function call ...`.

**Expected/desired behavior**

The custom decorator should be ignored.

### PR DESCRIPTION
**Pull request by chuckjaz**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-format
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
#9265

**What is the new behavior?**

Unrecognized decorators are ignored.

**Does this PR introduce a breaking change?**
- [ ] Yes
- [x] No

**Other information**:

Also modified static reflector to allow writing tests in using
the .ts and using the MetadataCollector.

Also made MetadataCollector be able to use SourceFiles that have
not been bound (that is, don't have the parent property set).

Fixes #9182
Fixes #9265

### CODE REVIEW

File: modules/@angular/compiler-cli/test/static_reflector_spec.ts [hunk 1]
```diff
@@ -322,16 +328,57 @@ describe('StaticReflector', () => {
...
+        host.getStaticSymbol('/tmp/src/custom-decorator-reference.ts', 'Foo'));
+    expect(props).toEqual({foo: []});
+  });
 });
 
 class MockReflectorHost implements StaticReflectorHost {
   private staticTypeCache = new Map<string, StaticSymbol>();
+  private collector: MetadataCollector;
+
+  constructor() { this.collector = new MetadataCollector(); }
```
Comment (vicb) [inline modules/@angular/compiler-cli/test/static_reflector_spec.ts]: - move instantation to declaration
- private members should start with "_"

**Comment by vicb** [comment]
LGTM with minor comments

File: modules/@angular/compiler-cli/test/static_reflector_spec.ts (hunk 1 above)
Comment (chuckjaz) [inline modules/@angular/compiler-cli/test/static_reflector_spec.ts]: Fixed the instantiation.
Decided off-line that we should decide on a convention globally and stick to it. Right now we are inconsistent. This can be fixed with the conversion to the global convention.

File: modules/@angular/compiler-cli/src/static_reflector.ts [hunk 2]
```diff
@@ -472,7 +482,11 @@ export class StaticReflector implements ReflectorReader {
       }
     }
 
-    return simplifyInContext(context, value);
+    let result = simplifyInContext(context, value, true);
```
Comment (tbosch) [inline modules/@angular/compiler-cli/src/static_reflector.ts]: This will remove a bunch of useful errors when calling functions in one of our decorators.
E.g. when a user does this:
```
// non exported function
function _test() {}

@Component({
  providers: [_myTest()]
})
```

Observation: `simplify` is only called for 

* decorators
* constructor parameter types array

We could do the following algorithm:

* If we want to simplify a decorator, we should check the decorator first whether it is know to us. If so, we should simplify as before this change throwing as before. If the decorator is unknown, we should not simplify at all.
* If we want to simplify the constructor parameter types, we should simplify as before this change and throw as before.

This should solve the problem of using unknown decorators as well as keeping the good error messages for our known decorators.

File: tools/@angular/tsc-wrapped/src/symbols.ts [hunk 3]
```diff
@@ -36,6 +36,10 @@ export class Symbols {
             const externalReference =
                 <ts.ExternalModuleReference>importEqualsDeclaration.moduleReference;
             // An `import <identifier> = require(<module-specifier>);
+            if (!externalReference.expression.parent) {
```
Comment (tbosch) [inline tools/@angular/tsc-wrapped/src/symbols.ts]: What are these changes about? Do we need a test for them (probably in the `tsc-wrapped` folder)?

File: modules/@angular/compiler-cli/src/static_reflector.ts (hunk 2 above)
Comment (tbosch) [inline modules/@angular/compiler-cli/src/static_reflector.ts]: We obviously are missing tests for these error messages in our known decorators, otherwise this change would not be green on Travis. Could you also add them?

File: tools/@angular/tsc-wrapped/src/symbols.ts (hunk 3 above)
Comment (chuckjaz) [inline tools/@angular/tsc-wrapped/src/symbols.ts]: The `parent` property of TypeScript nodes are set by the binder. If a `SourceFile` hasn't been bound then its nodes will not have their `parent` set. If the `parent` property is not set the `getText()` method will throw. This change allows the collector to collect metadata on files that have not been bound as is the case for my tests and might be the case if this is used in `webpack` that transforms modules without type-checking (type checking is done in a separate child process).

I will add a comment as to why this is being done here.

File: modules/@angular/compiler-cli/src/static_reflector.ts (hunk 2 above)
Comment (chuckjaz) [inline modules/@angular/compiler-cli/src/static_reflector.ts]: I believe I already do what you suggest.
- Decorators are encoded as calls to the decorator function.
- If the decorator is known we literally call the same code that would have been invoked by the decorator.
- If the function is not known we try to see if we have `function` definition in metadata, if so invoke it.
- If not we will throw based on the `ignoreCalls` flag. The `ignoreCalls` flag is only set on the initial call (that is the call to the decorator). Nested calls turn the `ignoreCalls` off meaning function calls that we cannot understand in a parameter to a decorator that we do understand will be reported just as before.

This means only decorators are ignored. If the decorator is understood then we will simplify its parameter(s) as before and throw as before.

In any case, I will add some negative test cases and verify that the errors are being reported correctly.

File: tools/@angular/tsc-wrapped/src/symbols.ts (hunk 3 above)
Comment (tbosch) [inline tools/@angular/tsc-wrapped/src/symbols.ts]: Ah, interesting! What is binding?

File: modules/@angular/compiler-cli/src/static_reflector.ts (hunk 2 above)
Comment (tbosch) [inline modules/@angular/compiler-cli/src/static_reflector.ts]: Ah, I think you are right, thanks for the explanation.

File: modules/@angular/compiler-cli/src/static_reflector.ts [hunk 4]
```diff
@@ -251,7 +235,7 @@ export class StaticReflector implements ReflectorReader {
     let scope = BindingScope.empty;
     let calling = new Map<StaticSymbol, boolean>();
 
-    function simplifyInContext(context: StaticSymbol, value: any): any {
+    function simplifyInContext(context: StaticSymbol, value: any, ignoreCalls: boolean): any {
```
Comment (tbosch) [inline modules/@angular/compiler-cli/src/static_reflector.ts]: Agreed offline to introduce `callDepth` parameter, and then check against `callDepth === 0` for whether to ignore calls. This way it is more obvious what we are doing here.
