### PR TITLE
fix(change_detection): _throwError should not mask the original excep…

### LINKED ISSUE #4405: In case of error, DynamicChangeDetector assumes propertyBindingIndex is set
Other errors get obfuscated by exceptions raised by DynamicChangeDetector when evaluating `_currentBinding()` on a `DynamicChangeDetector` instance if the `propertyBindingIndex` is null. This occurred in dart.

### PR DESCRIPTION
**Pull request by vsavkin**
…tion

Closes #4405

### CODE REVIEW

**Comment by jeffbcross** [comment]
This should close #4405

File: modules/angular2/test/core/change_detection/change_detector_spec.ts [hunk 1]
```diff
@@ -797,6 +799,22 @@ export function main() {
...
         });
+
+        it('should handle unexpected errors in the event handler itself', () => {
+          var throwingDispatcher = new SpyChangeDispatcher();
+          throwingDispatcher.spy("getDebugContext")
+              .andCallFake((_, __) => { throw new BaseException('boom'); });
+
+          var val =
+              _createChangeDetector('invalidFn(1)', _DEFAULT_CONTEXT, null, throwingDispatcher);
+          try {
```
Comment (rkirov) [inline modules/angular2/test/core/change_detection/change_detector_spec.ts]: Don't we have `expectToThrow` or somethings of sorts? Why is this method of asserting failures preferable?

Comment (vsavkin) [inline modules/angular2/test/core/change_detection/change_detector_spec.ts]: We have `expect(() => blah).toThrowError`, but it does not allow you to inspect the thrown exception. It only allows you to check its message.
