### PR TITLE
fix(compiler): Correctly handles references to static methods

### LINKED ISSUE #10975: angular-forms: "Cannot read property 'validate' of null" on AoT compiled app
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Current behavior**

`normalizeValidator` in [normalize_validator.ts](https://github.com/sod/angular/blob/eef9512ce6b8b72f8753d2964304745d621cf0d7/modules/@angular/forms/src/directives/normalize_validator.ts#L14-L14) checks for undefined, but most default values on controls are null:

image

Results in Error: `Cannot read property 'validate' of null`

**Reproduction of the problem**

Error does not happen in JIT, but when app precompiled and router is used.

**Plunkr**: http://plnkr.co/edit/j4j4stKtA9dRbEwBdhXC?p=preview `app/app-precompiled.ts` is the precompiled `app/app.ts` via `ngc`. 

Versions used:

```log
    "@angular/common": "2.0.0-rc.5",
    "@angular/compiler": "2.0.0-rc.5",
    "@angular/compiler-cli": "0.5.0",
    "@angular/core": "2.0.0-rc.5",
    "@angular/forms": "0.3.0",
    "@angular/http": "2.0.0-rc.5",
    "@angular/platform-browser": "2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "2.0.0-rc.5",
    "@angular/platform-server": "2.0.0-rc.5",
    "@angular/router": "3.0.0-rc.1",
```

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Language:** [TypeScript 2.0.0]

### PR DESCRIPTION
**Pull request by chuckjaz**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-format
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

References to static methods in providers and other metadata resulted in a `null` at runtime when using AoT. #10975

**What is the new behavior?**

References to static methods are correctly generated by AoT.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

**Other information**:

Fixes: #10975

### CODE REVIEW

File: modules/@angular/compiler-cli/src/reflector_host.ts [hunk 1]
```diff
@@ -221,11 +221,12 @@ export class ReflectorHost implements StaticReflectorHost, ImportGenerator {
    * @param declarationFile the absolute path of the file where the symbol is declared
    * @param name the name of the type.
    */
-  getStaticSymbol(declarationFile: string, name: string): StaticSymbol {
-    let key = `"${declarationFile}".${name}`;
+  getStaticSymbol(declarationFile: string, name: string, members?: string[]): StaticSymbol {
+    const memberSuffix = members ? `.${ members.join('.')}` : '';
+    const key = `"${declarationFile}".${name}${memberSuffix}}`;
```
Comment (vicb) [inline modules/@angular/compiler-cli/src/reflector_host.ts]: `}}` should be `}` ?

File: modules/@angular/compiler-cli/src/static_reflector.ts [hunk 2]
```diff
@@ -451,7 +451,12 @@ export class StaticReflector implements ReflectorReader {
                   if (declarationValue && declarationValue.statics) {
                     selectTarget = declarationValue.statics;
                   } else {
-                    return null;
+                    const member: string = expression['member'];
+                    const members = selectTarget.members ?
+                        (selectTarget.members as string[]).slice(0).concat(member) :
```
Comment (vicb) [inline modules/@angular/compiler-cli/src/static_reflector.ts]: remove `.slice(0)` ?
