### PR TITLE
fix(change_detection): throw ChangeDetectionError in JIT mode

### LINKED ISSUE #2906: Throw ChangeDetectionError in JIT mode

### PR DESCRIPTION
**Pull request by vsavkin**
Closes #2906

### CODE REVIEW

File: modules/angular2/test/transform/integration/two_annotations_files/expected/bar.ng_deps.dart [hunk 1]
```diff
@@ -40,15 +41,23 @@ class _MyComponent_ChangeDetector0 extends _gen.AbstractChangeDetector {
...
     var change_context = false;
     var isChanged = false;
-    var currentProto;
+    currentProto = null;
     var changes = null;
 
     context = _context;
 
-    _alreadyChecked = true;
+    _alreadyChecked = true;
```
Comment (yjbanov) [inline modules/angular2/test/transform/integration/two_annotations_files/expected/bar.ng_deps.dart]: remove trailing whitespace from generated code
