### PR TITLE
fix(router): generate links for router-link with baseHref

### LINKED ISSUE #1850: router-link does not support baseHref
The following html
`</router-outlet><a router-link="foo">link</a>`
and config 
```
const {
  'path': 'foo',
  'component': FooCmp,
  'as': 'foo'
}
```
with baseHref `/hello/web` should generate href `/hello/web/foo`, while it generates `/foo` right now.

Similarly `router.navigate('foo')` (router injected into the given component) should act like clicking on that anchor tag.

### PR DESCRIPTION
**Pull request by btford**
There's a bit more work to do to disambiguate `router-link="/foo"` and `router-link="foo"`, but this at least makes `router-link="foo"` do the right thing with the base href.

Closes #1850

### CODE REVIEW

File: modules/angular2/test/router/outlet_spec.js [hunk 1]
```diff
@@ -136,6 +136,19 @@ export function main() {
...
 
 
+    it('should generate absolute hrefs that include the base href', inject([AsyncTestCompleter], (async) => {
+      location.setBaseHref('/my/base');
+      compile('<a href="hello" router-link="user"></a>')
+        .then((_) => rtr.config({'path': '/user', 'component': UserCmp, 'as': 'user'}))
+        .then((_) => rtr.navigate('/a/b'))
+        .then((_) => {
+          view.detectChanges();
+          expect(DOM.getAttribute(view.rootNodes[0].childNodes[0], 'href')).toEqual('/my/base/user');
```
Comment (rkirov) [inline modules/angular2/test/router/outlet_spec.js]: This means every url is treated as absolute with respect to base path, for example here we ignore the current route `/a/b/`. This is no worse than currently, but I wonder if it is the long term behavior we want?

**Comment by rkirov** [comment]
LGTM, remove `Closes #1850` as it doesn't handle the router.navigate part.

**Comment by vicb** [comment]
please rebase on master to get Travis green
