### PR TITLE
fix(platform-server): fix get/set title for parse5 adapter

### LINKED ISSUE #14936: [platform-server]: Unable to set Title
**I'm submitting a ...**  
```
[x] bug report
```

**Current behavior**
When trying to `setTitle` using either the `Title` service (from platform-browser) or even trying to manually set it through the `DOCUMENT`, neither are able to actually change the `<title>` in the server-rendered View.

Code example:
```
  constructor(
    private title: Title,
    @Inject(DOCUMENT) private document
    ) {}

  ngAfterViewInit() {
      this.title.setTitle(`This doesn't work`);
      this.document.title = `This doesn't work either :(`;
  }
```

image

**Expected behavior**
In server-rendered view: `<title>Something got updated here</title>`

**Minimal reproduction of the problem with instructions**
https://github.com/MarkPieszak/ng-universal-demo/tree/title-bug
You can see in the [HomeComponent ](https://github.com/MarkPieszak/ng-universal-demo/blob/title-bug/src/app/home/home-view.component.ts#L29-L30)the code above trying to manipulate the Title 

**What is the motivation / use case for changing the behavior?**
Title update needed for SEO. `this.document.title = 'new title';` worked in previous angular2-universal.

* **Angular version:** 
4.0-rc2

* **Browser:** [all ]
 
* **Language:** [ TypeScript 2.2.1 ]

cc/ @vikerman @alxhub @gdi2290

### PR DESCRIPTION
**Pull request by FrozenPandaz**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

Fixes https://github.com/angular/angular/issues/14936

Currently, setting and getting the title on platform-server is broken and untested.

**What is the new behavior?**

Getting and setting the title will function and be tested

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by FrozenPandaz** [comment]
I'm planning a change which will cache the document's title the first time its retrieved so we dont have to query every time.

**Comment by DzmitryShylovich** [comment]
They are moving away from parse5 https://github.com/angular/angular/pull/14939

**Comment by FrozenPandaz** [comment]
@DzmitryShylovich It's an on going discussion

**Comment by vikerman** [comment]
Hey @DzmitryShylovich  - I've been in sync with @FrozenPandaz and asked him to submit this PR. The PR to move to jsdom is still experimental. We still have to figure out whether it is performant enough. Thanks.

File: modules/@angular/platform-server/src/parse5_adapter.ts [hunk 1]
```diff
@@ -592,6 +596,16 @@ export class Parse5DomAdapter extends DomAdapter {
   getCookie(name: string): string { throw new Error('not implemented'); }
   setCookie(name: string, value: string) { throw new Error('not implemented'); }
   animate(element: any, keyframes: any[], options: any): any { throw new Error('not implemented'); }
+  private getTitleNode(doc: any) {
+    let title = this.querySelector(doc, 'head title');
```
Comment (vikerman) [inline modules/@angular/platform-server/src/parse5_adapter.ts]: Can you just query doc.head for title?

File: modules/@angular/platform-server/src/parse5_adapter.ts [hunk 2]
```diff
@@ -592,6 +596,16 @@ export class Parse5DomAdapter extends DomAdapter {
...
+    if (title) {
+      return title;
+    }
+
+    title = this.createElement('title');
+    this.appendChild(this.querySelector(doc, 'head'), title);
```
Comment (vikerman) [inline modules/@angular/platform-server/src/parse5_adapter.ts]: doc.head should already be set to the head element

File: modules/@angular/platform-server/test/integration_spec.ts [hunk 3]
```diff
@@ -143,7 +143,21 @@ export function main() {
...
+        const platform = platformDynamicServer([{
+          provide: INITIAL_CONFIG,
+          useValue: { document: '<html><head></head><body><app></app></body></html>' }
+        }]);
+        platform.bootstrapModule(ExampleModule).then(ref => {
+          const doc = ref.injector.get(DOCUMENT);
+          getDOM().setTitle(doc, 'Test');
+          const title = getDOM().querySelector(doc, 'head title');
+          expect(title).toBeTruthy();
+          expect(getDOM().getText(title)).toContain('Test');
```
Comment (vikerman) [inline modules/@angular/platform-server/test/integration_spec.ts]: Can you make it stricter to .toBe('Test') ?

File: modules/@angular/platform-server/test/integration_spec.ts [hunk 4]
```diff
@@ -143,7 +143,21 @@ export function main() {
            expect(getDOM().getText(doc)).toEqual('Works too!');
            platform2.destroy();
          });
-       }));
+      }));
+
+    it('adds title to the document', async(() => {
```
Comment (vikerman) [inline modules/@angular/platform-server/test/integration_spec.ts]: Thanks for adding this integration test!

File: modules/@angular/platform-server/test/integration_spec.ts [hunk 5]
```diff
@@ -143,7 +143,21 @@ export function main() {
...
+          provide: INITIAL_CONFIG,
+          useValue: { document: '<html><head></head><body><app></app></body></html>' }
+        }]);
+        platform.bootstrapModule(ExampleModule).then(ref => {
+          const doc = ref.injector.get(DOCUMENT);
+          getDOM().setTitle(doc, 'Test');
+          const title = getDOM().querySelector(doc, 'head title');
+          expect(title).toBeTruthy();
+          expect(getDOM().getText(title)).toContain('Test');
+        });
```
Comment (vikerman) [inline modules/@angular/platform-server/test/integration_spec.ts]: For a more end to end check we should do a PlatformState.renderToString() and make sure the title is rendered

**Review by vikerman — CHANGES_REQUESTED** [review]
Please fix the commit message to fix(platform-server):...

File: modules/@angular/platform-server/test/integration_spec.ts (hunk 4 above)
Comment (FrozenPandaz) [inline modules/@angular/platform-server/test/integration_spec.ts]: Then it'll never happen again :)

File: modules/@angular/platform-server/src/parse5_adapter.ts (hunk 2 above)
Comment (FrozenPandaz) [inline modules/@angular/platform-server/src/parse5_adapter.ts]: I thought so too.. but i was having trouble.. i will double check

File: modules/@angular/platform-server/test/integration_spec.ts (hunk 5 above)
Comment (FrozenPandaz) [inline modules/@angular/platform-server/test/integration_spec.ts]: Good idea, i think i'll make it a separate it() so we know the difference

File: modules/@angular/platform-server/test/integration_spec.ts [hunk 6]
```diff
@@ -143,7 +143,21 @@ export function main() {
...
+      }));
+
+    it('adds title to the document', async(() => {
+        const platform = platformDynamicServer([{
+          provide: INITIAL_CONFIG,
+          useValue: { document: '<html><head></head><body><app></app></body></html>' }
+        }]);
+        platform.bootstrapModule(ExampleModule).then(ref => {
+          const doc = ref.injector.get(DOCUMENT);
+          getDOM().setTitle(doc, 'Test');
```
Comment (vikerman) [inline modules/@angular/platform-server/test/integration_spec.ts]: Please use the Title service in the test. That's how we want end users to set the title.

**Review by vikerman — CHANGES_REQUESTED** [review]

File: modules/@angular/platform-server/test/integration_spec.ts [hunk 7]
```diff
@@ -145,6 +155,33 @@ export function main() {
          });
        }));
 
+    it('adds title to the document', async(() => {
```
Comment (vikerman) [inline modules/@angular/platform-server/test/integration_spec.ts]: Can you remove this test? We just want to test public API in the integration test.

**Review by vikerman — APPROVED** [review]

File: modules/@angular/platform-server/src/parse5_adapter.ts [hunk 8]
```diff
@@ -30,7 +30,7 @@ function _notImplemented(methodName: string) {
 /**
  * Parses a document string to a Document object.
  */
-export function parseDocument(html: string) {
+export function parseDocument(html: string): Document {
```
Comment (vikerman) [inline modules/@angular/platform-server/src/parse5_adapter.ts]: Please leave the return type as any - since it's a parse5 Document and not the standard TS Document interface,

File: modules/@angular/platform-server/src/parse5_adapter.ts [hunk 9]
```diff
@@ -43,6 +43,7 @@ export function parseDocument(html: string) {
  * can introduce XSS risks.
  */
 export class Parse5DomAdapter extends DomAdapter {
+  private title: HTMLTitleElement;
```
Comment (vikerman) [inline modules/@angular/platform-server/src/parse5_adapter.ts]: Please leave the type of this as any - This is a parse5 Element and not an actual HTMLTitleElement.

**Review by vikerman — CHANGES_REQUESTED** [review]

**Review by vikerman — APPROVED** [review]

**Comment by chuckjaz** [comment]
This PR needs to be rebased.

**Comment by FrozenPandaz** [comment]
rebased

**Review by vikerman — APPROVED** [review]
