### PR TITLE
fix(compiler): ignore calls to unresolved symbols in metadata

### LINKED ISSUE #15969: language server: unresolved modules produce incorrect diagnostics.
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**

Referencing a module that cannot be resolved, such as `@angular/animations` when it isn't installed, results in an error messages "Cannot read 'name' of null'.

**Expected behavior**

Either no error or the correct error diagnostic such as '@angular/animations' cannot be resolved...'

### PR DESCRIPTION
**Pull request by chuckjaz**
This only shows up in the language service. Calls to symbols
that are not resolve resulted in null instead of being resolved
causing the language service to see exceptions when the null
was not expected such as in the animations array.

Fixes #15969

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
```

**What is the current behavior?** (You can also link to an open issue here)

The language service produces spurious errors as described in #15969

**What is the new behavior?**

The spurious errors are not generated.

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

### CODE REVIEW

File: packages/compiler/test/aot/static_reflector_spec.ts [hunk 1]
```diff
@@ -546,6 +546,30 @@ describe('StaticReflector', () => {
     expect(annotation.providers).toEqual([1, 2, 3, 4, 5, 6, 7]);
   });
 
+  it('should return result in an empty array to unresoled calls', () => {
```
Comment (vicb) [inline packages/compiler/test/aot/static_reflector_spec.ts]: is `'should return result in an empty array to unresoled calls'` right ?

**Review by vicb — APPROVED** [review]
1 nit

**Comment by tbosch** [comment]
This breaks G3, see the build errors in https://test.corp.google.com/ui#id=OCL:153180717:BASE:153180757:1492191111009:6d1dc760
