### PR TITLE
fix(di): allow `@Inject(…)` to work in dart2js and dynamic reflection

### LINKED ISSUE #2185: DI: using `@Inject(...)` without a type fails in dart2js when using mirrors
Given a class that does something like this (see e.g. `DomRenderer`):
```
var someToken = new OpaqueToken('test');
class SomeClass {
  constructor(@Inject(someToken) token) {}  
}
```

Using this class with DI fails with the following error in dart2js when using dynamic reflection (e.g. in hello_world/index_dynamic.html):
```
Unsupported operation: This type does not support reflectedType
    at dart.wrapException (http://localhost:8002/examples/src/key_events/index.dart.js:3781:15)
    at JsTypeMirror.dart.JsTypeMirror.get$reflectedType (http://localhost:8002/examples/src/key_events/index.dart.js:23991:15)
    at ReflectionCapabilities.dart.ReflectionCapabilities._convertParameter$1 (http://localhost:8002/examples/src/key_events/index.dart.js:85648:25)
    at eval (eval at <anonymous> (http://localhost:8002/examples/src/key_events/index.dart.js:5395:16), <anonymous>:2:38)
    at MappedListIterable.dart.MappedListIterable._f$1 (http://localhost:8002/examples/src/key_events/index.dart.js:22556:22)
```

### PR DESCRIPTION
**Pull request by tbosch**
Note: We can’t write a unit test for this as our unit tests
are running in Dartium, where the error does not occur.
However, we previously had a failure in our e2e tests
in `hello_world/index_dynamic.html`
when removing the TODOs in `application.ts`.

Closes #2185

### CODE REVIEW

File: modules/angular2/src/reflection/reflection_capabilities.dart [hunk 1]
```diff
@@ -57,8 +57,8 @@ class ReflectionCapabilities {
   }
 
   List _convertParameter(ParameterMirror p) {
-    var t = p.type.reflectedType;
-    var res = t == dynamic ? [] : [t];
+    var t = p.type;
+    var res = (!t.hasReflectedType || t.reflectedType == dynamic) ? [] : [t.reflectedType];
```
Comment (rkirov) [inline modules/angular2/src/reflection/reflection_capabilities.dart]: Yes, I ran across this bug before, thanks for fixing it!
