### PR TITLE
fix(change detection): preserve memoized results from pure functions

### LINKED ISSUE #2556: Generated Change Detectors do not properly handle pure functions
Fix handling pure functions and reenable change detectors:
https://github.com/angular/angular/blob/master/modules/angular2/src/core/application.ts#L72

Generated change detectors always reset the result of pure functions to undefined.

### PR DESCRIPTION
**Pull request by yjbanov**
Fixes https://github.com/angular/angular/issues/2556

### CODE REVIEW

File: modules/angular2/test/change_detection/change_detector_spec.ts [hunk 1]
```diff
@@ -304,6 +304,16 @@ export function main() {
         expect(val.dispatcher.log).toEqual(['propName=BvalueA']);
       });
 
+      describe('pure functions', () => {
+        it('should preserve memoized result', () => {
+          var person = new Person('bob');
+          var val = _createChangeDetector('passThrough([12])', person);
+          val.changeDetector.detectChanges();
+          val.changeDetector.detectChanges();
+          expect(val.dispatcher.loggedValues).toEqual([[12]]);
```
Comment (vicb) [inline modules/angular2/test/change_detection/change_detector_spec.ts]: `expect(ptInvocations).toEqual(1)` ?

Comment (vicb) [inline modules/angular2/test/change_detection/change_detector_spec.ts]: or maybe it would have been logged twice ?

Comment (yjbanov) [inline modules/angular2/test/change_detection/change_detector_spec.ts]: Two issues:

1. It would have been logged twice
2. The two values would be different, the second always being `null`/`undefined`
