### PR TITLE
fix(Compiler): add an error when a directive is null or undefined

### LINKED ISSUE #1908: Confusing error message when `directives` contains non-directive
If I have:
```js
@View({
  directives: [SomethingThatIsNotADirective]
})
```
The resulting error is `Cannot read property 'annotations' of undefined`, which is rather opaque.

It would be better if the compiler checks that the thing given is 1) defined / not null, and 2) is actually a `Directive` or `Component`.

### PR DESCRIPTION
**Pull request by vicb**
fixes #1908

@jelbourn seems like I've found the root cause now.

It occurs when a directive is null or undefined.

### CODE REVIEW

File: modules/angular2/src/core/compiler/compiler.js [hunk 1]
```diff
@@ -134,10 +134,21 @@ export class Compiler {
...
-    var directives = ListWrapper.map(
-      this._flattenDirectives(template),
-      (directive) => this._bindDirective(directive)
-    );
+
+    var directives;
+    try {
+      directives = ListWrapper.map(
+        this._flattenDirectives(template),
+        (directive) => this._bindDirective(directive)
```
Comment (jelbourn) [inline modules/angular2/src/core/compiler/compiler.js]: I don't think you need the parens around `directive` any more.

File: modules/angular2/src/core/compiler/compiler.js [hunk 2]
```diff
@@ -134,10 +134,21 @@ export class Compiler {
     if (isBlank(template)) {
       return null;
     }
-    var directives = ListWrapper.map(
-      this._flattenDirectives(template),
-      (directive) => this._bindDirective(directive)
-    );
+
+    var directives;
+    try {
```
Comment (jelbourn) [inline modules/angular2/src/core/compiler/compiler.js]: Is it possible to do this without a try-catch? Using this construct prevents V8 from doing optimizations. Not sure how hot this code is, thought.

@rkirov ?

Comment (vicb) [inline modules/angular2/src/core/compiler/compiler.js]: I can flatten the directives & do a scan after. Will update.

File: modules/angular2/src/core/compiler/compiler.js (hunk 1 above)
Comment (vicb) [inline modules/angular2/src/core/compiler/compiler.js]: I don't think this should be part of this PR.
A style PR that updates everywhere this applies would be more appropriate

**Comment by vicb** [comment]
@jelbourn I've updated the PR, please TAL

**Comment by jelbourn** [comment]
LGTM

**Comment by vicb** [comment]
@jelbourn thanks for the review, I'll merge when Travis is happy.
