### PR TITLE
fix(compiler): Ignore references to declared modules and unneeded types

### LINKED ISSUE #9670: ngc not working with static symbols used with Angular 1 code (ngUpgrade)
**I'm submitting a ...**
```
[x] bug report
```

**Current behavior**
I'm getting this error:

```
$ ./node_modules/.bin/ngc
Failed on type {"filePath":"/.../testApp/app/scripts/core/sectionhelp.component.ts","name":"SectionHelpComponent"} with error Error: Error encountered resolving symbol values statically. Qualified type names not supported (position 18:53 in the original .ts file), resolving symbol SectionHelpComponent in /.../testApp/app/scripts/core/section-help.component.ts
Error: Error encountered resolving symbol values statically. Qualified type names not supported (position 18:53 in the original .ts file), resolving symbol SectionHelpComponent in /.../testApp/app/scripts/core/section-help.component.ts
at simplifyInContext (/.../testApp/node_modules/@angular/compiler-cli/src/static_reflector.js:409:23)
at StaticReflector.simplify (/.../testApp/node_modules/@angular/compiler-cli/src/static_reflector.js:412:22)
at StaticReflector.parameters (/.../testApp/node_modules/@angular/compiler-cli/src/static_reflector.js:85:47)
at CompileMetadataResolver.getDependenciesMetadata (/.../testApp/node_modules/@angular/compiler/src/metadata_resolver.js:224:86)
at CompileMetadataResolver.getTypeMetadata (/.../testApp/node_modules/@angular/compiler/src/metadata_resolver.js:173:26)
at CompileMetadataResolver.getDirectiveMetadata (/.../testApp/node_modules/@angular/compiler/src/metadata_resolver.js:136:28)
at CompileMetadataResolver.maybeGetDirectiveMetadata (/.../testApp/node_modules/@angular/compiler/src/metadata_resolver.js:158:25)
at CodeGenerator.readComponents (/.../testApp/node_modules/@angular/compiler-cli/src/codegen.js:62:39)
at generateOneFile (/.../testApp/node_modules/@angular/compiler-cli/src/codegen.js:100:38)
at Array.map (native)
Compilation failed
```

On this code:

```ts
@Component({
    selector: 'section-help',
    templateUrl: 'scripts/core/section-help.component.html',
    directives: [CORE_DIRECTIVES],
    pipes: [TranslateNG1Pipe],
})
export class SectionHelpComponent implements OnInit {
    private language:string;
    private locationHash:string;
    private loading:boolean;
    private helpList:any[];
    private glossaryList:any[];

    constructor(@Inject('$timeout') private $timeout:ng.ITimeoutService,
                @Inject('$location') private $location:ng.ILocationService,
                private HelpService:HelpService) {
    }
```

If I remove the types from Angular 1 it successfully compiles using ```ngc```:

```ts
    constructor(@Inject('$timeout') private $timeout,
                @Inject('$location') private $location,
                private HelpService:HelpService) {
    }
```

This code works perfectly compiling using ```tsc``` in dynamic mode.

**Expected/desired behavior**
Be able to compile using Angular 1 types and custom interfaces.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
  
* **Language:** TypeScript 1.9

@alexeagle

### PR DESCRIPTION
**Pull request by chuckjaz**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-format
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

`ngc` produces errors when referencing AngularJs types in a DI location (such as constructor parameters) either as a global reference to `ng` or through an import. The first reports `Qualified reference not supported` and the second `can't find module "angular"`.

**What is the new behavior?**

Changed the collector to collect qualified references as a select on the function reference. If this happens to refer to an interface it is ignored by the static reflector.

Changed the static reflector and reflector host to not throw on modules it cannot map to files and to, instead, treat the module name as the canonical name. This prevents the static reflector from throwing for symbols it will not use anyway.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

**Other information**:

Fixes: #9670

### CODE REVIEW

File: modules/@angular/compiler-cli/src/reflector_host.ts [hunk 1]
```diff
@@ -174,10 +177,12 @@ export class ReflectorHost implements StaticReflectorHost, ImportGenerator {
...
   }
 
-  // TODO(alexeagle): take a statictype
   getMetadataFor(filePath: string): ModuleMetadata {
     if (!this.context.exists(filePath)) {
-      throw new Error(`No such file '${filePath}'`);
+      // If the file doesn't exists then we cannot return metadata for the file.
+      // This will occur if the user refernced a declared module for which no file
+      // exists for the module (i.e. jQuery or angularjs).
+      return undefined;
```
Comment (vicb) [inline modules/@angular/compiler-cli/src/reflector_host.ts]: return;

File: tools/@angular/tsc-wrapped/test/evaluator.spec.ts [hunk 2]
```diff
@@ -152,40 +152,43 @@ describe('Evaluator', () => {
     });
   });
 
-  it('should return errors for unsupported expressions', () => {
-    let errors = program.getSourceFile('errors.ts');
-    let aDecl = findVar(errors, 'a');
+  it('should support referene to a declared module type', () => {
+    let declared = program.getSourceFile('declared.ts');
+    let aDecl = findVar(declared, 'a');
```
Comment (vicb) [inline tools/@angular/tsc-wrapped/test/evaluator.spec.ts]: consts

**Comment by vicb** [comment]
LGTM. A couple of minor comments.
