### PR TITLE
fix(compiler): throw on invalid `in` expressions

### LINKED ISSUE #65244: Collision between expressions and template variable / class field
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

For expression, which can be a valid class field or template variable, a collision may occur when referencing it in a template, for example `in` or `typeof`.

If we create something like this:
```
@Component({
  template: `{{ in }}`
})
export class App {
  public in = 0;
}
```
`in` is treated as an expression instead of a class field. The solution, is to use `this.in`, then it refers to the field. Unfortunately, this cannot be applied to template variables. Maybe the compiler should handle these cases better and check if a collision can occur in a given context and display a better warning / error.

Bunus points :)
1. It seems that `in` does not require anything before or after itself, unlike `typeof` which requires something after itself, for example:
```ts
{{ typeof }} // NG5002: Parser Error: Unexpected end of expression:  typeof  at the end of the expression [ typeof ]
{{ typeof 'value' }} // OK - return 'string'
{{ in }} // OK - return string 'in', but should throw error
{{ 1 in values }} // OK
```
2. [The documentation](https://angular.dev/guide/templates/expression-syntax) is missing information about support for `in` and `typeof`, for example.

### Please provide a link to a minimal reproduction of the bug

_No response_

### Please provide the exception or error you saw

```true

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 20.3.10
Node: 20.19.1
Package Manager: npm 10.8.2
OS: linux x64
    

Angular: 20.3.12
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, router

Package                      Version
------------------------------------
@angular-devkit/architect    0.2003.10
@angular-devkit/core         20.3.10
@angular-devkit/schematics   20.3.10
@angular/build               20.3.10
@angular/cli                 20.3.10
@schematics/angular          20.3.10
rxjs                         7.8.2
typescript                   5.8.2
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by JeanMeche**
`{{in}}` are not interpreted as `'in'` string expressions anymore.

```
<input #in /> // OK
{{in}} // throws
```

fixes https://github.com/angular/angular/issues/65244

BREAKING CHANGE: `in` variables will throw in template expressions.

### CODE REVIEW

File: packages/compiler/src/expression_parser/parser.ts [hunk 1]
```diff
@@ -1127,7 +1127,7 @@ class _ParseAST {
     } else if (this.next.isKeywordFalse()) {
       this.advance();
       return new LiteralPrimitive(this.span(start), this.sourceSpan(start), false);
-    } else if (this.next.isKeywordIn()) {
+    } else if (this.next.isKeywordIn() && this.index > 0) {
```
Comment (JoostK) [inline packages/compiler/src/expression_parser/parser.ts]: I don't follow the rationale here, nor for the original code; why would `in` be tokenized as keyword, yet interpreted as string... string literals should be tokenized as-is, so keyword tokens shouldn't be parsed to string literals.

Making this conditional on token index makes this even weirder. Concretely, I don't expect multi-statement bindings in outputs to be handled correctly:

```html
<a (click)="in; in"></a>
```

Comment (JeanMeche) [reply packages/compiler/src/expression_parser/parser.ts]: Yes agreed, the parsing of the `in` operator needs to be reworked.

**Review by JoostK — APPROVED** [review]

**Comment by JeanMeche** [comment]
As expected this will require a g3 cleanup and is a breaking change. We'll have to wait for the next breaking change window.

**Comment by JeanMeche** [comment]
G3 has been cleaned up. 

[Green TGP](https://fusion2.corp.google.com/presubmit/833075775/OCL:833075775:BASE:874219617:1771881494625:31a559a5)

**Comment by thePunderWoman** [comment]
This PR was merged into the repository. The changes were merged into the following branches:

- main: 786ef8261f4faca0693ef73938d3a6275b5baf7f
