### PR TITLE
fix(migrations): inject migration not work in multi-project workspace…

### LINKED ISSUE #66074: Inject migration does not work in a multi-project workspace
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

In [multi-project workspace](https://angular.dev/reference/configs/file-structure#multiple-projects), the inject migration doesn't work when targeting one of the projects due to either not finding any files in other projects or considering them external thus it throws a `SchematicsException`

### Minimal Reproduction
1. Create a new workspace with Angular CLI
    a. `ng new my-workspace --no-create-application`
2. Generate a new application in the workspace
    a. `ng generate application my-app`
3. Generate a new library in the workspace
    a. `ng generate library my-lib`
4. Create a new service
5. Import service into generated component in `my-lib`
6. Run inject migration targeting the library
    a. `ng generate @angular/core:inject`

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-ap2u31fu

### Please provide the exception or error you saw

```true
`Could not find any files to migrate under the path \\home\\projects\\stackblitz-starters-ap2u31fu\\projects\\my-lib\\src. Cannot run the inject migration.`
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI       : 21.0.3
Angular           : 21.0.5
Node.js           : 20.19.1
Package Manager   : npm 10.8.2
Operating System  : linux x64

 
Package				Version
------------------------------------------------
@angular/build			 21.0.3
@angular/cli			 21.0.3
@angular/common			 21.0.5
@angular/compiler		 21.0.5
@angular/compiler-cli		 21.0.5
@angular/core			 21.0.5
@angular/forms			 21.0.5
@angular/platform-browser	 21.0.5
@angular/router			 21.0.5
ng-packagr			 21.0.0
rxjs				 7.8.2
typescript			 5.9.3
vitest				 4.0.15
```

### Anything else?

I couldn't find any information if this multi-project scenario are supported by migrations so I'm not sure if this is a bug or not.

One thing I noticed is that in the [source code](https://github.com/angular/angular/blob/main/packages/core/schematics/ng-generate/inject-migration/index.ts#L62) the exception is thrown if no files are found, so maybe a naïve fix could be just rendering a warning but continue to the next `tsconfig` file so that the whole migration process isn't interrupted (however it might still ignores due to the external library check)

### Alternatives considered
In a similar but now deprecated migration made by @eneajaho in the **ngxtension** project it contains a `--project` flag which could be a nice solution
https://ngxtension.dev/utilities/migrations/inject-migration/#options

### PR DESCRIPTION
**Pull request by aparzi**
Fix inject migration in multi-project workspace. The inject migration doesn't work when targeting one of the projects due to either not finding any files in other projects or considering them external thus it throws a SchematicsException

Fixes: #66074

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/contributing-docs/commit-message-guidelines.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.dev application / infrastructure changes
- [ ] Other... Please describe:

Issue Number: #66074

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

File: packages/core/schematics/test/inject_migration_spec.ts [hunk 1]
```diff
@@ -411,6 +411,76 @@ describe('inject migration', () => {
     ]);
   });
 
+  it('should not throw when --path matches files only in a later tsconfig', async () => {
```
Comment (JeanMeche) [inline packages/core/schematics/test/inject_migration_spec.ts]:
```suggestion
  it('should migrate files present in other workspace projects', async () => {
```

**Comment by aparzi** [comment]
Any news for this PR?

**Comment by aparzi** [comment]
Any news?

**Review by JeanMeche — APPROVED** [review]

**Comment by leonsenft** [comment]
This PR was merged into the repository. The changes were merged into the following branches:

- main: a73b4b7c30ae943966ad6deecf5a284cddb1f3fd
- 21.2.x: 73d6b01b47bb6762d182f1cd891f8ad4d7f688e1
