### PR TITLE
fix(compiler): ship &nbsp; when trimming / removing whitespaces

### LINKED ISSUE #19304: WhiteSpace in html
The text node in `<p>&nbsp</p>` will get removed. 
IMO it's a bug. 
Root cause `toText("&nbsp;").trim() == ""`.

Cause you please also check that `.replace(/\s\s+/g, ' ')` leaves `nbsp`s alone. 

Edit: `.replace(/\s\s+/g, ' ')` also has the same issue

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
Fixes #19304

The exact set of characters that we take into account is open to discussion.

### CODE REVIEW

**Review by jelbourn — APPROVED** [review]
LGTM, though Vic should still take a look

cc fyi @mmalerba

File: packages/compiler/src/ml_parser/html_whitespaces.ts [hunk 1]
```diff
@@ -14,6 +14,12 @@ export const PRESERVE_WS_ATTR_NAME = 'ngPreserveWhitespaces';
 
 const SKIP_WS_TRIM_TAGS = new Set(['pre', 'template', 'textarea', 'script', 'style']);
 
+// Equivalent to \s with \u00a0 (non-breaking space) excluded.
+// Based on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp
+const WS_CHARS = ' \f\n\r\t\v\u1680\u180e\u2000-\u200a\u2028\u2029\u202f\u205f\u3000\ufeff';
```
Comment (vicb) [inline packages/compiler/src/ml_parser/html_whitespaces.ts]: If not sure how useful the `\u1680\u180e\u2000-\u200a\u2028\u2029\u202f\u205f\u3000\ufeff` part is but it shouldn't hurt either

File: packages/compiler/src/ml_parser/html_whitespaces.ts [hunk 2]
```diff
@@ -14,6 +14,12 @@ export const PRESERVE_WS_ATTR_NAME = 'ngPreserveWhitespaces';
...
+const WS_DETECT_REGEXP = new RegExp(`[${WS_CHARS}]+`);
+const WS_REPLACE_REGEXP = new RegExp(`[${WS_CHARS}][${WS_CHARS}]+`, 'g');
```
Comment (vicb) [inline packages/compiler/src/ml_parser/html_whitespaces.ts]: may be `[${WS_CHARS}]{2,}`

File: packages/compiler/src/ml_parser/html_whitespaces.ts [hunk 3]
```diff
@@ -63,10 +69,11 @@ class WhitespaceVisitor implements html.Visitor {
   }
 
   visitText(text: html.Text, context: any): any {
-    const isBlank = text.value.trim().length === 0;
+    const isBlank = text.value.replace(WS_DETECT_REGEXP, '').length === 0;
```
Comment (vicb) [inline packages/compiler/src/ml_parser/html_whitespaces.ts]: testing for `[^WS_CHARS]` is probably more efficient (speed/memory)

File: packages/compiler/src/ml_parser/html_whitespaces.ts [hunk 4]
```diff
@@ -63,10 +69,11 @@ class WhitespaceVisitor implements html.Visitor {
...
 
     if (!isBlank) {
-      return new html.Text(replaceNgsp(text.value).replace(/\s\s+/g, ' '), text.sourceSpan);
+      return new html.Text(
+          replaceNgsp(text.value).replace(WS_REPLACE_REGEXP, ' '), text.sourceSpan);
```
Comment (vicb) [inline packages/compiler/src/ml_parser/html_whitespaces.ts]: collapse replaceNgsp & replace ? (ie include ngsp in the RegExp) ?

**Review by vicb — APPROVED** [review]
Added a few minor comments

File: packages/compiler/src/ml_parser/html_whitespaces.ts (hunk 1 above)
Comment (pkozlowski-opensource) [reply packages/compiler/src/ml_parser/html_whitespaces.ts]: Kept it for consistency with `\s`

File: packages/compiler/src/ml_parser/html_whitespaces.ts (hunk 3 above)
Comment (pkozlowski-opensource) [reply packages/compiler/src/ml_parser/html_whitespaces.ts]: Might be. Anyway, changed as suggested since it is more explicit / reads better. Thnx for the suggestion.

File: packages/compiler/src/ml_parser/html_whitespaces.ts (hunk 4 above)
Comment (pkozlowski-opensource) [reply packages/compiler/src/ml_parser/html_whitespaces.ts]: `replaceNgsp` is exported and needed in the template parser so I can't get rid of it. I could remove `replaceNgsp` _usage_ in this file but then we would have the same "logic" in places.

Given all this I prefer to keep it as-is.
