### PR TITLE
fix(service-worker): check for updates on navigation

### LINKED ISSUE #20877: Service Worker should check for updates on every navigation
Currently the SW checks for updates on cold starts. Cold starts are unpredictable. This technique is generally fine in production but makes it hard for developers to verify the update process.

The SW should instead always fetch `ngsw.json` on navigation.

### PR DESCRIPTION
**Pull request by alxhub**
Currently the Service Worker checks for updates only on SW startup,
an event which happens frequently but also nondeterministically. This
makes it hard for developers to observe the update process or reason
about how updates will be delivered to users. This problem is
exacerbated by the DevTools behavior of keeping the SW alive
indefinitely while opened, effectively preventing the page from
updating at all.

This change causes the SW to additionally check for updates on
navigation requests (app page reloads). This creates deterministic
update behavior, and is much easier for developers to reason about.
It does leave the old update-on-SW-startup behavior in place, as
removing that would be a breaking change.

Fixes #20877

### CODE REVIEW

File: packages/service-worker/worker/src/driver.ts [hunk 1]
```diff
@@ -327,6 +332,15 @@ export class Driver implements Debuggable, UpdateSource {
       return this.safeFetch(event.request);
     }
 
+    // On navigation requests, check for new updates.
+    if (event.request.mode === 'navigate' && !this.scheduledNavUpdateCheck) {
+      this.scheduledNavUpdateCheck = true;
+      this.idle.schedule('check-updates-on-navigation', async () => {
```
Comment (gkalpak) [inline packages/service-worker/worker/src/driver.ts]: clang-format complains about the space after `async` :grin:

File: packages/service-worker/worker/test/happy_spec.ts [hunk 2]
```diff
@@ -337,6 +337,41 @@ export function main() {
       serverUpdate.assertNoOtherRequests();
     });
 
+    async_it('checks for updates on navigation', async() => {
+      expect(await makeRequest(scope, '/foo.txt')).toEqual('this is foo');
+      await driver.initialized;
+      server.clearRequests();
+
+      expect(await makeRequest(scope, '/foo.txt', 'default', {
+        mode: 'navigate',
```
Comment (gkalpak) [inline packages/service-worker/worker/test/happy_spec.ts]: Might be worth checking that other modes do not trigger an update.

File: packages/service-worker/worker/test/happy_spec.ts [hunk 3]
```diff
@@ -337,6 +337,41 @@ export function main() {
...
+      })).toEqual('this is foo');
+
+      scope.advance(12000);
+      await driver.idle.empty;
+
+      server.assertSawRequestFor('ngsw.json');
+      server.assertNoOtherRequests();
```
Comment (gkalpak) [inline packages/service-worker/worker/test/happy_spec.ts]: AFAICT, `assertSawRequestFor()` will remove all requests for the specified URL, so this does not really test that only one request was made.

**Review by gkalpak — DISMISSED** [review]

File: packages/service-worker/worker/test/happy_spec.ts (hunk 3 above)
Comment (alxhub) [reply packages/service-worker/worker/test/happy_spec.ts]: Only the first match:

```
const matching = this.requests.filter(req => req.url.split('?')[0] === url);
    if (matching.length > 0) {
      this.requests = this.requests.filter(req => req !== matching[0]);
      return true;
    }
    return false;
```

Only one request will be removed because we look for `matching[0]` specifically. Lazy coding on my part, but it works :)

File: packages/service-worker/worker/test/happy_spec.ts (hunk 2 above)
Comment (alxhub) [reply packages/service-worker/worker/test/happy_spec.ts]: The other tests will essentially do that (via `assertNoOtherRequests` calls).

File: packages/service-worker/worker/src/driver.ts (hunk 1 above)
Comment (alxhub) [reply packages/service-worker/worker/src/driver.ts]: clang-format has been dealt with.

File: packages/service-worker/worker/test/happy_spec.ts (hunk 3 above)
Comment (gkalpak) [reply packages/service-worker/worker/test/happy_spec.ts]: Oh, right! I remember I initially fell for this when reviewing the orignal code :smiley:

**Review by gkalpak — APPROVED** [review]
