### PR TITLE
fix(router): only secondary top-level segments

### LINKED ISSUE #10017: Auxiliary routes don't work with an empty path
I wanted to have this:
```
[
      {path: '',        component: HomeComponent},
      {path: 'product', component: ProductDetailComponent},
      {path: 'chat', component: ChatComponent, outlet:"aux"}

    ]
```
and this:

```
        this.router.navigateByUrl("(aux:chat)");
```

But it gives me the error

Error: Uncaught (in promise): Error: Cannot match any routes: ''

I had to do this workaround:

```
[
      {path: '',  redirectTo: 'home', terminal:true},
      {path: 'home',        component: HomeComponent},
      {path: 'product', component: ProductDetailComponent},
      {path: 'chat', component: ChatComponent, outlet:"aux"}
    ]
```

and 

```
 this.router.navigateByUrl("home(aux:chat)");
```

I'd like to use auxiliary routes with the default routes without the need to use redirectTo.

### PR DESCRIPTION
**Pull request by vsavkin**
Closes #10017, #9935

### CODE REVIEW

File: modules/@angular/router/src/shared.ts [hunk 1]
```diff
@@ -12,7 +12,7 @@
  *
  * @experimental
  */
-export const PRIMARY_OUTLET = 'PRIMARY_OUTLET';
+export const PRIMARY_OUTLET = 'z';
```
Comment (robwormald) [inline modules/@angular/router/src/shared.ts]: curious - y u do this?

**Comment by robwormald** [comment]
lgtm :shipit:
