### PR TITLE
fix(zone.js): support passthrough of Promise.try API

### LINKED ISSUE #67057: (zone.js) Promise.try is undefined
### Which @angular/* package(s) are the source of the bug?

zone.js

### Is this a regression?

No

### Description

In 2025 the static method [`Promise.try`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/try) recieved wide support in browsers.

ZoneAwarePromise does not implement it.

### Please provide a link to a minimal reproduction of the bug

_No response_

### Please provide the exception or error you saw

```true
Uncaught TypeError: Promise.try is not a function
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI       : 21.1.4
Angular           : 21.1.4
Node.js           : 24.13.0
Package Manager   : pnpm 10.29.3
Operating System  : win32 x64

┌───────────────────────────────────┬───────────────────┬───────────────────┐
│ Package                           │ Installed Version │ Requested Version │
├───────────────────────────────────┼───────────────────┼───────────────────┤
│ @angular/animations               │ 21.1.4            │ ^21.1.4           │
│ @angular/build                    │ 21.1.4            │ ^21.1.4           │
│ @angular/cdk                      │ 21.1.4            │ ^21.1.4           │
│ @angular/cli                      │ 21.1.4            │ ~21.1.4           │
│ @angular/common                   │ 21.1.4            │ ^21.1.4           │
│ @angular/compiler                 │ 21.1.4            │ ^21.1.4           │
│ @angular/compiler-cli             │ 21.1.4            │ ^21.1.4           │
│ @angular/core                     │ 21.1.4            │ ^21.1.4           │
│ @angular/forms                    │ 21.1.4            │ ^21.1.4           │
│ @angular/language-service         │ 21.1.4            │ ^21.1.4           │
│ @angular/localize                 │ 21.1.4            │ ^21.1.4           │
│ @angular/material                 │ 21.1.4            │ ^21.1.4           │
│ @angular/material-moment-adapter  │ 21.1.4            │ ^21.1.4           │
│ @angular/platform-browser         │ 21.1.4            │ ^21.1.4           │
│ @angular/platform-browser-dynamic │ 21.1.4            │ ^21.1.4           │
│ @angular/router                   │ 21.1.4            │ ^21.1.4           │
│ @angular/youtube-player           │ 21.1.4            │ ^21.1.4           │
│ rxjs                              │ 7.8.2             │ ^7.8.2            │
│ typescript                        │ 5.9.3             │ ~5.9.3            │
│ zone.js                           │ 0.16.0            │ ~0.16.0           │
└───────────────────────────────────┴───────────────────┴───────────────────┘
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by atscott**
When Zone patches Promise, it uses ZoneAwarePromise. The new Promise.try API was undefined on ZoneAwarePromise, making it unavailable when zone was present. This change gracefully passes through Promise.try to the native Promise implementation, if available, without patching it to execute in the right zone (our stance is not to add new patches but avoid destructively making new APIs unavailable).

Fixes #67057

### CODE REVIEW

File: packages/zone.js/lib/common/promise.ts [hunk 1]
```diff
@@ -627,6 +627,10 @@ export function patchPromise(Zone: ZoneType): void {
 
     if (NativePromise) {
       patchThen(NativePromise);
+      const nativeTry = (NativePromise as any)['try'];
+      if (nativeTry && typeof nativeTry === 'function') {
+        (ZoneAwarePromise as any)['try'] = nativeTry;
+      }
```
Comment (dgp1130) [inline packages/zone.js/lib/common/promise.ts:634]: Consider: Would it be worth doing something more generic to propagate any unknown properties on `Promise` to `ZoneAwarePromise`?

That might be more effort than it's worth and comes with a performance cost, but could potentially mean any future additions don't require us to manually plumb through each property.

**Review by dgp1130 — APPROVED** [review]

File: packages/zone.js/lib/common/promise.ts (hunk 1 above)
Comment (atscott) [reply packages/zone.js/lib/common/promise.ts:634]: Added TODO

**Comment by mattrbeck** [comment]
This PR was merged into the repository. The changes were merged into the following branches:

- main: fc557f0276aefe523e328cad984eddb3ba7fecdb
- 21.1.x: 9c1ec6c93ef086650c241a9b42134465e0da7570
