### PR TITLE
fix(language-service): tolerate errors in decorators

### LINKED ISSUE #14631: `StaticReflector` elides annotations that contains errors
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**

The `StaticReflector` will not produce an attribute if the attribute declaration contains an error.

Root cause of https://github.com/angular/vscode-ng-language-service/issues/10 and probably several others.

**Expected behavior**

The `StaticReflector` should produce a partial value so that correct parts of, for example, an `NgModule` is not discarded.

**Minimal reproduction of the problem with instructions**

See https://github.com/angular/vscode-ng-language-service/issues/10

**What is the motivation / use case for changing the behavior?**

See https://github.com/angular/vscode-ng-language-service/issues/10

### PR DESCRIPTION
**Pull request by chuckjaz**
Fixes #14631

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
```

**What is the current behavior?** (You can also link to an open issue here)

Metadata errors caused the language service to produce strange cascading errors causing problems such as reported here: https://github.com/angular/vscode-ng-language-service/issues/10

**What is the new behavior?**

Metadata errors are reported and ignored.

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

### CODE REVIEW

File: modules/@angular/compiler/src/aot/static_reflector.ts [hunk 1]
```diff
@@ -335,7 +343,8 @@ export class StaticReflector implements ReflectorReader {
             if (value && (depth != 0 || value.__symbolic != 'error')) {
               const parameters: string[] = targetFunction['parameters'];
               const defaults: any[] = targetFunction.defaults;
-              args = args.map(arg => simplifyInContext(context, arg, depth + 1));
+              args = args.map(arg => simplifyInContext(context, arg, depth + 1))
+                         .map(arg => shouldIgnore(arg) ? undefined : arg);
```
Comment (alexeagle) [inline modules/@angular/compiler/src/aot/static_reflector.ts]: could it be filter() instead? where do the undefined values go?

File: modules/@angular/compiler/src/aot/static_reflector.ts [hunk 2]
```diff
@@ -18,6 +18,14 @@ const ANGULAR_CORE = '@angular/core';
 
 const HIDDEN_KEY = /^\$.*\$$/;
 
+const ignore = {
```
Comment (alexeagle) [inline modules/@angular/compiler/src/aot/static_reflector.ts]: opt: all caps?

File: modules/@angular/compiler/src/aot/static_reflector.ts [hunk 3]
```diff
@@ -529,7 +538,8 @@ export class StaticReflector implements ReflectorReader {
                   let converter = self.conversionMap.get(staticSymbol);
                   if (converter) {
                     const args =
-                        argExpressions.map(arg => simplifyInContext(context, arg, depth + 1));
+                        argExpressions.map(arg => simplifyInContext(context, arg, depth + 1))
+                            .map(arg => shouldIgnore(arg) ? undefined : arg);
```
Comment (alexeagle) [inline modules/@angular/compiler/src/aot/static_reflector.ts]: again

File: modules/@angular/compiler/test/aot/static_reflector_spec.ts [hunk 4]
```diff
@@ -492,6 +495,31 @@ describe('StaticReflector', () => {
...
+        @Component({
+          selector: 'tmp',
+          template: () => {},
+          providers: [1, 2, (() => {}), 3, !(() => {}), 4, 5, (() => {}) + (() => {}), 6, 7]
+        })
+        export class BadComponent {
+
+        }
+      `;
+    init(data, [], () => {}, {verboseInvalidExpression: true});
```
Comment (alexeagle) [inline modules/@angular/compiler/test/aot/static_reflector_spec.ts]: should there be a test for what happens with a Component with errors and `verboseInvalidExpression` is false?

**Review by alexeagle — APPROVED** [review]

File: modules/@angular/compiler/src/aot/static_reflector.ts (hunk 1 above)
Comment (chuckjaz) [inline modules/@angular/compiler/src/aot/static_reflector.ts]: No as that would change the argument order.  Imagine the call `a(1, () => {}, 2)`, I want the transformed into `a(1, undefined, 2)` not `a(1,2)`.

File: modules/@angular/compiler/src/aot/static_reflector.ts (hunk 3 above)
Comment (chuckjaz) [inline modules/@angular/compiler/src/aot/static_reflector.ts]: see above

File: modules/@angular/compiler/test/aot/static_reflector_spec.ts (hunk 4 above)
Comment (chuckjaz) [inline modules/@angular/compiler/test/aot/static_reflector_spec.ts]: Not in this case. There are tests elsewhere that test that. The only time we need to handle more than one error is the case where there is error reporter and `verboseInvalidExpressions` is `true`. Testing this with `verboseInvalidExpression` as `false` would simplify the expression to a single error node which is what the other tests are already testing.

**Review by mhevery — APPROVED** [review]
