### PR TITLE
fix(aio): use a special version of the TopBar if the screen is narrow

### LINKED ISSUE #16940: Remove or move "Docs" sidenav item from the list in the mobile view
screen shot 2017-05-22 at 2 56 01 pm

The "Docs" item is already expanded under all the marketing menu items, so it's not necessary to list it there. Can we remove it? Or should we move it to be the last in the list of marketing pages and add a colon or something to suggest that the items under are the docs menu subitems?

### PR DESCRIPTION
**Pull request by petebacondarwin**
If there is a `TopBarNarrow` nav view then use this when the screen is narrow.
Otherwise just use the normal `TopBar`.

This commit also creates such a narrow topbar view where the "Docs" item is
in a different position

Closes #16940

### CODE REVIEW

File: aio/src/app/app.component.ts [hunk 1]
```diff
@@ -161,6 +162,7 @@ export class AppComponent implements OnInit {
       this.footerNodes  = views['Footer']  || [];
       this.sideNavNodes = views['SideNav'] || [];
       this.topMenuNodes = views['TopBar']  || [];
+      this.topMenuNarrowNodes = views['TopBarNarrow']  || this.topMenuNodes;
```
Comment (gkalpak) [inline aio/src/app/app.component.ts]: Unnecessary double space before `||`.

File: aio/content/navigation.json [hunk 2]
```diff
@@ -18,6 +18,25 @@
...
+      "url": "resources",
+      "title": "Resources"
+    },
+    {
+      "url": "events",
+      "title": "Events"
+    },
+    {
+      "url": "docs",
+      "title": "Docs:"
```
Comment (gkalpak) [inline aio/content/navigation.json]: Given that this has its own page (i.e. it is a clickable link), I find it weird tht is has `:` at the end.
I would prefer it without the `:`, but don't feel strongly about it :grin:

**Review by gkalpak — APPROVED** [review]

File: aio/content/navigation.json (hunk 2 above)
Comment (petebacondarwin) [inline aio/content/navigation.json]: It was @IgorMinar's suggestion.

Comment (gkalpak) [inline aio/content/navigation.json]: I know. But still 😉 
<sub>(Let me remind you, he also suggested red arrows 😛)</sub>
