### PR TITLE
fix(aio): do not nav to an image url

### LINKED ISSUE #16608: aio: clicking on links to assets fails with 404
Our click interceptor needs to be cleverer to realise that clicks on links such as:

```
<a href="generated/images/guide/aot-compiler/toh-pt6-bundle.png" title="View larger image">
```

Are not pages and so should allow the browser to handle it.

See the bottom of the page at http://localhost:4200/guide/aot-compiler#inspect-the-bundle

### PR DESCRIPTION
**Pull request by wardbell**
closes #16608
Formerly, tried to navigate when user clicked an anchor with an image url (to view image in a new tab) resulting in 404.
Now ignores href URL with any extension and lets browser handle it.
Affects `LocationService` whose tests have also been refactored for clarity.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]

**Comment by wardbell** [comment]
Subsequent to @petebacondarwin approval, after discussion, the rule changed from "ignore any extension except `.html`" to "ignore any extension".  Updated initial comment accordingly.

File: aio/src/app/app.component.ts [hunk 1]
```diff
@@ -183,8 +183,8 @@ export class AppComponent implements OnInit {
     while (target && !(target instanceof HTMLAnchorElement)) {
       target = target.parentElement;
     }
-    if (target) {
-      return this.locationService.handleAnchorClick(target as HTMLAnchorElement, button, ctrlKey, metaKey);
+    if (target instanceof HTMLAnchorElement) {
```
Comment (gkalpak) [inline aio/src/app/app.component.ts]: The `instanceof HTMLAnchorElement` part is redundant. [Rings any bells][1]? 😛 

[1]: https://github.com/angular/angular/pull/16131#discussion_r112145564

File: aio/src/app/shared/location.service.ts [hunk 2]
```diff
@@ -87,6 +87,14 @@ export class LocationService {
   }
 
   /**
+   * Handle user's anchor click
+   *
+   * @param anchor {HTMLAnchorElement} - the anchor element clicked
+   * @param button Number of the mouse button held down. 0 means left or none
+   * @param ctrlKey True if control key held down
+   * @param metaKey True if command or window key held down
+   * @return false if service navigated with`go()`; true if browser should handle it.
```
Comment (gkalpak) [inline aio/src/app/shared/location.service.ts]: _with\`go()\`_ --> _with \`go()\`_ (missing whitespace)

**Review by gkalpak — APPROVED** [review]

**Comment by mhevery** [comment]
@wardbell the CI is red. can you have a look?

**Comment by petebacondarwin** [comment]
@wardbell linting issues

File: aio/src/app/app.component.ts (hunk 1 above)
Comment (wardbell) [inline aio/src/app/app.component.ts]: Not this time @gkalpak. Notice that I moved from `target as HTMLAnchorElement` in next line to here, `if (target instanceof HTMLAnchorElement)`.  **TS insists on one or the other** (you don't need both). Because I was messing with `target` inside the `if` for a while, moving it up  was helpful.  Now it doesn't matter but I left it there for posterity.

**Comment by wardbell** [comment]
Yup. Fixed and re-running CI
