### PR TITLE
test(core): update ErrorHandler tests to handle browsers without stack

### LINKED ISSUE #11114: [Test/IE9] IE9 test are failing
@mlaval had managed to have all tests green (:+1:) but IE9 tests are broken again.

Seems like this is due to #11059

### PR DESCRIPTION
**Pull request by marclaval**
This PR updates the ErrorHandler tests so that they take into account the case where there is no stacktrace in the browser.

Fixes #11114

### CODE REVIEW

File: modules/@angular/core/test/error_handler_spec.ts [hunk 1]
```diff
@@ -48,8 +48,10 @@ export function main() {
     it('should output stackTrace', () => {
       var error = new Error('message!');
       var stack = getStack(error);
-      var e = errorToString(error);
-      expect(e).toContain(stack);
+      if (stack) {
+        var e = errorToString(error);
```
Comment (vicb) [inline modules/@angular/core/test/error_handler_spec.ts]: LGTM but please use `const` whenever updating code.
