### PR TITLE
fix(language-service): do not throw for invalid metadata

### LINKED ISSUE #13255: Language service throws when component metadata is invalid
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**

The language service will sometimes throw if metadata is invalid.

**Expected behavior**

It should report a diagnostic but not throw.

**Minimal reproduction of the problem with instructions**

Include the following in some project with the language service enabled.

```ts
@NgModule({declarations: [SomeComponent]} export class SomeModule {}
class SomeComponent {}
```

**Work around**

If the class is exported the language service will no longer throw.

### PR DESCRIPTION
**Pull request by chuckjaz**
**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
```

**What is the current behavior?** (You can also link to an open issue here)

The language service will sometimes throw with invalid metadata.

#13255

**What is the new behavior?**

The language service no longer throws.

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

**Other information**:

Fixes #13255

### CODE REVIEW

File: modules/@angular/compiler/src/metadata_resolver.ts [hunk 1]
```diff
@@ -372,29 +383,37 @@ export class CompileMetadataResolver {
...
+            return;
           }
           importedModules.push(importedModuleSummary);
         } else {
-          throw new Error(
-              `Unexpected value '${stringify(importedType)}' imported by the module '${stringify(moduleType)}'`);
+          this._reportError(
+              new Error(
+                  `Unexpected value '${stringify(importedType)}' imported by the module '${stringify(moduleType)}'`),
+              moduleType);
```
Comment (vicb) [inline modules/@angular/compiler/src/metadata_resolver.ts]: `return` ? (in case some code is added below)

File: modules/@angular/compiler/src/metadata_resolver.ts [hunk 2]
```diff
@@ -459,14 +487,16 @@ export class CompileMetadataResolver {
...
-      const typeMetadata = flattenAndDedupeArray(meta.bootstrap).map(type => {
+      flattenAndDedupeArray(meta.bootstrap).forEach(type => {
         if (!isValidType(type)) {
-          throw new Error(
-              `Unexpected value '${stringify(type)}' used in the bootstrap property of module '${stringify(moduleType)}'`);
+          this._reportError(
+              new Error(
+                  `Unexpected value '${stringify(type)}' used in the bootstrap property of module '${stringify(moduleType)}'`),
+              moduleType);
+          return;
```
Comment (vicb) [inline modules/@angular/compiler/src/metadata_resolver.ts]: inside a `forEach`

**Comment by vicb** [comment]
LGTM with a few minor comments

File: modules/@angular/compiler/src/metadata_resolver.ts (hunk 2 above)
Comment (vicb) [inline modules/@angular/compiler/src/metadata_resolver.ts]: Yep seen that after (I first thought you wanted to break the loop)

**Comment by alxhub** [comment]
Hi @chuckjaz,

Can you rebase?
