### PR TITLE
fix(compiler-cli): don't rewrite imports when annotating for closure

### LINKED ISSUE #19026: Angular v5 compiler rewrites imports
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
</code></pre>

## Current behavior

I'm using TypeScript `paths` to define a sub-module in my repo:
```json
{
    "compilerOptions": {
        "baseUrl": ".",
        "rootDir": ".",
        "paths": {
            "@my-org/my-sub-module": [
                "./src/my-sub-module/public_api.ts"
            ]
        }
    }
}
```

Then in a `.ts` file I use the import:
```typescript
import {some_class} from '@my-org/my-sub-module';
```

When I compile using NGC it resolves the imports correctly, but sometimes replaces it with relative path in the output files:
```javascript
import { some_class } from "./../my-sub-module/public_api";
```

This is fine for base usage, but once I try to use rollup to bundle packages based on the `paths` it will try to include files that do not belong to my sub-module. The roots in `paths` are passed into `external` option of rollup. But these do not match the rewritten paths anymore...

The code was working fine in Angular **4.3.x.**

## Expected behavior
The imports are never replaced with relative paths. 

## Minimal reproduction of the problem with instructions
Can't find any pattern for which the imports are modified. It seems to be that they are changed once the relative path is shorter then the name in `paths`(?)...

## Environment
<pre><code>Angular version: 5.0.0-beta.6
TypeScript: 2.3.4
</code></pre>

### PR DESCRIPTION
**Pull request by chuckjaz**
Closure no longer needs to have the imports rewritten avoid rewriting
as this can cause issues when the source directory structure differs
from what is deployed.

Fixes: #19026

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
```

## What is the current behavior?

Issue Number:  #19026 

Tsickle import rewriting is no longer needed and can often cause issues for other tools and no longer match the deployed source structure.

## What is the new behavior?

The imports are no longer rewritten for closure as closure no longer requires it.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

File: packages/compiler-cli/test/ngc_spec.ts [hunk 1]
```diff
@@ -507,6 +507,43 @@ describe('ngc transformer command-line', () => {
       });
     });
 
+    it('should not rewrite imports', () => {
```
Comment (tbosch) [inline packages/compiler-cli/test/ngc_spec.ts]: maybe add `when annotating with closure`?

**Review by tbosch — APPROVED** [review]
