### PR TITLE
fix(animations): always cleanup players after they have finished internally

### LINKED ISSUE #13333: Previous animation styles are accidentally collected
With the recent changes to how animations are run, if a previous animation has run then it's styles will always be included into the next animation.

### PR DESCRIPTION
**Pull request by matsko**
Closes #13333
Closes #13334

cc @kara

### CODE REVIEW

File: modules/@angular/core/src/animation/view_animation_map.ts [hunk 1]
```diff
@@ -44,10 +44,11 @@ export class ViewAnimationMap {
 
   getAllPlayers(): AnimationPlayer[] { return this._allPlayers; }
 
-  remove(element: any, animationName: string): void {
+  remove(element: any, animationName: string, targetPlayer: AnimationPlayer = null): void {
     const playersByAnimation = this._map.get(element);
     if (playersByAnimation) {
       const player = playersByAnimation[animationName];
+      if (targetPlayer && player !== targetPlayer) return;
```
Comment (matsko) [inline modules/@angular/core/src/animation/view_animation_map.ts]: use a branch for this `if`

**Comment by matsko** [comment]
Reviewed in person with @tbosch
