### PR TITLE
fix(core): debug data causing memory leak for root effects

### LINKED ISSUE #65265: Root effects leak memory in dev mode
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

_No response_

### Description

I am using the first demo from https://material.angular.dev/cdk/scrolling/overview.
When you conditionally show and hide the scroll viewport, it is not correctly removed by the garbage collector.

Image

Seems somehow connected to: 
https://github.com/angular/components/blob/main/src/cdk/scrolling/virtual-scroll-viewport.ts#L214

Is this still bound to the application refs effects scheduler?

### Reproduction

StackBlitz link: https://stackblitz.com/edit/stackblitz-starters-luexm4f1?file=src%2Fmain.ts
Steps to reproduce:
1.  Click the toggle button
2. open the dev tools and create a snapshot of the heap
3.  look for "cdk-virtual-scroll-viewport"
4. its detached and retained

### Expected Behavior

After removal from the dom, the cdk-virtual-scroll-viewport should not be retained in memory.

### Actual Behavior

After removal from the dom, the cdk-virtual-scroll-viewport is retained as detached in memory.

### Environment

 ng version

Angular CLI: 20.3.9
Node: 20.19.1
Package Manager: npm 10.8.2
OS: linux x64
    

Angular: 20.3.10
... common, compiler, compiler-cli, core, forms
... platform-browser, router

Package                      Version
------------------------------------
@angular-devkit/architect    0.2003.9
@angular-devkit/core         20.3.9
@angular-devkit/schematics   20.3.9
@angular/build               20.3.9
@angular/cdk                 20.2.12
@angular/cli                 20.3.9
@schematics/angular          20.3.9
rxjs                         7.8.2
typescript                   5.9.3
zone.js                      0.15.1

Image

### PR DESCRIPTION
**Pull request by crisbeto**
We track all effects that are created for debugging purposes in the `resolverToEffects` map. This ends up leaking memory for effects registered on long-living resolvers (e.g. on the root injector), because they stay in the array, even if the effect itself has been destroyed.

These changes add a callback to clean up the references.

Fixes #65265.

### CODE REVIEW

File: packages/core/src/render3/reactivity/effect.ts [hunk 1]
```diff
@@ -210,7 +209,7 @@ export const EFFECT_NODE: Omit<EffectNode, 'fn' | 'destroy' | 'injector' | 'noti
     ...BASE_EFFECT_NODE,
     cleanupFns: undefined,
     zone: null,
-    onDestroyFn: noop,
+    onDestroyFns: [],
```
Comment (crisbeto) [inline packages/core/src/render3/reactivity/effect.ts]: I'm not a fan of having to turn this into an array, but the alternative would be to do something like this in the debug data code which feels a bit hacky:

```
const originalOnDestroy = node.onDestroyFn;

node.onDestroyFn = () => {
 cleanupDebugData();
 originalOnDestroy();
};
```

Comment (alxhub) [reply packages/core/src/render3/reactivity/effect.ts]: This object is the prototype for all `EFFECT_NODE` instances. We shouldn't have an `Array` here as that'll get shared across all effect instances. Instead, this needs to be `undefined` or `null` and lazily initialized before pushing to it (or replaced, as you do).

Comment (crisbeto) [reply packages/core/src/render3/reactivity/effect.ts]: oops, good catch. Switched it to `null`.

**Review by thePunderWoman — APPROVED** [review]
LGTM

**Comment by kirjs** [comment]
This PR was merged into the repository. The changes were merged into the following branches:

- main: ca6ab6c91405987684a0249d00fb4d16ae83ce4b
- 21.0.x: 70507b8c1ce733b8232a12fa45037ee219b5b102
