### PR TITLE
fix(router): make router links work on non-a tags

### LINKED ISSUE #8357: alt_router: support routerLink on other elements then anchors
**Steps to reproduce and a minimal demo of the problem**

The new implementation of `RouterLink` currently only supports `<a>` tags. Using the directive on a `div` leads to the following exception:

```html
<div [routerLink]="['/tasks','edit', task.id]" class="fade-in task-list-entry">
  ...
</div>
```

```
Template parse errors:
Can't bind to 'href' since it isn't a known native property ("[ERROR ->]<div [routerLink]="['/tasks','edit', task.id]" class="fade-in task-list-entry" [ngClass]="{selected :"): ...
```

**Expected/desired behavior**

RouterLink should also work on `<div>`-Elements

**Other information**

### PR DESCRIPTION
**Pull request by vsavkin**
Closes #8357, #9471, #9665

### CODE REVIEW

File: modules/@angular/router/src/directives/router_link.ts [hunk 1]
```diff
@@ -54,8 +54,54 @@ import {UrlTree} from '../url_tree';
...
+   * @internal
+   */
+  constructor(
+      private router: Router, private route: ActivatedRoute,
+      private locationStrategy: LocationStrategy) {}
+
+  @Input()
+  set routerLink(data: any[]|string) {
+    if (Array.isArray(data)) {
+      this.commands = <any>data;
```
Comment (vicb) [inline modules/@angular/router/src/directives/router_link.ts]: unneeded cast ?

File: modules/@angular/router/src/directives/router_link.ts [hunk 2]
```diff
@@ -54,8 +54,54 @@ import {UrlTree} from '../url_tree';
...
+    }
+  }
+
+  @HostListener('click', ['$event.button', '$event.ctrlKey', '$event.metaKey'])
+  onClick(button: number, ctrlKey: boolean, metaKey: boolean): boolean {
+    if (button !== 0 || ctrlKey || metaKey) {
+      return true;
+    }
+
+    if (typeof this.target === 'string' && this.target != '_self') {
```
Comment (vicb) [inline modules/@angular/router/src/directives/router_link.ts]: Do we want this behavior for non a ?

**Comment by vicb** [comment]
lgtm with 1 q
