### PR TITLE
fix(Headers): deep copy for constructor using existing Headers

### LINKED ISSUE #6845: http Headers (copy) constructor
In case: ` if (headers instanceof Headers)`
Headers (copy) constructor creates only the shallow copy of the given Headers.
```typescript
 constructor(headers?: Headers | {[key: string]: any}) {
    if (headers instanceof Headers) {
      this._headersMap = (<Headers>headers)._headersMap;
      return;
    }

    this._headersMap = new Map<string, string[]>();

    if (isBlank(headers)) {
      return;
    }

    // headers instanceof StringMap
    StringMapWrapper.forEach(
        headers, (v, k) => { this._headersMap.set(k, isListLikeIterable(v) ? v : [v]); });
  }
```

It should deep copy the `headers`.

Version: angular-2.0.0-beta.2

### PR DESCRIPTION
**Pull request by marcuskrahl**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-format
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

The headersMap of a new Headers object is a reference to the headersMap of an existing Headers object if the Headers object is specified in the constructor. Therefore header values which are added to the new Headers object are also added to the existing Headers object (see [#6845](https://github.com/angular/angular/issues/6845))

**What is the new behavior?**

When creating a new Headers object by passing an existing Headers object the underlying headersMap is now cloned. That also means that the existing Headers object is not altered when adding values to a Headers object which is based on it.
This behavior is in accordance with the [spec](https://fetch.spec.whatwg.org/#concept-headers-fill)

**Does this PR introduce a breaking change?** (check one with "x")

```
[x] Yes
[ ] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: 
Breaks existing code which relies on the fact that Headers objects remain linked when based on each other. Since this is not in accordance with the spec the impact should be minimal.

**Other information**:

When creating a new Headers object using an existing Headers object
the existing Headers map is copied by reference. Therefore adding a
new Header value to the new Headers object also added this value to
the existing Headers object which is not in accordance with the
spec.
This commit alters the constructor to create a deep copy of existing
Headers maps and therefore unlink existing Headers from new Headers.

Closes #6845
BREAKING CHANGE: any code which relies on the fact that a newly
created Headers object is referencing an existing Headers map is
now broken, but that should normally not be the case since this
behavior is not documented and not in accordance with the spec.

### CODE REVIEW

File: modules/@angular/http/test/headers_spec.ts [hunk 1]
```diff
@@ -42,6 +42,13 @@ export function main() {
         expect(headers.get('foo')).toBe('bar');
         expect(headers.getAll('foo')).toEqual(['bar']);
       });
+      it('should not alter the values of a provided header template', () => {
+        // Spec at https://fetch.spec.whatwg.org/#concept-headers-fill
+        var firstHeaders = new Headers();
```
Comment (vicb) [inline modules/@angular/http/test/headers_spec.ts]: var -> const

File: modules/@angular/http/test/headers_spec.ts [hunk 2]
```diff
@@ -42,6 +42,13 @@ export function main() {
         expect(headers.get('foo')).toBe('bar');
         expect(headers.getAll('foo')).toEqual(['bar']);
       });
+      it('should not alter the values of a provided header template', () => {
```
Comment (vicb) [inline modules/@angular/http/test/headers_spec.ts]: please add a comment with a link to the GH issue

**Comment by marcuskrahl** [comment]
The changes should be fine to merge
