### PR TITLE
fix(core): fix memory leak with event replay

### LINKED ISSUE #59261: Event replay memory leak
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Elements are not being garbage collected properly when the app is destroyed because they are captured inside the early event contract event info list. When calling `appRef.destroy()`, we can capture the heap snapshot and observe the detached `<app-root />`, which cannot be garbage collected:

Image

### Please provide a link to a minimal reproduction of the bug

https://github.com/arturovt/ng-issue-event-replay-leak

### Please provide the exception or error you saw

Elements are captured in that part of the code:

https://github.com/angular/angular/blob/2c3630aafdf0f375e1e5fc45f9068a274b46b7c7/packages/core/primitives/event-dispatch/src/earlyeventcontract.ts#L69-L83

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 19.0.4
Node: 20.11.1
Package Manager: yarn 1.22.22
OS: linux x64

Angular: 19.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.4
@angular-devkit/build-angular   19.0.4
@angular-devkit/core            19.0.4
@angular-devkit/schematics      19.0.4
@schematics/angular             19.0.4
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by thePunderWoman**
This ensures event replay does not hold on to elements after an application has been destroyed.

fixes: #59261

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: packages/core/src/hydration/event_replay.ts [hunk 1]
```diff
@@ -294,24 +292,26 @@ function hydrateAndInvokeBlockListeners(
   injector: Injector,
   event: Event,
   currentTarget: Element,
+  queue: EventReplayQueue,
```
Comment (AndrewKushnir) [inline packages/core/src/hydration/event_replay.ts]: nit: since we have access to the injector, we can inject the queue inside of the function (no need to pass it as an argument).

File: packages/core/src/hydration/event_replay.ts [hunk 2]
```diff
@@ -294,24 +292,26 @@ function hydrateAndInvokeBlockListeners(
...
 ) {
-  blockEventQueue.push({event, currentTarget});
-  triggerHydrationFromBlockName(injector, blockName, replayQueuedBlockEvents);
+  queue.push({event, currentTarget});
+  triggerHydrationFromBlockName(injector, blockName, replayQueuedBlockEvents(queue));
```
Comment (AndrewKushnir) [inline packages/core/src/hydration/event_replay.ts]: nit: it'd be great to rename the function to match its new behavior:
```suggestion
  triggerHydrationFromBlockName(injector, blockName, createReplayQueuedBlockEventsFn(queue));
```

**Review by AndrewKushnir — APPROVED** [review]

File: packages/core/src/hydration/event_replay.ts (hunk 1 above)
Comment (thePunderWoman) [reply packages/core/src/hydration/event_replay.ts]: Ah good catch. Updated.

File: packages/core/src/hydration/event_replay.ts (hunk 2 above)
Comment (thePunderWoman) [reply packages/core/src/hydration/event_replay.ts]: Updated!

**Comment by thePunderWoman** [comment]
This PR was merged into the repository. The changes were merged into the following branches:

- main: 30e9c62bdfb8af73c24833473bd4492869538d2d
- 21.0.x: a6a2621bf9df02584e4079f4a804278fc2060a9c
