### PR TITLE
fix(language-service): initialize static reflector correctly

### LINKED ISSUE #15768: language service: using `else` in an `ngIf` can cause the language service to crash
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**

https://github.com/angular/vscode-ng-language-service/issues/61

The language service does not install the static reflector correctly causing potential crashes.

**Expected behavior**

No crash.

**Minimal reproduction of the problem with instructions**

See https://github.com/angular/vscode-ng-language-service/issues/61

### PR DESCRIPTION
**Pull request by chuckjaz**
Fixes #15768

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
```

**What is the current behavior?** (You can also link to an open issue here)

#15768 

**What is the new behavior?**

Using `else` no longer causes the language service to crash.

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

### CODE REVIEW

File: packages/language-service/test/diagnostics_spec.ts [hunk 1]
```diff
@@ -201,6 +201,23 @@ describe('diagnostics', () => {
...
     });
 
+    // Issue #15768
+    it('should be able to parse a template reference', () => {
+      addCode(
+          `
+        @Component({
+          selector: 'my-component',
+          template: \`
+            <div *ngIf="comps | async; let comps; else loading">
```
Comment (vicb) [inline packages/language-service/test/diagnostics_spec.ts]: `"false; else loading"` ? (keep it as simple as it the test needs)

**Review by vicb — APPROVED** [review]

File: packages/language-service/test/diagnostics_spec.ts (hunk 1 above)
Comment (chuckjaz) [inline packages/language-service/test/diagnostics_spec.ts]: Since this is a regression I want it to match the original report.
