### PR TITLE
fix(compiler): Missing metadata files should result in undefined

### LINKED ISSUE #9678: Metadata extractor fails when encountering a d.ts generated from a source file that uses a custom decorator
When the metadata extractor encounters a custom decorator, it includes the information for that symbol in the `.metadata.json` file. Typescript, however, does not include an import for that symbol in the `.d.ts` file because it is not necessary. This disconnect causes the metadata extractor (when run on a downstream app) to fail because the symbol for the module is not included in the program.

This can be worked-around by manually adding the missing `.d.ts` file to the `files` list in the `tsconfig.json`, but this is rather hacky.

### PR DESCRIPTION
**Pull request by chuckjaz**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-format
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

`ngc` throws an exception complaining about the file not being `in the program` when a module is referenced in metadata but the collector did not produce metadata for it. This error is misleading and unnecessary as it doesn't need to find `.d.ts`.

**What is the new behavior?**

The ReflectorHost now produces `undefined` in these cases allowing the `StaticReflector` to produce a more meaningful error message or ignore it (as in should have in #9678).

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

**Other information**:

RelectorHost threw an exception when metadata was requested for a
.d.ts file that didn't have a .metadata.json file.  Changed it to
return undefined.

Fixes #9678

### CODE REVIEW

File: modules/@angular/compiler-cli/src/reflector_host.ts [hunk 1]
```diff
@@ -184,14 +184,13 @@ export class ReflectorHost implements StaticReflectorHost, ImportGenerator {
       if (this.context.exists(metadataPath)) {
         return this.readMetadata(metadataPath);
       }
+    } else {
+      let sf = this.program.getSourceFile(filePath);
```
Comment (vicb) [inline modules/@angular/compiler-cli/src/reflector_host.ts]: const
