### PR TITLE
fix(views): remove dynamic component views, free host views, free emb…

### LINKED ISSUE #2339: `DynamicComponentLoader.loadIntoExistingLocation` should create a host element
Right now, Angular has 2 ways of loading dynamic components:

1. Using a `@Component` that does not have a view and dynamically loads another component onto the same element including the view of that component
2. Using a regular `@Directive` that creates a host view via a `ViewContainer` (i.e. a View that contains the host element of the component)

Option 1) has the following downsides:

- it allows having 2 component instances on the same element, including possible 2 app injectors on it, which can have unexpected corner cases. It can also lead to a component without a view at all.
- it does not handle animations, as we can't animate adding a shadow root. I.e. if a user wants to use option 1) + animations, he needs to use a `ViewContainer` any ways
- the only customer (GT) for which we designed it actually needs the host element

We should change option 1) into also creating a host view but inserting it as a child of a given `ElementRef`.

Note that this would also allow to remove 1 method from the `Compiler`, leaving only one public method.

### LINKED ISSUE #2472: DynamicComponentLoader.loadIntoNewLocation: Should be usable with any ElementRef ...
not just with a component's `ElementRef`.

For example:

```dart
@Directive()
class ReferenceDirective {
  ReferenceDirective(DynamicComponentLoader dcl, ElementRef ref) {
    dcl.loadIntoNewLocation(... ref) // Throws right now
  }
}
```

Workaround:

```dart
var elementInjector = internalView(elementRef.parentView)
    .elementInjectors[elementRef.boundElementIndex];
var hostComponentElementRef = elementInjector.getHost()
    .getElementRef();
```

I'm denoting P3, because there is a simple enough workaround that can be hidden away in a utility class, but I may bump if others run into the same issue.

### PR DESCRIPTION
**Pull request by tbosch**
…edded views

Closes #2472
Closes #2339

BREAKING CHANGE
- `DynamicComponentLoader.loadInto{Existing,New}Location` is removed
  - use `DynamicComponentLoader.loadNextToLocation` instead
- `DynamicComponentLoader.loadNextToExistingLocation` was renamed into
  `DynamicComponentLoader.loadNextToLocation`
- `AppViewManager.{create,destroy}Free{Host,Embedded}View` was removed
  - use `AppViewManager.createViewInContainer` and then move the view nodes
    manually around via `DomRenderer.getRootNodes()`

### CODE REVIEW

File: modules/angular2/src/core/compiler/compiler.ts [hunk 1]
```diff
@@ -94,20 +107,19 @@ export class Compiler {
...
+    if (isPresent(hostAppProtoView)) {
+      hostPvPromise = PromiseWrapper.resolve(hostAppProtoView);
+    } else {
+      hostPvPromise = this._render.compileHost(directiveMetadata)
+                          .then((hostRenderPv) => {
+                            return this._compileNestedProtoViews(componentBinding, hostRenderPv,
+                                                                 [componentBinding]);
+                          });
+    }
+    return hostPvPromise.then((hostAppProtoView) => { return new ProtoViewRef(hostAppProtoView); });
```
Comment (tbosch) [inline modules/angular2/src/core/compiler/compiler.ts]: Maybe remove `{`

**Comment by tbosch** [comment]
Reviewed in person with @vsavkin
