### PR TITLE
Router bug fixes

### LINKED ISSUE #9480: [GuardChecks] Cannot read _routeConfig of null
_From @francois-appliware on June 14, 2016 13:47_

Hi,

I am working with the new router and had an issue that I "managed to resolve", but as I don't quite understand how everything works under the hood I prefer to open this issue and try to understand what is going on.

In my application, I have a few routes as following :
```javascript
{ path: '/dashboard', component: DashboardComponent },
{
    path: '/companies', component: CompanyComponent, children: [
        { path: '/details/:id', component: CompanyDetailComponent },
        { path: '/new', component: CompanyEditComponent },
        { path: '/', component: CompanyDetailComponent, index: true }
    ]
},
{
    path: '/keys', component: KeyComponent, children: [
        { path: '/details/:id', component: KeyDetailComponent },
        { path: '/new', component: KeyEditComponent },
        { path: '/', component: CompanyDetailComponent, index: true }
    ]
}
```

When I am navigating from companies to keys, I have the following error : 

> Error {rejection: TypeError: Cannot read property '_routeConfig' of null
    at GuardChecks.runCanDeactivate (http://l…, promise: ZoneAwarePromise, zone: Zone, task: ZoneTask, message: "Uncaught (in promise): TypeError: Cannot read property '_routeConfig' of null"}

So I went ahead and downloaded the code to see what was going on inside that "GuardChecks".

For what I understand, it is used for the CanActivate / CanDeactivate (that I do not use in any of my components). Also, from what I understand, it is working with nullable values (in my case, where I don't have such guards).

Problem is, at some point in adds a check **with** a null value that throws the previous error mentioned above.

I managed to solve my issue by replacing the following line inside "router.js" inside the method _GuardChecks.prototype.runCanDeactivate = function (component, curr)_
`var canDeactivate = curr._routeConfig ? curr._routeConfig.canDeactivate : null;`
by the following : 
`var canDeactivate = curr ? (curr._routeConfig ? curr._routeConfig.canDeactivate : null) : null;`

(Yes, it's ugly but that's a hotfix so I can continue working)
I think the check can be set before the 'runCanDeactivate', where the checks are added, maybe in the traverseRoutes method inside GuardChecks.

Is this a known bug or a real bug and needs a fix or is it intended ?

Thank you.

_Copied from original issue: angular/vladivostok#48_

### PR DESCRIPTION
**Pull request by vsavkin**
Closes #9480, #9417, #8603, #9397, #9418

### CODE REVIEW

File: modules/@angular/router/src/router_state.ts [hunk 1]
```diff
@@ -188,10 +188,14 @@ function serializeNode(node: TreeNode<ActivatedRouteSnapshot>): string {
...
 export function advanceActivatedRoute(route: ActivatedRoute): void {
-  if (route.snapshot && !shallowEqual(route.snapshot.params, route._futureSnapshot.params)) {
+  if (route.snapshot) {
+    if (!shallowEqual(route.snapshot.params, route._futureSnapshot.params)) {
+      (<any>route.params).next(route._futureSnapshot.params);
+    }
+    if (!shallowEqualArrays(route.snapshot.url, route._futureSnapshot.url)) {
+      (<any>route.url).next(route._futureSnapshot.url);
+    }
     route.snapshot = route._futureSnapshot;
```
Comment (zhura) [inline modules/@angular/router/src/router_state.ts]: @vsavkin What is happened when user decide to get current route snapshot in `this.route.url.subscribe` ? Does he/she get current snapshot or previous?
