### PR TITLE
fix(router): ignore null or undefined query parameters

### LINKED ISSUE #7543: Make router ignore null or undefined optional parameters
When I do `router.navigate(['RouteName', { a: undefined}])` where a is optional parameter (i.e. query parameter) I get `/routeurl;a=`

To avoid that I have to explicitly `delete params['a']`. 

Can we make it not produce parameters for for null and undefined properties?

### PR DESCRIPTION
**Pull request by DzmitryShylovich**
Fixes https://github.com/angular/angular/issues/7543

### CODE REVIEW

File: modules/@angular/router/src/router.ts [hunk 1]
```diff
@@ -520,11 +523,21 @@ export class Router {
     if (url instanceof UrlTree) {
       return containsTree(this.currentUrlTree, url, exact);
     } else {
-      const urlTree = this.urlSerializer.parse(url);
+      const urlTree = this.urlSerializer.parse(<string>url);
```
Comment (vicb) [inline modules/@angular/router/src/router.ts]: revert

**Comment by alxhub** [comment]
@DzmitryShylovich can you rebase this please? Thanks :)

**Comment by DzmitryShylovich** [comment]
@alxhub done
