### PR TITLE
fix(di): injecting null causes a cyclic dependency

### LINKED ISSUE #2831: DI: support factories that return null
Currently they cause a cyclic dependency error

### PR DESCRIPTION
**Pull request by vsavkin**
Closes #2831

### CODE REVIEW

File: modules/angular2/test/di/injector_spec.ts [hunk 1]
```diff
@@ -82,197 +82,232 @@ class NoAnnotations {
...
+    bind('binding6').toValue(1),
+    bind('binding7').toValue(1),
+    bind('binding8').toValue(1),
+    bind('binding9').toValue(1)
+  ];
+
+  [{strategy: 'inline', bindings: []},
+   {
+     strategy: 'dynamic',
+     bindings: dynamicBindings
```
Comment (tbosch) [inline modules/angular2/test/di/injector_spec.ts]: check whether the right strategy is used.
