### PR TITLE
fix(core): run animation queue in application root injector context

### LINKED ISSUE #65628: animate.leave prevents removal of dynamically created components
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

I am opening this issue as a follow-up to discussion in [#65612](https://github.com/angular/angular/issues/65612). I have encountered a similar behavior where animate.leave prevents components from being destroyed/removed from DOM, specifically when using dynamically created components.

I have a setup with a dynamic-list component that contains a list of dynamically created Notification components.
- The Notification component is animated and designed to remove itself from the list when clicked.
- When animate.leave is applied, animations stop working entirely, and all animated elements fail to be removed from the DOM upon interaction.
- If animate.leave is commented out, the removal works as expected.

**Steps to reproduce:**
- Open reproduction link
- Click on toggle and content should be displayed with animation
- Click “add to list” (multiple times if desired).
- Click any item in the list — it should remove itself, but nothing happens.
- No animations work at this point: items in the dynamic list remain in the DOM, and the toggle no longer removes content.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/krhlk1js

### Please provide the exception or error you saw

```true

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI       : 21.0.0
Angular           : 21.0.0
Node.js           : 20.19.1
Package Manager   : npm 10.8.2
Operating System  : linux x64

┌───────────────────────────┬───────────────────┬───────────────────┐
│ Package                   │ Installed Version │ Requested Version │
├───────────────────────────┼───────────────────┼───────────────────┤
│ @angular/animations       │ 21.0.0            │ ^21.0.0           │
│ @angular/build            │ 21.0.0            │ ^21.0.0           │
│ @angular/cdk              │ 21.0.0            │ ^21.0.0           │
│ @angular/cli              │ 21.0.0            │ ^21.0.0           │
│ @angular/common           │ 21.0.0            │ ^21.0.0           │
│ @angular/compiler         │ 21.0.0            │ ^21.0.0           │
│ @angular/compiler-cli     │ 21.0.0            │ ^21.0.0           │
│ @angular/core             │ 21.0.0            │ ^21.0.0           │
│ @angular/forms            │ 21.0.0            │ ^21.0.0           │
│ @angular/material         │ 21.0.0            │ ^21.0.0           │
│ @angular/platform-browser │ 21.0.0            │ ^21.0.0           │
│ rxjs                      │ 7.8.2             │ ~7.8.0            │
│ typescript                │ 5.9.3             │ ~5.9.2            │
│ zone.js                   │ 0.15.1            │ ~0.15.0           │
└───────────────────────────┴───────────────────┴───────────────────┘
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by thePunderWoman**
In the case that a component injector is destroyed before the animation queue runs, the animation queue would fail to run because it was using a destroyed injector. This commit changes the animation queue to run in the context of the Application root injector, which is not destroyed until the app is destroyed.

fixes: #65628

### CODE REVIEW

File: packages/core/src/animation/queue.ts [hunk 1]
```diff
@@ -68,6 +68,7 @@ export function removeFromAnimationQueue(injector: Injector, animationData: Anim
 
 export function scheduleAnimationQueue(injector: Injector) {
   const animationQueue = injector.get(ANIMATION_QUEUE);
+  const environmentInjector = injector.get(EnvironmentInjector);
```
Comment (JoostK) [inline packages/core/src/animation/queue.ts]: This can be moved within the if-block.

Also, can this have a test :-)

Comment (thePunderWoman) [reply packages/core/src/animation/queue.ts]: Moved. Test wise, I don't know that this really needs it. The fact that the entire animation test suite still passes should suffice.

**Review by JoostK — APPROVED** [review]

**Review by AndrewKushnir — APPROVED** [review]

File: packages/core/src/animation/queue.ts (hunk 1 above)
Comment (thePunderWoman) [reply packages/core/src/animation/queue.ts]: I managed to add a test. It was not an easy setup, but it does cover this case.

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository. The changes were merged into the following branches:

- main: d8ab83ca82c36faacae9fc1a01e9eb9762e679fc
- 21.0.x: 8c3304c766131b031b736ee3fe2ec9c9a42fbe07
