### PR TITLE
fix(compiler): handle nested brackets in host object bindings

### LINKED ISSUE #68039: CSS class binding with the @Component decorator host propery doesn't render correctly
### Which @angular/* package(s) are the source of the bug?

compiler, Don't known / other

### Is this a regression?

Yes

### Description

With following component, and Tailwind complex classes. The class name `md:col-[-3/-1]` renders as `md:col-[-3/-1` instead.

```typescript
@Component({
  selector: 'test-card',
  host: {
    '[class.md:col-[-3/-1]]': 'featured()',
  },
  template: 'Something'
})
export class TestComponent {
  readonly featured = input<boolean>(false);

  /*
  This is the current workaround
  @HostBinding('class.md:col-[-3/-1]')
  get isFeatured() {
    return this.featured();
  }
  */
}
```

# Verified by unit test
```typescript
describe('TestComponent', () => {
  let fixture: ComponentFixture<TestComponent>;
  
  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [TestComponent],
    }).compileComponents();

    // Set required inputs
    fixture = TestBed.createComponent(TestComponent); 
  });

  it('should add featured CSS classes when featured is true', async () => {
    fixture.componentRef.setInput('featured', true);
    fixture.detectChanges();
    await fixture.whenStable();

    const hostElement: HTMLElement = fixture.nativeElement;

    expect(hostElement.classList.contains('md:col-[-3/-1')).toBe(false);  // fails ( it renders this instead )
    expect(hostElement.classList.contains('md:col-[-3/-1]')).toBe(true);  // fails ( the rendering is incorrect )
  });
});
```

### Please provide a link to a minimal reproduction of the bug

_No response_

### Please provide the exception or error you saw

```true
The host attribute binding via @Component host property CSS class doesn't render the same as @HostBinding decorator. @HostBinding decorator works correctly.

Expected:
Host element class contains `md:col-[-3/-1]` when featured input is true

Actual:
Host element class contains `md:col-[-3/-1` when featured input is true
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI       : 21.2.6
Angular           : 21.2.7
Node.js           : 24.14.1
Package Manager   : npm 11.6.2
Operating System  : win32 x64

┌───────────────────────────────┬───────────────────┬───────────────────┐
│ Package                       │ Installed Version │ Requested Version │
├───────────────────────────────┼───────────────────┼───────────────────┤
│ @angular-devkit/build-angular │ 21.2.6            │ ~21.2.0           │
│ @angular-devkit/core          │ 21.2.6            │ ~21.2.0           │
│ @angular-devkit/schematics    │ 21.2.6            │ ~21.2.0           │
│ @angular/build                │ 21.2.6            │ ~21.2.0           │
│ @angular/cli                  │ 21.2.6            │ ~21.2.0           │
│ @angular/common               │ 21.2.7            │ ~21.2.0           │
│ @angular/compiler             │ 21.2.7            │ ~21.2.0           │
│ @angular/compiler-cli         │ 21.2.7            │ ~21.2.0           │
│ @angular/core                 │ 21.2.7            │ ~21.2.0           │
│ @angular/forms                │ 21.2.7            │ ~21.2.0           │
│ @angular/language-service     │ 21.2.7            │ ~21.2.0           │
│ @angular/platform-browser     │ 21.2.7            │ ~21.2.0           │
│ @angular/platform-server      │ 21.2.7            │ ~21.2.0           │
│ @angular/router               │ 21.2.7            │ ~21.2.0           │
│ @angular/ssr                  │ 21.2.6            │ ~21.2.0           │
│ @schematics/angular           │ 21.2.6            │ ~21.2.0           │
│ rxjs                          │ 7.8.2             │ ~7.8.0            │
│ typescript                    │ 5.9.3             │ ~5.9.2            │
│ vitest                        │ 4.1.2             │ ~4.1.0            │
└───────────────────────────────┴───────────────────┴───────────────────┘
```

### Anything else?

Related Tailwind class documentation: https://tailwindcss.com/docs/grid-column#using-a-custom-value
Yup, Tailwind is weird.

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes that we were parsing bindings in the `host` object with a regex that didn't account for nested brackets which may come up with something like Tailwind.

Fixes #68039.

### CODE REVIEW

File: packages/compiler-cli/test/compliance/test_cases/r3_view_compiler_styling/class_bindings/host_class_binding_special_chars.js [hunk 1]
```diff
@@ -3,7 +3,7 @@ $r3$.ɵɵdefineComponent({
   hostVars: 6,
   hostBindings: function MyComponent_HostBindings(rf, ctx) {
     if (rf & 2) {
-      $r3$.ɵɵclassProp("text-primary/80", ctx.expr)("data-active:text-green-300/80", ctx.expr)("data-[size='large'", ctx.expr);
+      $r3$.ɵɵclassProp("text-primary/80", ctx.expr)("data-active:text-green-300/80", ctx.expr)("data-[size='large']:p-8", ctx.expr);
```
Comment (crisbeto) [inline packages/compiler-cli/test/compliance/test_cases/r3_view_compiler_styling/class_bindings/host_class_binding_special_chars.js:6]: Fun part is that I captured this in a test back in #62742, but didn't address it 😅

**Review by JoostK — APPROVED** [review]

**Comment by crisbeto** [comment]
[Passing TGP](http://test/OCL:895172229:BASE:895238168:1775470453998:d88106eb)

**Comment by crisbeto** [comment]
This is blocked until we can clean up a couple of internal clients.

**Comment by crisbeto** [comment]
Caretaker note: presubmit failure is unrelated.

**Comment by atscott** [comment]
This PR was merged into the repository. The changes were merged into the following branches:

- main: 2ce0e98f79a02ddc550d00580e8e232cfed3bfb2
- 21.2.x: e40d378f3e3e7e57a45c8fbd9565ee06a3a6a13f
