### PR TITLE
fix(aio): remove `...` separator from search results

### LINKED ISSUE #17233: Search results contain odd ellipses in the middle of the result list
screen shot 2017-06-05 at 11 56 24 pm

### PR DESCRIPTION
**Pull request by petebacondarwin**
An ellipsis was used to separate the most relevant search
results from the alphabetic list. The separator was confusing
because it was not clear what it represented.

This has been removed and the most relevant results are now
indicated by styling with a more bold font and a bit of whitespace
between them and the rest of the results.

To keep things consistent, if there are fewer than 5 results all the
results are now displayed as priorityPages.

Closes #17233

### CODE REVIEW

**Comment by petebacondarwin** [comment]
The results now look like this:
screen shot 2017-06-07 at 13 46 28

**Review by gkalpak — CHANGES_REQUESTED** [review]
LGTM except for the fact that on some screens the different font-weights are rendered the same.

**Review by IgorMinar — COMMENTED** [review]
@gkalpak on what kind of screens? I can't repro the issue. This change looks good to me.

**Comment by gkalpak** [comment]
> @gkalpak on what kind of screens? I can't repro the issue.

On my screen and on @Foxandxss' screen :smiley:

**Comment by IgorMinar** [comment]
@gkalpak maybe it's a dpi issue? would increasing the weight a bit more do the trick?

**Comment by gkalpak** [comment]
Possibly. @petebacondarwin said he would change the weights to just use `normal` and `bold` instead.

**Comment by petebacondarwin** [comment]
@gkalpak is correct. The difference between 300 and 400 weight is not visible on some computers.
Also, the count of results in each area was wrong.

**Comment by petebacondarwin** [comment]
I have fixed the font weight and the totals. PTAL

File: aio/src/app/search/search-results/search-results.component.ts [hunk 1]
```diff
@@ -60,8 +60,10 @@ export class SearchResultsComponent implements OnInit, OnDestroy {
     });
     const keys = Object.keys(searchAreaMap).sort((l, r) => l > r ? 1 : -1);
     return keys.map(name => {
-      let pages = searchAreaMap[name];
-      const priorityPages = pages.length > 10 ? searchAreaMap[name].slice(0, 5) : [];
+      let pages: SearchResult[] = searchAreaMap[name];
+
+      // Extract the top 5 most relevant results as priorityPages
+      const priorityPages = pages.splice(0, 5);
```
Comment (gkalpak) [inline aio/src/app/search/search-results/search-results.component.ts]: Oh, you sneaked a `p` into `slice`. Sneaky 😛

**Comment by gkalpak** [comment]
Didn't we have a test for the totals? We should :wink:

**Review by gkalpak — APPROVED** [review]
It still doesn't look that much different on my screen. Maybe a little more space between the top results or some kind of subtle separator would make the distinction more obvious.

search-results

But not a blocker. LGTM otherwise.

**Comment by petebacondarwin** [comment]
I think the idea was not to make the difference to significant but to make it not too confusing when there were some in alphabetic order and so not.

**Comment by petebacondarwin** [comment]
I added a test for the count of result.
