### PR TITLE
fix(language-service): infer correct type of `?.` expressions

### LINKED ISSUE #15885: language service: Null is not removed from type using `?.` operator
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**

Language service does not correctly remove `null` from types when using the `?.` operator.
 
**Minimal reproduction of the problem with instructions**

1. Start with the `quickstart` example.

2. Add `"strictNullChecks": true` to the `tsconfig.json` file.

3. To `AppComponent` in `app.component.ts` add:
```  
test: {a: number, b: number} | null = {
    a: 1,
    b: 2
  }
```

4.  To the template in `app.component.ts` add:
```
  {{test?.a}}
```

EXPECTED: No errors and the hover over `a` to show a member of the anonymous type defined in `AppComponent`
RECEIVED: A diagnostic `Identifier 'a' is not defined.`

### PR DESCRIPTION
**Pull request by chuckjaz**
Fixes #15885

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
```

**What is the current behavior?** (You can also link to an open issue here)

The language service would not infer the correct type for `?.` operators.

#15885 

**What is the new behavior?**

The language service now correctly strips null and undefined from the type before looking for type members.

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

### CODE REVIEW

File: packages/language-service/test/diagnostics_spec.ts [hunk 1]
```diff
@@ -258,6 +258,29 @@ describe('diagnostics', () => {
...
+          \`
+        })
+        export class MyComponent {
+          test: {a: number, b: number} | null = {
+            a: 1,
+            b: 2
+          };
+        }
+      `,
+          fileName => onlyModuleDiagnostics(ngService.getDiagnostics(fileName)));
```
Comment (vicb) [inline packages/language-service/test/diagnostics_spec.ts]: nit: rename to `expectOnlyModuleDiagnostics` ?

**Review by vicb — APPROVED** [review]
